// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_A: &[PresetEntry] = &[
    PresetEntry { descriptor: &abacus::DESCRIPTOR, create: abacus::create_abacus },
    PresetEntry { descriptor: &abliteration_ai::DESCRIPTOR, create: abliteration_ai::create_abliteration_ai },
    PresetEntry { descriptor: &ai21::DESCRIPTOR, create: ai21::create_ai21 },
    PresetEntry { descriptor: &ai302::DESCRIPTOR, create: ai302::create_ai302 },
    PresetEntry { descriptor: &ai_router::DESCRIPTOR, create: ai_router::create_ai_router },
    PresetEntry { descriptor: &aiand::DESCRIPTOR, create: aiand::create_aiand },
    PresetEntry { descriptor: &aibadgr::DESCRIPTOR, create: aibadgr::create_aibadgr },
    PresetEntry { descriptor: &aigc2d::DESCRIPTOR, create: aigc2d::create_aigc2d },
    PresetEntry { descriptor: &aihubmix::DESCRIPTOR, create: aihubmix::create_aihubmix },
    PresetEntry { descriptor: &ails::DESCRIPTOR, create: ails::create_ails },
    PresetEntry { descriptor: &aiml::DESCRIPTOR, create: aiml::create_aiml },
    PresetEntry { descriptor: &aki_io::DESCRIPTOR, create: aki_io::create_aki_io },
    PresetEntry { descriptor: &albert::DESCRIPTOR, create: albert::create_albert },
    PresetEntry { descriptor: &alibaba::DESCRIPTOR, create: alibaba::create_alibaba },
    PresetEntry { descriptor: &alibaba_coding_plan::DESCRIPTOR, create: alibaba_coding_plan::create_alibaba_coding_plan },
    PresetEntry { descriptor: &alibaba_coding_plan_cn::DESCRIPTOR, create: alibaba_coding_plan_cn::create_alibaba_coding_plan_cn },
    PresetEntry { descriptor: &alibaba_token_plan::DESCRIPTOR, create: alibaba_token_plan::create_alibaba_token_plan },
    PresetEntry { descriptor: &alibaba_token_plan_cn::DESCRIPTOR, create: alibaba_token_plan_cn::create_alibaba_token_plan_cn },
    PresetEntry { descriptor: &ambient::DESCRIPTOR, create: ambient::create_ambient },
    PresetEntry { descriptor: &anyapi::DESCRIPTOR, create: anyapi::create_anyapi },
    PresetEntry { descriptor: &anyscale::DESCRIPTOR, create: anyscale::create_anyscale },
    PresetEntry { descriptor: &apertis::DESCRIPTOR, create: apertis::create_apertis },
    PresetEntry { descriptor: &api2d::DESCRIPTOR, create: api2d::create_api2d },
    PresetEntry { descriptor: &api2gpt::DESCRIPTOR, create: api2gpt::create_api2gpt },
    PresetEntry { descriptor: &apiserpent::DESCRIPTOR, create: apiserpent::create_apiserpent },
    PresetEntry { descriptor: &atlascloud::DESCRIPTOR, create: atlascloud::create_atlascloud },
    PresetEntry { descriptor: &atomic_chat::DESCRIPTOR, create: atomic_chat::create_atomic_chat },
    PresetEntry { descriptor: &auriko::DESCRIPTOR, create: auriko::create_auriko },
    PresetEntry { descriptor: &azure_ai::DESCRIPTOR, create: azure_ai::create_azure_ai },
];

/// The `abacus` preset (Abacus).
pub mod abacus {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "abacus",
        display: "Abacus",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://routellm.abacus.ai/v1",
        env_var: "ABACUS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `abacus` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_abacus(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `abacus` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn abacus() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_abacus(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use abacus::{create_abacus, abacus};

/// The `abliteration_ai` preset (Abliteration AI).
pub mod abliteration_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "abliteration_ai",
        display: "Abliteration AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.abliteration.ai/v1",
        env_var: "ABLIT_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `abliteration_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_abliteration_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `abliteration_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn abliteration_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_abliteration_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use abliteration_ai::{create_abliteration_ai, abliteration_ai};

/// The `ai21` preset (AI21 Labs).
pub mod ai21 {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ai21",
        display: "AI21 Labs",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.ai21.ai/v1",
        env_var: "AI21_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ai21` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ai21(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ai21` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ai21() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ai21(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ai21::{create_ai21, ai21};

/// The `ai302` preset (302.AI).
pub mod ai302 {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ai302",
        display: "302.AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.302.ai/v1",
        env_var: "AI302_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ai302` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ai302(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ai302` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ai302() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ai302(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ai302::{create_ai302, ai302};

/// The `ai_router` preset (AI-ROUTER).
pub mod ai_router {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ai_router",
        display: "AI-ROUTER",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.ai-router.dev/v1",
        env_var: "AI_ROUTER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ai_router` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ai_router(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ai_router` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ai_router() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ai_router(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ai_router::{create_ai_router, ai_router};

/// The `aiand` preset (AIand).
pub mod aiand {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aiand",
        display: "AIand",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.aiand.com/v1",
        env_var: "AIAND_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aiand` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aiand(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aiand` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aiand() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aiand(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aiand::{create_aiand, aiand};

/// The `aibadgr` preset (AI Badgr).
pub mod aibadgr {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aibadgr",
        display: "AI Badgr",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.aibadgr.com/v1",
        env_var: "AIBADGR_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aibadgr` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aibadgr(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aibadgr` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aibadgr() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aibadgr(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aibadgr::{create_aibadgr, aibadgr};

/// The `aigc2d` preset (AIGC2D).
pub mod aigc2d {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aigc2d",
        display: "AIGC2D",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.aigc2d.com/v1",
        env_var: "AIGC2D_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aigc2d` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aigc2d(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aigc2d` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aigc2d() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aigc2d(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aigc2d::{create_aigc2d, aigc2d};

/// The `aihubmix` preset (AIHubMix).
pub mod aihubmix {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aihubmix",
        display: "AIHubMix",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://aihubmix.com/v1",
        env_var: "AIHUBMIX_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aihubmix` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aihubmix(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aihubmix` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aihubmix() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aihubmix(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aihubmix::{create_aihubmix, aihubmix};

/// The `ails` preset (AILS).
pub mod ails {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ails",
        display: "AILS",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.caipacity.com/v1",
        env_var: "AILS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ails` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ails(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ails` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ails() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ails(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ails::{create_ails, ails};

/// The `aiml` preset (AI/ML API).
pub mod aiml {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aiml",
        display: "AI/ML API",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.aimlapi.com/v1",
        env_var: "AIML_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aiml` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aiml(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aiml` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aiml() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aiml(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aiml::{create_aiml, aiml};

/// The `aki_io` preset (AKI.IO).
pub mod aki_io {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "aki_io",
        display: "AKI.IO",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://aki.io/openai/v1",
        env_var: "AKI_IO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `aki_io` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_aki_io(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `aki_io` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn aki_io() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_aki_io(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use aki_io::{create_aki_io, aki_io};

/// The `albert` preset (Albert).
pub mod albert {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "albert",
        display: "Albert",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.albert.ai/v1",
        env_var: "ALBERT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `albert` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_albert(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `albert` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn albert() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_albert(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use albert::{create_albert, albert};

/// The `alibaba` preset (Alibaba Cloud (DashScope)).
pub mod alibaba {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "alibaba",
        display: "Alibaba Cloud (DashScope)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        env_var: "ALIBABA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `alibaba` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_alibaba(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `alibaba` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn alibaba() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_alibaba(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use alibaba::{create_alibaba, alibaba};

/// The `alibaba_coding_plan` preset (Alibaba Coding Plan).
pub mod alibaba_coding_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "alibaba_coding_plan",
        display: "Alibaba Coding Plan",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://coding-intl.dashscope.aliyuncs.com/v1",
        env_var: "ALIBABA_CODING_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `alibaba_coding_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_alibaba_coding_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `alibaba_coding_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn alibaba_coding_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_alibaba_coding_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use alibaba_coding_plan::{create_alibaba_coding_plan, alibaba_coding_plan};

/// The `alibaba_coding_plan_cn` preset (Alibaba Coding Plan (China)).
pub mod alibaba_coding_plan_cn {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "alibaba_coding_plan_cn",
        display: "Alibaba Coding Plan (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://coding.dashscope.aliyuncs.com/v1",
        env_var: "ALIBABA_CODING_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `alibaba_coding_plan_cn` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_alibaba_coding_plan_cn(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `alibaba_coding_plan_cn` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn alibaba_coding_plan_cn() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_alibaba_coding_plan_cn(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use alibaba_coding_plan_cn::{create_alibaba_coding_plan_cn, alibaba_coding_plan_cn};

/// The `alibaba_token_plan` preset (Alibaba Token Plan).
pub mod alibaba_token_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "alibaba_token_plan",
        display: "Alibaba Token Plan",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
        env_var: "ALIBABA_TOKEN_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `alibaba_token_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_alibaba_token_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `alibaba_token_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn alibaba_token_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_alibaba_token_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use alibaba_token_plan::{create_alibaba_token_plan, alibaba_token_plan};

/// The `alibaba_token_plan_cn` preset (Alibaba Token Plan (China)).
pub mod alibaba_token_plan_cn {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "alibaba_token_plan_cn",
        display: "Alibaba Token Plan (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        env_var: "ALIBABA_TOKEN_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `alibaba_token_plan_cn` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_alibaba_token_plan_cn(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `alibaba_token_plan_cn` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn alibaba_token_plan_cn() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_alibaba_token_plan_cn(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use alibaba_token_plan_cn::{create_alibaba_token_plan_cn, alibaba_token_plan_cn};

/// The `ambient` preset (Ambient).
pub mod ambient {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ambient",
        display: "Ambient",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.ambient.xyz/v1",
        env_var: "AMBIENT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ambient` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ambient(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ambient` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ambient() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ambient(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ambient::{create_ambient, ambient};

/// The `anyapi` preset (AnyAPI).
pub mod anyapi {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "anyapi",
        display: "AnyAPI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.anyapi.ai/v1",
        env_var: "ANYAPI_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `anyapi` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_anyapi(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `anyapi` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn anyapi() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_anyapi(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use anyapi::{create_anyapi, anyapi};

/// The `anyscale` preset (Anyscale).
pub mod anyscale {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "anyscale",
        display: "Anyscale",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.endpoints.anyscale.com/v1",
        env_var: "ANYSCALE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `anyscale` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_anyscale(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `anyscale` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn anyscale() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_anyscale(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use anyscale::{create_anyscale, anyscale};

/// The `apertis` preset (Apertis).
pub mod apertis {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "apertis",
        display: "Apertis",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.stima.tech/v1",
        env_var: "STIMA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `apertis` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_apertis(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `apertis` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn apertis() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_apertis(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use apertis::{create_apertis, apertis};

/// The `api2d` preset (API2D).
pub mod api2d {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "api2d",
        display: "API2D",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://oa.api2d.net/v1",
        env_var: "API2D_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `api2d` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_api2d(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `api2d` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn api2d() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_api2d(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use api2d::{create_api2d, api2d};

/// The `api2gpt` preset (API2GPT).
pub mod api2gpt {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "api2gpt",
        display: "API2GPT",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.api2gpt.com/v1",
        env_var: "API2GPT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `api2gpt` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_api2gpt(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `api2gpt` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn api2gpt() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_api2gpt(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use api2gpt::{create_api2gpt, api2gpt};

/// The `apiserpent` preset (API Serpent).
pub mod apiserpent {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "apiserpent",
        display: "API Serpent",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.apiserpent.com/v1",
        env_var: "APISERPENT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `apiserpent` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_apiserpent(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `apiserpent` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn apiserpent() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_apiserpent(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use apiserpent::{create_apiserpent, apiserpent};

/// The `atlascloud` preset (AtlasCloud).
pub mod atlascloud {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "atlascloud",
        display: "AtlasCloud",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.atlascloud.com/v1",
        env_var: "ATLASCLOUD_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `atlascloud` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_atlascloud(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `atlascloud` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn atlascloud() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_atlascloud(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use atlascloud::{create_atlascloud, atlascloud};

/// The `atomic_chat` preset (Atomic Chat).
pub mod atomic_chat {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "atomic_chat",
        display: "Atomic Chat",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:1337/v1",
        env_var: "ATOMIC_CHAT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `atomic_chat` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_atomic_chat(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `atomic_chat` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn atomic_chat() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_atomic_chat(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use atomic_chat::{create_atomic_chat, atomic_chat};

/// The `auriko` preset (Auriko).
pub mod auriko {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "auriko",
        display: "Auriko",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.auriko.ai/v1",
        env_var: "AURIKO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `auriko` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_auriko(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `auriko` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn auriko() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_auriko(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use auriko::{create_auriko, auriko};

/// The `azure_ai` preset (Azure AI).
pub mod azure_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "azure_ai",
        display: "Azure AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://models.inference.ai.azure.com",
        env_var: "AZURE_AI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `azure_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_azure_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `azure_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn azure_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_azure_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use azure_ai::{create_azure_ai, azure_ai};
