// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_D: &[PresetEntry] = &[
    PresetEntry { descriptor: &daoxe::DESCRIPTOR, create: daoxe::create_daoxe },
    PresetEntry { descriptor: &darkbloom::DESCRIPTOR, create: darkbloom::create_darkbloom },
    PresetEntry { descriptor: &databricks::DESCRIPTOR, create: databricks::create_databricks },
    PresetEntry { descriptor: &datarobot::DESCRIPTOR, create: datarobot::create_datarobot },
    PresetEntry { descriptor: &deepbricks::DESCRIPTOR, create: deepbricks::create_deepbricks },
    PresetEntry { descriptor: &deepinfra::DESCRIPTOR, create: deepinfra::create_deepinfra },
    PresetEntry { descriptor: &deepseek::DESCRIPTOR, create: deepseek::create_deepseek },
    PresetEntry { descriptor: &digitalocean::DESCRIPTOR, create: digitalocean::create_digitalocean },
    PresetEntry { descriptor: &dinference::DESCRIPTOR, create: dinference::create_dinference },
    PresetEntry { descriptor: &docker_model_runner::DESCRIPTOR, create: docker_model_runner::create_docker_model_runner },
    PresetEntry { descriptor: &doubao::DESCRIPTOR, create: doubao::create_doubao },
    PresetEntry { descriptor: &doubleword::DESCRIPTOR, create: doubleword::create_doubleword },
    PresetEntry { descriptor: &drun::DESCRIPTOR, create: drun::create_drun },
];

/// The `daoxe` preset (DaoXE).
pub mod daoxe {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "daoxe",
        display: "DaoXE",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://daoxe.com/v1",
        env_var: "DAOXE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `daoxe` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_daoxe(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `daoxe` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn daoxe() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_daoxe(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use daoxe::{create_daoxe, daoxe};

/// The `darkbloom` preset (Darkbloom).
pub mod darkbloom {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "darkbloom",
        display: "Darkbloom",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.darkbloom.dev/v1",
        env_var: "DARKBLOOM_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `darkbloom` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_darkbloom(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `darkbloom` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn darkbloom() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_darkbloom(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use darkbloom::{create_darkbloom, darkbloom};

/// The `databricks` preset (Databricks).
pub mod databricks {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "databricks",
        display: "Databricks",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://databricks.com/serving-endpoints",
        env_var: "DATABRICKS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `databricks` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_databricks(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `databricks` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn databricks() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_databricks(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use databricks::{create_databricks, databricks};

/// The `datarobot` preset (DataRobot).
pub mod datarobot {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "datarobot",
        display: "DataRobot",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://app.datarobot.com/api/v2",
        env_var: "DATAROBOT_API_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `datarobot` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_datarobot(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `datarobot` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn datarobot() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_datarobot(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use datarobot::{create_datarobot, datarobot};

/// The `deepbricks` preset (DeepBricks).
pub mod deepbricks {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "deepbricks",
        display: "DeepBricks",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.deepbricks.ai/v1",
        env_var: "DEEPBRICKS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `deepbricks` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_deepbricks(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `deepbricks` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn deepbricks() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_deepbricks(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use deepbricks::{create_deepbricks, deepbricks};

/// The `deepinfra` preset (DeepInfra).
pub mod deepinfra {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "deepinfra",
        display: "DeepInfra",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.deepinfra.com/v1/openai",
        env_var: "DEEPINFRA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `deepinfra` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_deepinfra(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `deepinfra` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn deepinfra() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_deepinfra(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use deepinfra::{create_deepinfra, deepinfra};

/// The `deepseek` preset (DeepSeek).
pub mod deepseek {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "deepseek",
        display: "DeepSeek",
        family: PresetFamily::DeepSeek,
        base_url: "https://api.deepseek.com/v1",
        env_var: "DEEPSEEK_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `deepseek` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_deepseek(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `deepseek` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn deepseek() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_deepseek(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use deepseek::{create_deepseek, deepseek};

/// The `digitalocean` preset (DigitalOcean).
pub mod digitalocean {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "digitalocean",
        display: "DigitalOcean",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://inference.do-ai.run",
        env_var: "DIGITALOCEAN_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `digitalocean` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_digitalocean(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `digitalocean` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn digitalocean() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_digitalocean(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use digitalocean::{create_digitalocean, digitalocean};

/// The `dinference` preset (DInference).
pub mod dinference {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "dinference",
        display: "DInference",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.dinference.com/v1",
        env_var: "DINFERENCE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `dinference` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_dinference(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `dinference` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn dinference() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_dinference(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use dinference::{create_dinference, dinference};

/// The `docker_model_runner` preset (Docker Model Runner).
pub mod docker_model_runner {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "docker_model_runner",
        display: "Docker Model Runner",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://model-runner.docker.internal/engines/llama.cpp/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("DOCKER_MODEL_RUNNER_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `docker_model_runner` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_docker_model_runner(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `docker_model_runner` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn docker_model_runner() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_docker_model_runner(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use docker_model_runner::{create_docker_model_runner, docker_model_runner};

/// The `doubao` preset (Doubao).
pub mod doubao {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "doubao",
        display: "Doubao",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        env_var: "ARK_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `doubao` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_doubao(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `doubao` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn doubao() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_doubao(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use doubao::{create_doubao, doubao};

/// The `doubleword` preset (Doubleword).
pub mod doubleword {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "doubleword",
        display: "Doubleword",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.doubleword.ai/v1",
        env_var: "DOUBLEWORD_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `doubleword` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_doubleword(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `doubleword` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn doubleword() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_doubleword(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use doubleword::{create_doubleword, doubleword};

/// The `drun` preset (D.Run (China)).
pub mod drun {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "drun",
        display: "D.Run (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://chat.d.run/v1",
        env_var: "DRUN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `drun` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_drun(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `drun` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn drun() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_drun(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use drun::{create_drun, drun};
