// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_E: &[PresetEntry] = &[
    PresetEntry { descriptor: &ebcloud::DESCRIPTOR, create: ebcloud::create_ebcloud },
    PresetEntry { descriptor: &embercloud::DESCRIPTOR, create: embercloud::create_embercloud },
    PresetEntry { descriptor: &empiriolabs::DESCRIPTOR, create: empiriolabs::create_empiriolabs },
    PresetEntry { descriptor: &evroc::DESCRIPTOR, create: evroc::create_evroc },
];

/// The `ebcloud` preset (EBCloud).
pub mod ebcloud {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ebcloud",
        display: "EBCloud",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://maas-api.ebcloud.com/v1",
        env_var: "EBCLOUD_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ebcloud` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ebcloud(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ebcloud` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ebcloud() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ebcloud(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ebcloud::{create_ebcloud, ebcloud};

/// The `embercloud` preset (Embercloud).
pub mod embercloud {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "embercloud",
        display: "Embercloud",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.embercloud.com/v1",
        env_var: "EMBERCLOUD_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `embercloud` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_embercloud(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `embercloud` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn embercloud() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_embercloud(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use embercloud::{create_embercloud, embercloud};

/// The `empiriolabs` preset (EmpirioLabs AI).
pub mod empiriolabs {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "empiriolabs",
        display: "EmpirioLabs AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.empiriolabs.ai/v1",
        env_var: "EMPIRIOLABS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `empiriolabs` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_empiriolabs(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `empiriolabs` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn empiriolabs() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_empiriolabs(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use empiriolabs::{create_empiriolabs, empiriolabs};

/// The `evroc` preset (evroc).
pub mod evroc {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "evroc",
        display: "evroc",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://models.think.evroc.com/v1",
        env_var: "EVROC_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `evroc` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_evroc(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `evroc` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn evroc() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_evroc(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use evroc::{create_evroc, evroc};
