// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_J: &[PresetEntry] = &[
    PresetEntry { descriptor: &jiekou::DESCRIPTOR, create: jiekou::create_jiekou },
    PresetEntry { descriptor: &jlama::DESCRIPTOR, create: jlama::create_jlama },
];

/// The `jiekou` preset (Jiekou.AI).
pub mod jiekou {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "jiekou",
        display: "Jiekou.AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.highwayapi.ai/openai",
        env_var: "JIEKOU_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `jiekou` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_jiekou(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `jiekou` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn jiekou() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_jiekou(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use jiekou::{create_jiekou, jiekou};

/// The `jlama` preset (Jlama).
pub mod jlama {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "jlama",
        display: "Jlama",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8080/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("JLAMA_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `jlama` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_jlama(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `jlama` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn jlama() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_jlama(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use jlama::{create_jlama, jlama};
