// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_K: &[PresetEntry] = &[
    PresetEntry { descriptor: &kenari::DESCRIPTOR, create: kenari::create_kenari },
    PresetEntry { descriptor: &kilo::DESCRIPTOR, create: kilo::create_kilo },
    PresetEntry { descriptor: &kimi::DESCRIPTOR, create: kimi::create_kimi },
    PresetEntry { descriptor: &kimi_for_coding::DESCRIPTOR, create: kimi_for_coding::create_kimi_for_coding },
    PresetEntry { descriptor: &kiro::DESCRIPTOR, create: kiro::create_kiro },
    PresetEntry { descriptor: &kluster_ai::DESCRIPTOR, create: kluster_ai::create_kluster_ai },
    PresetEntry { descriptor: &krutrim::DESCRIPTOR, create: krutrim::create_krutrim },
    PresetEntry { descriptor: &kuae_cloud_coding_plan::DESCRIPTOR, create: kuae_cloud_coding_plan::create_kuae_cloud_coding_plan },
];

/// The `kenari` preset (Kenari).
pub mod kenari {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kenari",
        display: "Kenari",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://kenari.id/v1",
        env_var: "KENARI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kenari` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kenari(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kenari` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kenari() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kenari(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kenari::{create_kenari, kenari};

/// The `kilo` preset (Kilo).
pub mod kilo {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kilo",
        display: "Kilo",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.kilo.ai/v1",
        env_var: "KILO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kilo` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kilo(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kilo` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kilo() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kilo(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kilo::{create_kilo, kilo};

/// The `kimi` preset (Kimi).
pub mod kimi {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kimi",
        display: "Kimi",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.moonshot.ai/v1",
        env_var: "MOONSHOT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kimi` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kimi(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kimi` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kimi() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kimi(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kimi::{create_kimi, kimi};

/// The `kimi_for_coding` preset (Kimi For Coding).
pub mod kimi_for_coding {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kimi_for_coding",
        display: "Kimi For Coding",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.kimi.com/coding/v1",
        env_var: "KIMI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kimi_for_coding` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kimi_for_coding(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kimi_for_coding` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kimi_for_coding() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kimi_for_coding(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kimi_for_coding::{create_kimi_for_coding, kimi_for_coding};

/// The `kiro` preset (Kiro).
pub mod kiro {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kiro",
        display: "Kiro",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.kiro.dev/v1",
        env_var: "KIRO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kiro` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kiro(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kiro` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kiro() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kiro(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kiro::{create_kiro, kiro};

/// The `kluster_ai` preset (Kluster AI).
pub mod kluster_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kluster_ai",
        display: "Kluster AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.kluster.ai/v1",
        env_var: "KLUSTER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kluster_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kluster_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kluster_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kluster_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kluster_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kluster_ai::{create_kluster_ai, kluster_ai};

/// The `krutrim` preset (Krutrim).
pub mod krutrim {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "krutrim",
        display: "Krutrim",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.krutrim.ai/v1",
        env_var: "KRUTRIM_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `krutrim` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_krutrim(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `krutrim` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn krutrim() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_krutrim(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use krutrim::{create_krutrim, krutrim};

/// The `kuae_cloud_coding_plan` preset (KUAE Cloud Coding Plan).
pub mod kuae_cloud_coding_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "kuae_cloud_coding_plan",
        display: "KUAE Cloud Coding Plan",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://coding-plan-endpoint.kuaecloud.net/v1",
        env_var: "KUAE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `kuae_cloud_coding_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_kuae_cloud_coding_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `kuae_cloud_coding_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn kuae_cloud_coding_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_kuae_cloud_coding_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use kuae_cloud_coding_plan::{create_kuae_cloud_coding_plan, kuae_cloud_coding_plan};
