// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_L: &[PresetEntry] = &[
    PresetEntry { descriptor: &lambda_ai::DESCRIPTOR, create: lambda_ai::create_lambda_ai },
    PresetEntry { descriptor: &lemonade::DESCRIPTOR, create: lemonade::create_lemonade },
    PresetEntry { descriptor: &lemonfox_ai::DESCRIPTOR, create: lemonfox_ai::create_lemonfox_ai },
    PresetEntry { descriptor: &libertai::DESCRIPTOR, create: libertai::create_libertai },
    PresetEntry { descriptor: &lilac::DESCRIPTOR, create: lilac::create_lilac },
    PresetEntry { descriptor: &lingyiwanwu::DESCRIPTOR, create: lingyiwanwu::create_lingyiwanwu },
    PresetEntry { descriptor: &litellm_proxy::DESCRIPTOR, create: litellm_proxy::create_litellm_proxy },
    PresetEntry { descriptor: &llama::DESCRIPTOR, create: llama::create_llama },
    PresetEntry { descriptor: &llamacpp::DESCRIPTOR, create: llamacpp::create_llamacpp },
    PresetEntry { descriptor: &llamafile::DESCRIPTOR, create: llamafile::create_llamafile },
    PresetEntry { descriptor: &llamagate::DESCRIPTOR, create: llamagate::create_llamagate },
    PresetEntry { descriptor: &llmgateway::DESCRIPTOR, create: llmgateway::create_llmgateway },
    PresetEntry { descriptor: &llmtr::DESCRIPTOR, create: llmtr::create_llmtr },
    PresetEntry { descriptor: &lmstudio::DESCRIPTOR, create: lmstudio::create_lmstudio },
    PresetEntry { descriptor: &local::DESCRIPTOR, create: local::create_local },
    PresetEntry { descriptor: &localai::DESCRIPTOR, create: localai::create_localai },
    PresetEntry { descriptor: &longcat::DESCRIPTOR, create: longcat::create_longcat },
    PresetEntry { descriptor: &lucidquery::DESCRIPTOR, create: lucidquery::create_lucidquery },
    PresetEntry { descriptor: &lynkr::DESCRIPTOR, create: lynkr::create_lynkr },
];

/// The `lambda_ai` preset (Lambda AI).
pub mod lambda_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lambda_ai",
        display: "Lambda AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lambda.ai/v1",
        env_var: "LAMBDA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lambda_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lambda_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lambda_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lambda_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lambda_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lambda_ai::{create_lambda_ai, lambda_ai};

/// The `lemonade` preset (Lemonade).
pub mod lemonade {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lemonade",
        display: "Lemonade",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://localhost:13305/v1",
        env_var: "LEMONADE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lemonade` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lemonade(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lemonade` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lemonade() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lemonade(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lemonade::{create_lemonade, lemonade};

/// The `lemonfox_ai` preset (Lemonfox AI).
pub mod lemonfox_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lemonfox_ai",
        display: "Lemonfox AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lemonfox.ai/v1",
        env_var: "LEMONFOX_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lemonfox_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lemonfox_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lemonfox_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lemonfox_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lemonfox_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lemonfox_ai::{create_lemonfox_ai, lemonfox_ai};

/// The `libertai` preset (Libertai).
pub mod libertai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "libertai",
        display: "Libertai",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.libertai.io/v1",
        env_var: "LIBERTAI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `libertai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_libertai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `libertai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn libertai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_libertai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use libertai::{create_libertai, libertai};

/// The `lilac` preset (Lilac).
pub mod lilac {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lilac",
        display: "Lilac",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.getlilac.com/v1",
        env_var: "LILAC_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lilac` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lilac(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lilac` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lilac() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lilac(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lilac::{create_lilac, lilac};

/// The `lingyiwanwu` preset (Lingyiwanwu (零一万物)).
pub mod lingyiwanwu {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lingyiwanwu",
        display: "Lingyiwanwu (零一万物)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lingyiwanwu.com/v1",
        env_var: "LINGYIWANWU_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lingyiwanwu` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lingyiwanwu(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lingyiwanwu` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lingyiwanwu() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lingyiwanwu(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lingyiwanwu::{create_lingyiwanwu, lingyiwanwu};

/// The `litellm_proxy` preset (LiteLLM Proxy).
pub mod litellm_proxy {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "litellm_proxy",
        display: "LiteLLM Proxy",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:4000/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LITELLM_PROXY_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `litellm_proxy` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_litellm_proxy(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `litellm_proxy` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn litellm_proxy() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_litellm_proxy(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use litellm_proxy::{create_litellm_proxy, litellm_proxy};

/// The `llama` preset (Llama).
pub mod llama {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llama",
        display: "Llama",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.llama.com/compat/v1/",
        env_var: "LLAMA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llama` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llama(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llama` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llama() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llama(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llama::{create_llama, llama};

/// The `llamacpp` preset (llama.cpp).
pub mod llamacpp {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llamacpp",
        display: "llama.cpp",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8080/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LLAMACPP_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llamacpp` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llamacpp(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llamacpp` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llamacpp() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llamacpp(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llamacpp::{create_llamacpp, llamacpp};

/// The `llamafile` preset (Llamafile).
pub mod llamafile {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llamafile",
        display: "Llamafile",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8080/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LLAMAFILE_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llamafile` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llamafile(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llamafile` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llamafile() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llamafile(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llamafile::{create_llamafile, llamafile};

/// The `llamagate` preset (Llamagate).
pub mod llamagate {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llamagate",
        display: "Llamagate",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.llamagate.dev/v1",
        env_var: "LLAMAGATE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llamagate` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llamagate(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llamagate` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llamagate() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llamagate(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llamagate::{create_llamagate, llamagate};

/// The `llmgateway` preset (LLM Gateway).
pub mod llmgateway {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llmgateway",
        display: "LLM Gateway",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.llmgateway.io/v1",
        env_var: "LLM_GATEWAY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llmgateway` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llmgateway(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llmgateway` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llmgateway() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llmgateway(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llmgateway::{create_llmgateway, llmgateway};

/// The `llmtr` preset (LLMTR).
pub mod llmtr {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "llmtr",
        display: "LLMTR",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://llmtr.com/v1",
        env_var: "LLMTR_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `llmtr` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_llmtr(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `llmtr` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn llmtr() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_llmtr(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use llmtr::{create_llmtr, llmtr};

/// The `lmstudio` preset (LM Studio).
pub mod lmstudio {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lmstudio",
        display: "LM Studio",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:1234/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LMSTUDIO_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lmstudio` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lmstudio(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lmstudio` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lmstudio() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lmstudio(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lmstudio::{create_lmstudio, lmstudio};

/// The `local` preset (Local LLM).
pub mod local {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "local",
        display: "Local LLM",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8080/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LOCAL_LLM_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `local` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_local(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `local` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn local() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_local(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use local::{create_local, local};

/// The `localai` preset (LocalAI).
pub mod localai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "localai",
        display: "LocalAI",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8080/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("LOCALAI_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `localai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_localai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `localai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn localai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_localai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use localai::{create_localai, localai};

/// The `longcat` preset (LongCat).
pub mod longcat {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "longcat",
        display: "LongCat",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.longcat.chat/v1",
        env_var: "LONGCAT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `longcat` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_longcat(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `longcat` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn longcat() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_longcat(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use longcat::{create_longcat, longcat};

/// The `lucidquery` preset (LucidQuery).
pub mod lucidquery {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lucidquery",
        display: "LucidQuery",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lucidquery.com/v1",
        env_var: "LUCIDQUERY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lucidquery` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lucidquery(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lucidquery` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lucidquery() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lucidquery(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lucidquery::{create_lucidquery, lucidquery};

/// The `lynkr` preset (Lynkr).
pub mod lynkr {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "lynkr",
        display: "Lynkr",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://localhost:8081/v1",
        env_var: "LYNKR_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `lynkr` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_lynkr(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `lynkr` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn lynkr() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_lynkr(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use lynkr::{create_lynkr, lynkr};
