// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.
//! The registry rows as explicit factories (283 presets).
//!
//! **Generated** by `scripts/gen_presets.py` from `provider_registry.json`; do
//! not edit by hand (CI runs `gen_presets.py --check`).
//!
//! For every row `<name>`:
//!
//! - `presets::<name>::DESCRIPTOR` is its [`PresetDescriptor`](crate::preset::PresetDescriptor);
//! - `presets::create_<name>(PresetSettings)` creates a [`PresetProvider`](crate::preset::PresetProvider);
//! - `presets::<name>()` is the default instance (created on first use, reads
//!   nothing from the environment, cannot fail).
//!
//! [`lookup`] finds a preset by name for the by-name entry points.

use crate::preset::PresetEntry;

#[rustfmt::skip]
mod a;
#[rustfmt::skip]
mod b;
#[rustfmt::skip]
mod c;
#[rustfmt::skip]
mod d;
#[rustfmt::skip]
mod e;
#[rustfmt::skip]
mod f;
#[rustfmt::skip]
mod g;
#[rustfmt::skip]
mod h;
#[rustfmt::skip]
mod i;
#[rustfmt::skip]
mod j;
#[rustfmt::skip]
mod k;
#[rustfmt::skip]
mod l;
#[rustfmt::skip]
mod m;
#[rustfmt::skip]
mod n;
#[rustfmt::skip]
mod o;
#[rustfmt::skip]
mod p;
#[rustfmt::skip]
mod q;
#[rustfmt::skip]
mod r;
#[rustfmt::skip]
mod s;
#[rustfmt::skip]
mod t;
#[rustfmt::skip]
mod u;
#[rustfmt::skip]
mod v;
#[rustfmt::skip]
mod w;
#[rustfmt::skip]
mod x;
#[rustfmt::skip]
mod z;

pub use a::*;
pub use b::*;
pub use c::*;
pub use d::*;
pub use e::*;
pub use f::*;
pub use g::*;
pub use h::*;
pub use i::*;
pub use j::*;
pub use k::*;
pub use l::*;
pub use m::*;
pub use n::*;
pub use o::*;
pub use p::*;
pub use q::*;
pub use r::*;
pub use s::*;
pub use t::*;
pub use u::*;
pub use v::*;
pub use w::*;
pub use x::*;
pub use z::*;

/// The presets of each initial, in name order.
const GROUPS: &[&[PresetEntry]] = &[
    ENTRIES_A, ENTRIES_B, ENTRIES_C, ENTRIES_D, ENTRIES_E, ENTRIES_F, ENTRIES_G, ENTRIES_H,
    ENTRIES_I, ENTRIES_J, ENTRIES_K, ENTRIES_L, ENTRIES_M, ENTRIES_N, ENTRIES_O, ENTRIES_P,
    ENTRIES_Q, ENTRIES_R, ENTRIES_S, ENTRIES_T, ENTRIES_U, ENTRIES_V, ENTRIES_W, ENTRIES_X,
    ENTRIES_Z,
];

/// Every preset, in name order.
pub fn entries() -> impl Iterator<Item = &'static PresetEntry> {
    GROUPS.iter().flat_map(|group| group.iter())
}

/// The names of every preset, in order.
pub fn names() -> impl Iterator<Item = &'static str> {
    entries().map(|entry| entry.descriptor.name)
}

/// The preset called `name`, or `None`. An unknown name is never mapped to
/// another preset.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static PresetEntry> {
    entries().find(|entry| entry.descriptor.name == name)
}
