// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_P: &[PresetEntry] = &[
    PresetEntry { descriptor: &parasail::DESCRIPTOR, create: parasail::create_parasail },
    PresetEntry { descriptor: &perfxcloud::DESCRIPTOR, create: perfxcloud::create_perfxcloud },
    PresetEntry { descriptor: &perplexity::DESCRIPTOR, create: perplexity::create_perplexity },
    PresetEntry { descriptor: &perplexity_agent::DESCRIPTOR, create: perplexity_agent::create_perplexity_agent },
    PresetEntry { descriptor: &petals::DESCRIPTOR, create: petals::create_petals },
    PresetEntry { descriptor: &pinstripes::DESCRIPTOR, create: pinstripes::create_pinstripes },
    PresetEntry { descriptor: &pioneer::DESCRIPTOR, create: pioneer::create_pioneer },
    PresetEntry { descriptor: &poe::DESCRIPTOR, create: poe::create_poe },
    PresetEntry { descriptor: &poolside::DESCRIPTOR, create: poolside::create_poolside },
    PresetEntry { descriptor: &portkey::DESCRIPTOR, create: portkey::create_portkey },
    PresetEntry { descriptor: &ppinfra::DESCRIPTOR, create: ppinfra::create_ppinfra },
    PresetEntry { descriptor: &predibase::DESCRIPTOR, create: predibase::create_predibase },
    PresetEntry { descriptor: &privatemode_ai::DESCRIPTOR, create: privatemode_ai::create_privatemode_ai },
    PresetEntry { descriptor: &publicai::DESCRIPTOR, create: publicai::create_publicai },
];

/// The `parasail` preset (Parasail).
pub mod parasail {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "parasail",
        display: "Parasail",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.parasail.io/v1",
        env_var: "PARASAIL_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `parasail` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_parasail(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `parasail` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn parasail() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_parasail(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use parasail::{create_parasail, parasail};

/// The `perfxcloud` preset (PerfXCloud).
pub mod perfxcloud {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "perfxcloud",
        display: "PerfXCloud",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.perfxcloud.com/v1",
        env_var: "PERFXCLOUD_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `perfxcloud` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_perfxcloud(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `perfxcloud` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn perfxcloud() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_perfxcloud(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use perfxcloud::{create_perfxcloud, perfxcloud};

/// The `perplexity` preset (Perplexity).
pub mod perplexity {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "perplexity",
        display: "Perplexity",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.perplexity.ai",
        env_var: "PERPLEXITY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: Some("max_tokens"),
        params: &[],
    };

    /// Create the `perplexity` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_perplexity(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `perplexity` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn perplexity() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_perplexity(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use perplexity::{create_perplexity, perplexity};

/// The `perplexity_agent` preset (Perplexity Agent).
pub mod perplexity_agent {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "perplexity_agent",
        display: "Perplexity Agent",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.perplexity.ai/v1",
        env_var: "PERPLEXITY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `perplexity_agent` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_perplexity_agent(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `perplexity_agent` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn perplexity_agent() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_perplexity_agent(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use perplexity_agent::{create_perplexity_agent, perplexity_agent};

/// The `petals` preset (Petals).
pub mod petals {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "petals",
        display: "Petals",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.petals.dev/v1",
        env_var: "PETALS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `petals` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_petals(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `petals` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn petals() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_petals(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use petals::{create_petals, petals};

/// The `pinstripes` preset (Pinstripes).
pub mod pinstripes {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "pinstripes",
        display: "Pinstripes",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.pinstripes.io/v1",
        env_var: "PINSTRIPES_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `pinstripes` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_pinstripes(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `pinstripes` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn pinstripes() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_pinstripes(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use pinstripes::{create_pinstripes, pinstripes};

/// The `pioneer` preset (Pioneer).
pub mod pioneer {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "pioneer",
        display: "Pioneer",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.pioneer.ai/v1",
        env_var: "PIONEER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `pioneer` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_pioneer(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `pioneer` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn pioneer() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_pioneer(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use pioneer::{create_pioneer, pioneer};

/// The `poe` preset (Poe).
pub mod poe {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "poe",
        display: "Poe",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.poe.com/v1",
        env_var: "POE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `poe` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_poe(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `poe` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn poe() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_poe(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use poe::{create_poe, poe};

/// The `poolside` preset (Poolside).
pub mod poolside {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "poolside",
        display: "Poolside",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://inference.poolside.ai/v1",
        env_var: "POOLSIDE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `poolside` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_poolside(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `poolside` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn poolside() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_poolside(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use poolside::{create_poolside, poolside};

/// The `portkey` preset (Portkey Gateway).
pub mod portkey {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "portkey",
        display: "Portkey Gateway",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.portkey.ai/v1",
        env_var: "PORTKEY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `portkey` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_portkey(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `portkey` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn portkey() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_portkey(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use portkey::{create_portkey, portkey};

/// The `ppinfra` preset (PPInfra（PPIO 派欧云）).
pub mod ppinfra {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "ppinfra",
        display: "PPInfra（PPIO 派欧云）",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.ppio.com/openai",
        env_var: "PPIO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `ppinfra` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_ppinfra(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `ppinfra` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn ppinfra() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_ppinfra(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use ppinfra::{create_ppinfra, ppinfra};

/// The `predibase` preset (Predibase).
pub mod predibase {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "predibase",
        display: "Predibase",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://serving.app.predibase.com/v1",
        env_var: "PREDIBASE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `predibase` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_predibase(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `predibase` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn predibase() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_predibase(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use predibase::{create_predibase, predibase};

/// The `privatemode_ai` preset (Privatemode AI).
pub mod privatemode_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "privatemode_ai",
        display: "Privatemode AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://localhost:8080/v1",
        env_var: "PRIVATEMODE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `privatemode_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_privatemode_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `privatemode_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn privatemode_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_privatemode_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use privatemode_ai::{create_privatemode_ai, privatemode_ai};

/// The `publicai` preset (Publicai).
pub mod publicai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "publicai",
        display: "Publicai",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://platform.publicai.co/v1",
        env_var: "PUBLICAI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: Some("max_tokens"),
        params: &[],
    };

    /// Create the `publicai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_publicai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `publicai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn publicai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_publicai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use publicai::{create_publicai, publicai};
