// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_S: &[PresetEntry] = &[
    PresetEntry { descriptor: &sakana::DESCRIPTOR, create: sakana::create_sakana },
    PresetEntry { descriptor: &sambanova::DESCRIPTOR, create: sambanova::create_sambanova },
    PresetEntry { descriptor: &sarvam::DESCRIPTOR, create: sarvam::create_sarvam },
    PresetEntry { descriptor: &scaleway::DESCRIPTOR, create: scaleway::create_scaleway },
    PresetEntry { descriptor: &scx_ai::DESCRIPTOR, create: scx_ai::create_scx_ai },
    PresetEntry { descriptor: &sglang::DESCRIPTOR, create: sglang::create_sglang },
    PresetEntry { descriptor: &siliconflow::DESCRIPTOR, create: siliconflow::create_siliconflow },
    PresetEntry { descriptor: &snowflake::DESCRIPTOR, create: snowflake::create_snowflake },
    PresetEntry { descriptor: &snowflake_cortex::DESCRIPTOR, create: snowflake_cortex::create_snowflake_cortex },
    PresetEntry { descriptor: &stackit::DESCRIPTOR, create: stackit::create_stackit },
    PresetEntry { descriptor: &stepfun::DESCRIPTOR, create: stepfun::create_stepfun },
    PresetEntry { descriptor: &stepfun_ai_step_plan::DESCRIPTOR, create: stepfun_ai_step_plan::create_stepfun_ai_step_plan },
    PresetEntry { descriptor: &stepfun_step_plan::DESCRIPTOR, create: stepfun_step_plan::create_stepfun_step_plan },
    PresetEntry { descriptor: &subconscious::DESCRIPTOR, create: subconscious::create_subconscious },
    PresetEntry { descriptor: &submodel::DESCRIPTOR, create: submodel::create_submodel },
    PresetEntry { descriptor: &synthetic::DESCRIPTOR, create: synthetic::create_synthetic },
];

/// The `sakana` preset (Sakana AI).
pub mod sakana {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "sakana",
        display: "Sakana AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.sakana.ai/v1",
        env_var: "SAKANA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `sakana` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_sakana(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `sakana` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn sakana() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_sakana(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use sakana::{create_sakana, sakana};

/// The `sambanova` preset (SambaNova).
pub mod sambanova {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "sambanova",
        display: "SambaNova",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.sambanova.ai/v1",
        env_var: "SAMBANOVA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `sambanova` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_sambanova(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `sambanova` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn sambanova() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_sambanova(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use sambanova::{create_sambanova, sambanova};

/// The `sarvam` preset (Sarvam AI).
pub mod sarvam {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "sarvam",
        display: "Sarvam AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.sarvam.ai/v1",
        env_var: "SARVAM_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: Some("max_tokens"),
        params: &[],
    };

    /// Create the `sarvam` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_sarvam(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `sarvam` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn sarvam() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_sarvam(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use sarvam::{create_sarvam, sarvam};

/// The `scaleway` preset (Scaleway AI).
pub mod scaleway {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "scaleway",
        display: "Scaleway AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.scaleway.ai/v1",
        env_var: "SCALEWAY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `scaleway` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_scaleway(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `scaleway` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn scaleway() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_scaleway(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use scaleway::{create_scaleway, scaleway};

/// The `scx_ai` preset (SCX AI).
pub mod scx_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "scx_ai",
        display: "SCX AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.scx.ai/v1",
        env_var: "SCX_AI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `scx_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_scx_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `scx_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn scx_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_scx_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use scx_ai::{create_scx_ai, scx_ai};

/// The `sglang` preset (SGLang).
pub mod sglang {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "sglang",
        display: "SGLang",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:30000/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("SGLANG_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `sglang` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_sglang(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `sglang` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn sglang() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_sglang(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use sglang::{create_sglang, sglang};

/// The `siliconflow` preset (SiliconFlow).
pub mod siliconflow {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "siliconflow",
        display: "SiliconFlow",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.siliconflow.cn/v1",
        env_var: "SILICONFLOW_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: Some("max_tokens"),
        params: &[],
    };

    /// Create the `siliconflow` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_siliconflow(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `siliconflow` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn siliconflow() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_siliconflow(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use siliconflow::{create_siliconflow, siliconflow};

/// The `snowflake` preset (Snowflake).
pub mod snowflake {
    use crate::preset::{AuthMode, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "snowflake",
        display: "Snowflake",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{account_identifier}.snowflakecomputing.com/api/v2/cortex/v1",
        env_var: "SNOWFLAKE_PAT",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "account_identifier", env: &[], default: None, derive: None },
        ],
    };

    /// Create the `snowflake` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_snowflake(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `snowflake` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn snowflake() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_snowflake(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use snowflake::{create_snowflake, snowflake};

/// The `snowflake_cortex` preset (Snowflake Cortex).
pub mod snowflake_cortex {
    use crate::preset::{AuthMode, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "snowflake_cortex",
        display: "Snowflake Cortex",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{account_identifier}.snowflakecomputing.com/api/v2/cortex/v1",
        env_var: "SNOWFLAKE_CORTEX_PAT",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "account_identifier", env: &[], default: None, derive: None },
        ],
    };

    /// Create the `snowflake_cortex` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_snowflake_cortex(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `snowflake_cortex` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn snowflake_cortex() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_snowflake_cortex(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use snowflake_cortex::{create_snowflake_cortex, snowflake_cortex};

/// The `stackit` preset (STACKIT).
pub mod stackit {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "stackit",
        display: "STACKIT",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
        env_var: "STACKIT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `stackit` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_stackit(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `stackit` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn stackit() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_stackit(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use stackit::{create_stackit, stackit};

/// The `stepfun` preset (StepFun (阶跃星辰)).
pub mod stepfun {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "stepfun",
        display: "StepFun (阶跃星辰)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.stepfun.com/v1",
        env_var: "STEPFUN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: Some("max_tokens"),
        params: &[],
    };

    /// Create the `stepfun` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_stepfun(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `stepfun` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn stepfun() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_stepfun(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use stepfun::{create_stepfun, stepfun};

/// The `stepfun_ai_step_plan` preset (StepFun Step Plan (Global)).
pub mod stepfun_ai_step_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "stepfun_ai_step_plan",
        display: "StepFun Step Plan (Global)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.stepfun.ai/step_plan/v1",
        env_var: "STEPFUN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `stepfun_ai_step_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_stepfun_ai_step_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `stepfun_ai_step_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn stepfun_ai_step_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_stepfun_ai_step_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use stepfun_ai_step_plan::{create_stepfun_ai_step_plan, stepfun_ai_step_plan};

/// The `stepfun_step_plan` preset (StepFun Step Plan (China)).
pub mod stepfun_step_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "stepfun_step_plan",
        display: "StepFun Step Plan (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.stepfun.com/step_plan/v1",
        env_var: "STEPFUN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `stepfun_step_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_stepfun_step_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `stepfun_step_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn stepfun_step_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_stepfun_step_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use stepfun_step_plan::{create_stepfun_step_plan, stepfun_step_plan};

/// The `subconscious` preset (Subconscious).
pub mod subconscious {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "subconscious",
        display: "Subconscious",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.subconscious.dev/v1",
        env_var: "SUBCONSCIOUS_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `subconscious` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_subconscious(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `subconscious` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn subconscious() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_subconscious(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use subconscious::{create_subconscious, subconscious};

/// The `submodel` preset (SubModel).
pub mod submodel {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "submodel",
        display: "SubModel",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.submodel.com/v1",
        env_var: "SUBMODEL_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `submodel` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_submodel(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `submodel` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn submodel() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_submodel(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use submodel::{create_submodel, submodel};

/// The `synthetic` preset (Synthetic).
pub mod synthetic {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "synthetic",
        display: "Synthetic",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.synthetic.new/openai/v1",
        env_var: "SYNTHETIC_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `synthetic` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_synthetic(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `synthetic` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn synthetic() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_synthetic(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use synthetic::{create_synthetic, synthetic};
