// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_T: &[PresetEntry] = &[
    PresetEntry { descriptor: &tencent::DESCRIPTOR, create: tencent::create_tencent },
    PresetEntry { descriptor: &tencent_coding_plan::DESCRIPTOR, create: tencent_coding_plan::create_tencent_coding_plan },
    PresetEntry { descriptor: &tencent_token_plan::DESCRIPTOR, create: tencent_token_plan::create_tencent_token_plan },
    PresetEntry { descriptor: &tencent_token_plan_enterprise_auto::DESCRIPTOR, create: tencent_token_plan_enterprise_auto::create_tencent_token_plan_enterprise_auto },
    PresetEntry { descriptor: &tencent_token_plan_enterprise_pro::DESCRIPTOR, create: tencent_token_plan_enterprise_pro::create_tencent_token_plan_enterprise_pro },
    PresetEntry { descriptor: &tencent_token_plan_general_personal::DESCRIPTOR, create: tencent_token_plan_general_personal::create_tencent_token_plan_general_personal },
    PresetEntry { descriptor: &tencent_token_plan_hy_personal::DESCRIPTOR, create: tencent_token_plan_hy_personal::create_tencent_token_plan_hy_personal },
    PresetEntry { descriptor: &tencent_tokenhub::DESCRIPTOR, create: tencent_tokenhub::create_tencent_tokenhub },
    PresetEntry { descriptor: &tensormesh::DESCRIPTOR, create: tensormesh::create_tensormesh },
    PresetEntry { descriptor: &the_grid_ai::DESCRIPTOR, create: the_grid_ai::create_the_grid_ai },
    PresetEntry { descriptor: &thinkingmachines::DESCRIPTOR, create: thinkingmachines::create_thinkingmachines },
    PresetEntry { descriptor: &tinfoil::DESCRIPTOR, create: tinfoil::create_tinfoil },
    PresetEntry { descriptor: &togetherai::DESCRIPTOR, create: togetherai::create_togetherai },
    PresetEntry { descriptor: &tokenflux::DESCRIPTOR, create: tokenflux::create_tokenflux },
    PresetEntry { descriptor: &tokenpony::DESCRIPTOR, create: tokenpony::create_tokenpony },
    PresetEntry { descriptor: &trustedrouter::DESCRIPTOR, create: trustedrouter::create_trustedrouter },
    PresetEntry { descriptor: &tundra::DESCRIPTOR, create: tundra::create_tundra },
];

/// The `tencent` preset (Tencent (混元/Hunyuan)).
pub mod tencent {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent",
        display: "Tencent (混元/Hunyuan)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.hunyuan.cloud.tencent.com/v1",
        env_var: "TENCENT_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent::{create_tencent, tencent};

/// The `tencent_coding_plan` preset (Tencent Coding Plan (China)).
pub mod tencent_coding_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_coding_plan",
        display: "Tencent Coding Plan (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lkeap.cloud.tencent.com/coding/v3",
        env_var: "TENCENT_CODING_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_coding_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_coding_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_coding_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_coding_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_coding_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_coding_plan::{create_tencent_coding_plan, tencent_coding_plan};

/// The `tencent_token_plan` preset (Tencent Token Plan).
pub mod tencent_token_plan {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_token_plan",
        display: "Tencent Token Plan",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        env_var: "TENCENT_TOKEN_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_token_plan` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_token_plan(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_token_plan` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_token_plan() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_token_plan(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_token_plan::{create_tencent_token_plan, tencent_token_plan};

/// The `tencent_token_plan_enterprise_auto` preset (腾讯云 Token Plan / Token Plan 企业版轻享套餐).
pub mod tencent_token_plan_enterprise_auto {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_token_plan_enterprise_auto",
        display: "腾讯云 Token Plan / Token Plan 企业版轻享套餐",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://tokenhub.tencentmaas.com/plan/v3",
        env_var: "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_token_plan_enterprise_auto` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_token_plan_enterprise_auto(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_token_plan_enterprise_auto` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_token_plan_enterprise_auto() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_token_plan_enterprise_auto(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_token_plan_enterprise_auto::{create_tencent_token_plan_enterprise_auto, tencent_token_plan_enterprise_auto};

/// The `tencent_token_plan_enterprise_pro` preset (腾讯云 Token Plan / Token Plan 企业版专业套餐).
pub mod tencent_token_plan_enterprise_pro {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_token_plan_enterprise_pro",
        display: "腾讯云 Token Plan / Token Plan 企业版专业套餐",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://tokenhub.tencentmaas.com/plan/v3",
        env_var: "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_token_plan_enterprise_pro` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_token_plan_enterprise_pro(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_token_plan_enterprise_pro` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_token_plan_enterprise_pro() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_token_plan_enterprise_pro(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_token_plan_enterprise_pro::{create_tencent_token_plan_enterprise_pro, tencent_token_plan_enterprise_pro};

/// The `tencent_token_plan_general_personal` preset (腾讯云 Token Plan / 通用 Token Plan（个人版）).
pub mod tencent_token_plan_general_personal {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_token_plan_general_personal",
        display: "腾讯云 Token Plan / 通用 Token Plan（个人版）",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        env_var: "TENCENT_TOKEN_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_token_plan_general_personal` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_token_plan_general_personal(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_token_plan_general_personal` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_token_plan_general_personal() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_token_plan_general_personal(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_token_plan_general_personal::{create_tencent_token_plan_general_personal, tencent_token_plan_general_personal};

/// The `tencent_token_plan_hy_personal` preset (腾讯云 Token Plan / Hy Token Plan（个人版）).
pub mod tencent_token_plan_hy_personal {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_token_plan_hy_personal",
        display: "腾讯云 Token Plan / Hy Token Plan（个人版）",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        env_var: "TENCENT_TOKEN_PLAN_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_token_plan_hy_personal` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_token_plan_hy_personal(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_token_plan_hy_personal` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_token_plan_hy_personal() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_token_plan_hy_personal(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_token_plan_hy_personal::{create_tencent_token_plan_hy_personal, tencent_token_plan_hy_personal};

/// The `tencent_tokenhub` preset (Tencent TokenHub).
pub mod tencent_tokenhub {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tencent_tokenhub",
        display: "Tencent TokenHub",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://tokenhub.tencentmaas.com/v1",
        env_var: "TENCENT_TOKENHUB_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tencent_tokenhub` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tencent_tokenhub(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tencent_tokenhub` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tencent_tokenhub() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tencent_tokenhub(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tencent_tokenhub::{create_tencent_tokenhub, tencent_tokenhub};

/// The `tensormesh` preset (Tensormesh).
pub mod tensormesh {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tensormesh",
        display: "Tensormesh",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://serverless.tensormesh.ai",
        env_var: "YOUR_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tensormesh` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tensormesh(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tensormesh` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tensormesh() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tensormesh(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tensormesh::{create_tensormesh, tensormesh};

/// The `the_grid_ai` preset (The Grid AI).
pub mod the_grid_ai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "the_grid_ai",
        display: "The Grid AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.thegrid.ai/v1",
        env_var: "THEGRIDAI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `the_grid_ai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_the_grid_ai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `the_grid_ai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn the_grid_ai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_the_grid_ai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use the_grid_ai::{create_the_grid_ai, the_grid_ai};

/// The `thinkingmachines` preset (Thinking Machines).
pub mod thinkingmachines {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "thinkingmachines",
        display: "Thinking Machines",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://tinker.thinkingmachines.dev/services/tinker-prod/oai/api/v1",
        env_var: "TINKER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `thinkingmachines` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_thinkingmachines(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `thinkingmachines` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn thinkingmachines() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_thinkingmachines(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use thinkingmachines::{create_thinkingmachines, thinkingmachines};

/// The `tinfoil` preset (Tinfoil).
pub mod tinfoil {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tinfoil",
        display: "Tinfoil",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://inference.tinfoil.sh/v1",
        env_var: "TINFOIL_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tinfoil` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tinfoil(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tinfoil` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tinfoil() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tinfoil(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tinfoil::{create_tinfoil, tinfoil};

/// The `togetherai` preset (Together AI).
pub mod togetherai {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "togetherai",
        display: "Together AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.together.xyz/v1",
        env_var: "TOGETHER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `togetherai` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_togetherai(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `togetherai` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn togetherai() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_togetherai(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use togetherai::{create_togetherai, togetherai};

/// The `tokenflux` preset (Tokenflux).
pub mod tokenflux {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tokenflux",
        display: "Tokenflux",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://tokenflux.ai/v1",
        env_var: "TOKENFLUX_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tokenflux` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tokenflux(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tokenflux` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tokenflux() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tokenflux(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tokenflux::{create_tokenflux, tokenflux};

/// The `tokenpony` preset (TokenPony).
pub mod tokenpony {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tokenpony",
        display: "TokenPony",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.tokenpony.com/v1",
        env_var: "TOKENPONY_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tokenpony` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tokenpony(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tokenpony` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tokenpony() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tokenpony(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tokenpony::{create_tokenpony, tokenpony};

/// The `trustedrouter` preset (TrustedRouter).
pub mod trustedrouter {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "trustedrouter",
        display: "TrustedRouter",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.trustedrouter.com/v1",
        env_var: "TRUSTEDROUTER_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `trustedrouter` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_trustedrouter(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `trustedrouter` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn trustedrouter() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_trustedrouter(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use trustedrouter::{create_trustedrouter, trustedrouter};

/// The `tundra` preset (Tundra).
pub mod tundra {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "tundra",
        display: "Tundra",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.tundra.ai/v1",
        env_var: "TUNDRA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `tundra` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_tundra(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `tundra` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn tundra() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_tundra(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use tundra::{create_tundra, tundra};
