// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_V: &[PresetEntry] = &[
    PresetEntry { descriptor: &v0::DESCRIPTOR, create: v0::create_v0 },
    PresetEntry { descriptor: &venice::DESCRIPTOR, create: venice::create_venice },
    PresetEntry { descriptor: &vercel::DESCRIPTOR, create: vercel::create_vercel },
    PresetEntry { descriptor: &vertex_ai_ai21_models::DESCRIPTOR, create: vertex_ai_ai21_models::create_vertex_ai_ai21_models },
    PresetEntry { descriptor: &vertex_ai_anthropic_models::DESCRIPTOR, create: vertex_ai_anthropic_models::create_vertex_ai_anthropic_models },
    PresetEntry { descriptor: &vertex_ai_deepseek_models::DESCRIPTOR, create: vertex_ai_deepseek_models::create_vertex_ai_deepseek_models },
    PresetEntry { descriptor: &vertex_ai_llama_models::DESCRIPTOR, create: vertex_ai_llama_models::create_vertex_ai_llama_models },
    PresetEntry { descriptor: &vertex_ai_minimax_models::DESCRIPTOR, create: vertex_ai_minimax_models::create_vertex_ai_minimax_models },
    PresetEntry { descriptor: &vertex_ai_mistral_models::DESCRIPTOR, create: vertex_ai_mistral_models::create_vertex_ai_mistral_models },
    PresetEntry { descriptor: &vertex_ai_moonshot_models::DESCRIPTOR, create: vertex_ai_moonshot_models::create_vertex_ai_moonshot_models },
    PresetEntry { descriptor: &vertex_ai_openai_models::DESCRIPTOR, create: vertex_ai_openai_models::create_vertex_ai_openai_models },
    PresetEntry { descriptor: &vertex_ai_qwen_models::DESCRIPTOR, create: vertex_ai_qwen_models::create_vertex_ai_qwen_models },
    PresetEntry { descriptor: &vertex_ai_zai_models::DESCRIPTOR, create: vertex_ai_zai_models::create_vertex_ai_zai_models },
    PresetEntry { descriptor: &vivgrid::DESCRIPTOR, create: vivgrid::create_vivgrid },
    PresetEntry { descriptor: &vllm::DESCRIPTOR, create: vllm::create_vllm },
    PresetEntry { descriptor: &volc_engine::DESCRIPTOR, create: volc_engine::create_volc_engine },
    PresetEntry { descriptor: &vultr::DESCRIPTOR, create: vultr::create_vultr },
];

/// The `v0` preset (v0 (Vercel)).
pub mod v0 {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "v0",
        display: "v0 (Vercel)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.v0.dev/v1",
        env_var: "V0_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `v0` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_v0(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `v0` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn v0() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_v0(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use v0::{create_v0, v0};

/// The `venice` preset (Venice).
pub mod venice {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "venice",
        display: "Venice",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.venice.ai/api/v1",
        env_var: "VENICE_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `venice` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_venice(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `venice` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn venice() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_venice(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use venice::{create_venice, venice};

/// The `vercel` preset (Vercel).
pub mod vercel {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vercel",
        display: "Vercel",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.v0.dev/v1",
        env_var: "VERCEL_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `vercel` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vercel(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vercel` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vercel() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vercel(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vercel::{create_vercel, vercel};

/// The `vertex_ai_ai21_models` preset (AI21 models on Vertex AI).
pub mod vertex_ai_ai21_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_ai21_models",
        display: "AI21 models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_ai21_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_ai21_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_ai21_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_ai21_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_ai21_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_ai21_models::{create_vertex_ai_ai21_models, vertex_ai_ai21_models};

/// The `vertex_ai_anthropic_models` preset (Anthropic Claude models on Vertex AI).
pub mod vertex_ai_anthropic_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_anthropic_models",
        display: "Anthropic Claude models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_anthropic_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_anthropic_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_anthropic_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_anthropic_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_anthropic_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_anthropic_models::{create_vertex_ai_anthropic_models, vertex_ai_anthropic_models};

/// The `vertex_ai_deepseek_models` preset (DeepSeek models on Vertex AI).
pub mod vertex_ai_deepseek_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_deepseek_models",
        display: "DeepSeek models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_deepseek_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_deepseek_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_deepseek_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_deepseek_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_deepseek_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_deepseek_models::{create_vertex_ai_deepseek_models, vertex_ai_deepseek_models};

/// The `vertex_ai_llama_models` preset (Meta Llama models on Vertex AI).
pub mod vertex_ai_llama_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_llama_models",
        display: "Meta Llama models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_llama_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_llama_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_llama_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_llama_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_llama_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_llama_models::{create_vertex_ai_llama_models, vertex_ai_llama_models};

/// The `vertex_ai_minimax_models` preset (MiniMax models on Vertex AI).
pub mod vertex_ai_minimax_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_minimax_models",
        display: "MiniMax models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_minimax_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_minimax_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_minimax_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_minimax_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_minimax_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_minimax_models::{create_vertex_ai_minimax_models, vertex_ai_minimax_models};

/// The `vertex_ai_mistral_models` preset (Mistral models on Vertex AI).
pub mod vertex_ai_mistral_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_mistral_models",
        display: "Mistral models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_mistral_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_mistral_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_mistral_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_mistral_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_mistral_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_mistral_models::{create_vertex_ai_mistral_models, vertex_ai_mistral_models};

/// The `vertex_ai_moonshot_models` preset (Moonshot AI models on Vertex AI).
pub mod vertex_ai_moonshot_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_moonshot_models",
        display: "Moonshot AI models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_moonshot_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_moonshot_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_moonshot_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_moonshot_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_moonshot_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_moonshot_models::{create_vertex_ai_moonshot_models, vertex_ai_moonshot_models};

/// The `vertex_ai_openai_models` preset (OpenAI models on Vertex AI).
pub mod vertex_ai_openai_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_openai_models",
        display: "OpenAI models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_openai_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_openai_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_openai_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_openai_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_openai_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_openai_models::{create_vertex_ai_openai_models, vertex_ai_openai_models};

/// The `vertex_ai_qwen_models` preset (Qwen models on Vertex AI).
pub mod vertex_ai_qwen_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_qwen_models",
        display: "Qwen models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_qwen_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_qwen_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_qwen_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_qwen_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_qwen_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_qwen_models::{create_vertex_ai_qwen_models, vertex_ai_qwen_models};

/// The `vertex_ai_zai_models` preset (Z.AI models on Vertex AI).
pub mod vertex_ai_zai_models {
    use crate::preset::{AuthMode, DeriveSpec, ParamSpec, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vertex_ai_zai_models",
        display: "Z.AI models on Vertex AI",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://{host}/v1/projects/{project}/locations/{location}/endpoints/openapi",
        env_var: "GOOGLE_VERTEX_ACCESS_TOKEN",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[
            ParamSpec { name: "project", env: &["GOOGLE_VERTEX_PROJECT"], default: None, derive: None },
            ParamSpec { name: "location", env: &["GOOGLE_VERTEX_LOCATION"], default: Some("global"), derive: None },
            ParamSpec { name: "host", env: &[], default: None, derive: Some(DeriveSpec { from: "location", map: &[("global", "aiplatform.googleapis.com"), ("eu", "aiplatform.eu.rep.googleapis.com"), ("us", "aiplatform.us.rep.googleapis.com")], otherwise: "{location}-aiplatform.googleapis.com" }) },
        ],
    };

    /// Create the `vertex_ai_zai_models` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vertex_ai_zai_models(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vertex_ai_zai_models` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vertex_ai_zai_models() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vertex_ai_zai_models(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vertex_ai_zai_models::{create_vertex_ai_zai_models, vertex_ai_zai_models};

/// The `vivgrid` preset (Vivgrid).
pub mod vivgrid {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vivgrid",
        display: "Vivgrid",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.vivgrid.com/v1",
        env_var: "VIVGRID_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `vivgrid` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vivgrid(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vivgrid` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vivgrid() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vivgrid(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vivgrid::{create_vivgrid, vivgrid};

/// The `vllm` preset (vLLM).
pub mod vllm {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vllm",
        display: "vLLM",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:8000/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("VLLM_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `vllm` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vllm(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vllm` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vllm() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vllm(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vllm::{create_vllm, vllm};

/// The `volc_engine` preset (VolcEngine).
pub mod volc_engine {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "volc_engine",
        display: "VolcEngine",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        env_var: "ARK_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `volc_engine` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_volc_engine(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `volc_engine` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn volc_engine() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_volc_engine(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use volc_engine::{create_volc_engine, volc_engine};

/// The `vultr` preset (Vultr).
pub mod vultr {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "vultr",
        display: "Vultr",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://api.vultrinference.com/v1",
        env_var: "VULTR_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `vultr` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_vultr(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `vultr` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn vultr() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_vultr(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use vultr::{create_vultr, vultr};
