// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.

use crate::preset::PresetEntry;

pub(super) static ENTRIES_X: &[PresetEntry] = &[
    PresetEntry { descriptor: &xiaomi_token_plan_ams::DESCRIPTOR, create: xiaomi_token_plan_ams::create_xiaomi_token_plan_ams },
    PresetEntry { descriptor: &xiaomi_token_plan_cn::DESCRIPTOR, create: xiaomi_token_plan_cn::create_xiaomi_token_plan_cn },
    PresetEntry { descriptor: &xiaomi_token_plan_sgp::DESCRIPTOR, create: xiaomi_token_plan_sgp::create_xiaomi_token_plan_sgp },
    PresetEntry { descriptor: &xiaomimimo::DESCRIPTOR, create: xiaomimimo::create_xiaomimimo },
    PresetEntry { descriptor: &xinference::DESCRIPTOR, create: xinference::create_xinference },
    PresetEntry { descriptor: &xpersona::DESCRIPTOR, create: xpersona::create_xpersona },
    PresetEntry { descriptor: &xunfei::DESCRIPTOR, create: xunfei::create_xunfei },
];

/// The `xiaomi_token_plan_ams` preset (Xiaomi Token Plan (Europe)).
pub mod xiaomi_token_plan_ams {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xiaomi_token_plan_ams",
        display: "Xiaomi Token Plan (Europe)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://token-plan-ams.xiaomimimo.com/v1",
        env_var: "MIMO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xiaomi_token_plan_ams` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xiaomi_token_plan_ams(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xiaomi_token_plan_ams` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xiaomi_token_plan_ams() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xiaomi_token_plan_ams(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xiaomi_token_plan_ams::{create_xiaomi_token_plan_ams, xiaomi_token_plan_ams};

/// The `xiaomi_token_plan_cn` preset (Xiaomi Token Plan (China)).
pub mod xiaomi_token_plan_cn {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xiaomi_token_plan_cn",
        display: "Xiaomi Token Plan (China)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://token-plan-cn.xiaomimimo.com/v1",
        env_var: "MIMO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xiaomi_token_plan_cn` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xiaomi_token_plan_cn(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xiaomi_token_plan_cn` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xiaomi_token_plan_cn() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xiaomi_token_plan_cn(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xiaomi_token_plan_cn::{create_xiaomi_token_plan_cn, xiaomi_token_plan_cn};

/// The `xiaomi_token_plan_sgp` preset (Xiaomi Token Plan (Singapore)).
pub mod xiaomi_token_plan_sgp {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xiaomi_token_plan_sgp",
        display: "Xiaomi Token Plan (Singapore)",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://token-plan-sgp.xiaomimimo.com/v1",
        env_var: "MIMO_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xiaomi_token_plan_sgp` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xiaomi_token_plan_sgp(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xiaomi_token_plan_sgp` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xiaomi_token_plan_sgp() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xiaomi_token_plan_sgp(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xiaomi_token_plan_sgp::{create_xiaomi_token_plan_sgp, xiaomi_token_plan_sgp};

/// The `xiaomimimo` preset (Xiaomi MiMo).
pub mod xiaomimimo {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xiaomimimo",
        display: "Xiaomi MiMo",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://mimo.xiaomi.com/v1",
        env_var: "XIAOMI_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xiaomimimo` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xiaomimimo(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xiaomimimo` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xiaomimimo() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xiaomimimo(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xiaomimimo::{create_xiaomimimo, xiaomimimo};

/// The `xinference` preset (Xinference).
pub mod xinference {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xinference",
        display: "Xinference",
        family: PresetFamily::OpenAICompatible,
        base_url: "http://127.0.0.1:9997/v1",
        env_var: "",
        auth: AuthMode::None,
        base_url_env: Some("XINFERENCE_BASE_URL"),
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xinference` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xinference(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xinference` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xinference() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xinference(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xinference::{create_xinference, xinference};

/// The `xpersona` preset (Xpersona).
pub mod xpersona {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xpersona",
        display: "Xpersona",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://www.xpersona.co/v1",
        env_var: "XPERSONA_API_KEY",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xpersona` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xpersona(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xpersona` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xpersona() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xpersona(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xpersona::{create_xpersona, xpersona};

/// The `xunfei` preset (Xunfei).
pub mod xunfei {
    use crate::preset::{AuthMode, PresetDescriptor, PresetFamily, PresetProvider, PresetSettings};
    use aimux_core::AiMuxError;
    use std::sync::OnceLock;

    /// The registry row.
    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {
        name: "xunfei",
        display: "Xunfei",
        family: PresetFamily::OpenAICompatible,
        base_url: "https://spark-api-open.xf-yun.com/v1",
        env_var: "XUNFEI_API_PASSWORD",
        auth: AuthMode::ApiKey,
        base_url_env: None,
        max_tokens_key: None,
        params: &[],
    };

    /// Create the `xunfei` preset from explicit settings. Reads nothing from the
    /// environment: the key and any environment-sourced URL are evaluated per request.
    ///
    /// # Errors
    ///
    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a
    /// `params` value that is not a plain segment.
    pub fn create_xunfei(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {
        PresetProvider::create(&DESCRIPTOR, settings)
    }

    /// The default `xunfei` instance, created on first use. Creating it reads nothing
    /// from the environment and cannot fail.
    #[must_use]
    pub fn xunfei() -> &'static PresetProvider {
        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();
        DEFAULT.get_or_init(|| {
            create_xunfei(PresetSettings::default())
                .expect("default preset settings are always valid")
        })
    }
}
pub use xunfei::{create_xunfei, xunfei};
