// shim.c - generated: references every aimux-ffi C symbol so the
// linker keeps the static archive objects (Dart resolves them via
// DynamicLibrary.process(); nothing else references them).
//
// `used` keeps the array in the object file; aimux.swift additionally
// references it so the linker pulls this object into the app binary.
#include "aimux_ffi.h"

__attribute__((used)) void *const aimux_ffi_all_symbols[] = {
    (void *)&aimux_anthropic_aws_new,
    (void *)&aimux_anthropic_aws_new_with_base,
    (void *)&aimux_anthropic_new,
    (void *)&aimux_anthropic_new_with_base,
    (void *)&aimux_azure_new,
    (void *)&aimux_azure_new_with_base,
    (void *)&aimux_bedrock_new,
    (void *)&aimux_bedrock_new_with_base,
    (void *)&aimux_codex_refresh,
    (void *)&aimux_cohere_embedding_new,
    (void *)&aimux_cohere_embedding_new_with_base,
    (void *)&aimux_cohere_new,
    (void *)&aimux_cohere_new_with_base,
    (void *)&aimux_cohere_reranking_new,
    (void *)&aimux_cohere_reranking_new_with_base,
    (void *)&aimux_drop_handle,
    (void *)&aimux_embed,
    (void *)&aimux_file_upload,
    (void *)&aimux_free_string,
    (void *)&aimux_generate_text,
    (void *)&aimux_google_embedding_new,
    (void *)&aimux_google_embedding_new_with_base,
    (void *)&aimux_google_image_new,
    (void *)&aimux_google_image_new_with_base,
    (void *)&aimux_google_video_new,
    (void *)&aimux_google_video_new_with_base,
    (void *)&aimux_image_generate,
    (void *)&aimux_init_logging,
    (void *)&aimux_last_error,
    (void *)&aimux_mistral_new,
    (void *)&aimux_mistral_new_with_base,
    (void *)&aimux_openai_embedding_new,
    (void *)&aimux_openai_embedding_new_with_base,
    (void *)&aimux_openai_files_new,
    (void *)&aimux_openai_files_new_with_base,
    (void *)&aimux_openai_image_new,
    (void *)&aimux_openai_image_new_with_base,
    (void *)&aimux_openai_new,
    (void *)&aimux_openai_new_with_base,
    (void *)&aimux_openai_speech_new,
    (void *)&aimux_openai_speech_new_with_base,
    (void *)&aimux_openai_transcription_new,
    (void *)&aimux_openai_transcription_new_with_base,
    (void *)&aimux_provider_from_env,
    (void *)&aimux_provider_new,
    (void *)&aimux_rerank,
    (void *)&aimux_search,
    (void *)&aimux_speech_generate,
    (void *)&aimux_stream_text,
    (void *)&aimux_tavily_search_new,
    (void *)&aimux_tavily_search_new_with_base,
    (void *)&aimux_transcription_generate,
    (void *)&aimux_vertex_new,
    (void *)&aimux_vertex_new_with_base,
    (void *)&aimux_video_generate,
    (void *)&aimux_xai_new,
    (void *)&aimux_xai_new_with_base,
};
