// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatCompletionMessage } from "./ChatCompletionMessage";
import type { JsonValue } from "./serde_json/JsonValue";

export type ChatCompletionChoice = { index: number, message: ChatCompletionMessage, finish_reason: string | null, logprobs: JsonValue | null, };
