// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatCompletionChunkToolCall } from "./ChatCompletionChunkToolCall";

export type ChatCompletionDelta = { role: string | null, content: string | null, reasoning_content: string | null, tool_calls: Array<ChatCompletionChunkToolCall> | null, };
