// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Debugging response info specific to embedding calls.
 */
export type EmbeddingResponse = { 
/**
 * Response headers.
 */
headers: { [key in string]: string } | null, 
/**
 * The response body (opaque JSON).
 */
body: JsonValue | null, };
