// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized-wire fingerprint stored in a `TraceRecord` (hex strings —
 * `u128` is not JSON-serializable).
 */
export type Fingerprint = { 
/**
 * 128-bit hash of the whole denoised body (hex).
 */
body_hash: string, len_bytes: bigint, block_size: bigint, 
/**
 * Block-hash chain (hex), one entry per block.
 */
block_hashes: Array<string>, 
/**
 * Token estimate — byte proxy `len_bytes / 4` when no tokenizer is
 * attached (RFC-0015 §4.1: W capped at one block in this mode).
 */
token_estimate: bigint, };
