// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified finish reason enum (aligned with V4 `LanguageModelV4FinishReason`).
 */
export type FinishReasonUnified = "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
