// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpRecord = { method: string, url: string, 
/**
 * 敏感头(authorization/cookie/含 api-key/key/x-amz-security-token 等)已脱敏为 "[REDACTED]"。
 */
headers: Array<[string, string]>, 
/**
 * 明文(脱敏后);None = 无 body。
 */
body: string | null, };
