// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFileData } from "./ImageFileData";

/**
 * An image file used for image editing or variation generation.
 *
 * Aligned with V4 `ImageModelV4File`.
 */
export type ImageFile = { "File": { 
/**
 * IANA media type, e.g. `"image/png"`.
 */
media_type: string, 
/**
 * File data as base64 string or binary bytes.
 */
data: ImageFileData, } } | { "Url": { 
/**
 * The URL of the image file.
 */
url: string, } };
