// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * ② 配置侧:provider 身份(请求回放重建用)。
 */
export type ProviderRecord = { 
/**
 * `model.provider()`,如 "openai"。
 */
provider: string, 
/**
 * `model.model_id()`,如 "gpt-4o"。
 */
model_id: string, 
/**
 * provider 的 base_url。
 */
base_url: string | null, 
/**
 * api_key 来源(不存明文):"env:OPENAI_API_KEY" / "explicit" / "none" / "unknown"。
 */
api_key_source: string, 
/**
 * OpenAICompatProfile(能力差异)。
 */
profile: JsonValue | null, 
/**
 * ProviderOptions(headers/org/project/...;已脱敏)。
 */
provider_options: JsonValue | null, };
