// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request-side cache hints (best-effort, e.g. Anthropic `cache_control`).
 */
export type RequestCacheHints = { 
/**
 * Whether any message requested `cache_control` (write) this call.
 */
requested_write: boolean, };
