// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Optional response information for a reranking call.
 */
export type RerankingResponse = { 
/**
 * ID for the generated response, if the provider sends one.
 */
id: string | null, 
/**
 * Timestamp for the start of the generated response (ISO 8601 string).
 */
timestamp: string | null, 
/**
 * The ID of the model that was used to generate the response.
 */
model_id: string | null, 
/**
 * Response headers.
 */
headers: { [key in string]: string } | null, 
/**
 * Response body (opaque JSON).
 */
body: JsonValue | null, };
