// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResponseRecord = { status: number, headers: Array<[string, string]>, 
/**
 * 非流式:完整 JSON;流式:原始 SSE 拼接文本(上限截断)。
 */
body: string | null, stream_chunks: number | null, 
/**
 * 首字节延迟(流式)。
 */
ttfb_ms?: number | null, };
