// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source / citation, extracted to the top level (M7).
 */
export type SourcePart = { id: string, source_type: string, url?: string | null, title?: string | null, };
