// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-call timeout configuration.
 *
 * Aligned with V4 `LanguageModelV4CallOptions.timeout`
 * (`TimeoutConfiguration`). All values are milliseconds; `None` disables the
 * corresponding limit. A `total` timeout also covers retry backoff and the
 * whole streamed response.
 */
export type TimeoutConfiguration = { 
/**
 * Overall timeout for the entire call (including retries and, for
 * streaming, the whole stream), in milliseconds.
 */
total_ms: number | null, 
/**
 * Timeout waiting for the first stream chunk (streaming only).
 */
first_chunk_ms: number | null, 
/**
 * Maximum idle time between consecutive stream chunks (streaming only).
 */
chunk_ms: number | null, };
