// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the model should choose tools.
 *
 * Wire format aligns with Vercel AI SDK `toolChoice`:
 * `"auto" | "none" | "required" | { "type": "tool", "toolName": "..." }`.
 * This is a mixed tagged/untagged shape (unit variants as bare strings,
 * `Tool` variant as a tagged object), so serde is implemented by hand.
 */
export type ToolChoice = "auto" | "none" | "required" | { type: "tool"; toolName: string };
