// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireMessage } from "./WireMessage";
import type { WireOptions } from "./WireOptions";

/**
 * One model call from the console (RFC-0029 §5.3).
 */
export type WireCallRequest = { 
/**
 * Registry name or native protocol name ("openai", "deepseek", …).
 */
provider: string, 
/**
 * Model id (free text, e.g. "gpt-4o").
 */
model: string, 
/**
 * API key: `None` (provider reads its registered env var), or
 * `Some("env:VAR")`. Plaintext keys are rejected (RFC-0029 §9).
 */
api_key?: string | null, 
/**
 * Base URL override (proxies / local endpoints).
 */
base_url?: string | null, 
/**
 * Stream the response as SSE (`StreamPart` events). Default true.
 */
stream: boolean, 
/**
 * Route through the loaded mock model (offline mode, RFC-0023 P3).
 */
mock: boolean, options: WireOptions, 
/**
 * Session grouping id (RFC-0024). The console reuses one id per agent run.
 */
session_id?: string | null, 
/**
 * Informational step marker (the backend assigns the authoritative step).
 */
step?: number | null, messages: Array<WireMessage>, };
