// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A content part in the wire format.
 */
export type WireContentPart = { "type": "text", text: string, } | { "type": "tool_call", tool_call_id: string, tool_name: string, input: JsonValue, } | { "type": "tool_result", tool_call_id: string, result: JsonValue, is_error?: boolean | null, };
