// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * What a failed API call observed — the field set of the AI SDK's
 * `APICallError` (`statusCode` / `responseBody`), which this project's error
 * taxonomy mirrors (docs/internal/vercel-research/07-kernel-infrastructure.md).
 *
 * Carried by [`AiMuxError::ApiCall`] alone. There are no per-status
 * variants: a 401, 404 or 429 is an `ApiCall` error whose classification is
 * read from `status_code`, exactly as the AI SDK reads
 * `APICallError.statusCode`. Transport failures (connection reset, DNS,
 * body read) are `ApiCall` errors too — no response arrived, so
 * `status_code` is `None` and `is_retryable` is `true`, exactly as the AI
 * SDK's `handleFetchError` builds an `APICallError` with no `statusCode`
 * and `isRetryable: true`. `message` holds the provider's text verbatim when
 * one is available; transport and parsing failures use a library message
 * with the source detail appended. The HTTP status is always a field, never
 * baked into the string; `Display` composes the human-readable form from the
 * fields at print time, so nothing downstream has to parse it back out.
 *
 * Every producer must provide the sanitized request URL and request values.
 * This keeps transport and response failures self-contained and matches the
 * AI SDK's `APICallError` contract.
 */
export type ApiCallError = {
/**
 * Sanitized request URL. Required for every API-derived failure.
 */
url: string,
/**
 * Sanitized request values used to create the API request.
 */
request_body_values: JsonValue,
/**
 * HTTP status of the response, when it came from one
 * (`APICallError.statusCode`). Always the *observed* status: the HTTP
 * layer fills it for every response-derived error; errors built without
 * an HTTP exchange leave it `None`.
 */
status_code: number | null,
/**
 * Provider's machine-readable code (OpenAI's `code`/`type`,
 * e.g. `"rate_limit_exceeded"` vs `"insufficient_quota"`). Never an HTTP
 * status. Our normalized take on `APICallError.data`.
 */
provider_code: string | null,
/**
 * Human-readable failure text. Provider text is verbatim when available;
 * locally detected transport/parse failures include their source detail.
 * Never includes an HTTP status prefix.
 */
message: string,
/**
 * The raw response body, verbatim (`APICallError.responseBody`) — the
 * lossless evidence when `message`/`provider_code` are extractions.
 * `None` when the error did not come from a response body.
 */
response_body: string | null,
/**
 * Sanitized response headers.
 */
response_headers: { [key in string]: string } | null,
/**
 * Parsed provider error data.
 */
data: JsonValue | null,
/**
 * Whether retrying can help (`APICallError.isRetryable`) — stored at
 * construction, exactly like the AI SDK: the response path computes it
 * from the status (408/409/429 or 5xx), and the transport path (no response, so
 * no status to compute from) sets it to `true` explicitly.
 */
is_retryable: boolean, };
