// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a failed API call observed — the field set of the AI SDK's
 * `APICallError` (`statusCode` / `responseBody`), which this project's error
 * taxonomy mirrors (docs/internal/vercel-research/07-kernel-infrastructure.md).
 *
 * Carried by [`AiMuxError::ApiCall`] alone. There are no per-status
 * variants: a 401, 404 or 429 is an `ApiCall` error whose classification is
 * read from `status_code`, exactly as the AI SDK reads
 * `APICallError.statusCode`. Transport failures (connection reset, DNS,
 * body read) are `ApiCall` errors too — no response arrived, so
 * `status_code` is `None` and `is_retryable` is `true`, exactly as the AI
 * SDK's `handleFetchError` builds an `APICallError` with no `statusCode`
 * and `isRetryable: true`. `message` holds the provider's text **only** —
 * the status is a field, never baked into the string; `Display` composes
 * the human-readable form from the fields at print time, so nothing
 * downstream has to parse it back out.
 *
 * `APICallError` fields not carried in this round: `url` /
 * `requestBodyValues` / `responseHeaders` (the request context is not
 * available at the error-construction sites today; all fields are
 * `#[serde(default)]`, so adding them later is not a breaking change).
 */
export type ApiCallError = { 
/**
 * HTTP status of the response, when it came from one
 * (`APICallError.statusCode`). Always the *observed* status: the HTTP
 * layer fills it for every response-derived error; errors built without
 * an HTTP exchange leave it `None`.
 */
status_code: number | null, 
/**
 * Provider's machine-readable code (OpenAI's `code`/`type`,
 * e.g. `"rate_limit_exceeded"` vs `"insufficient_quota"`). Never an HTTP
 * status. Our normalized take on `APICallError.data`.
 */
provider_code: string | null, 
/**
 * The failure's own text, without a status prefix — `Display` adds
 * that. Usually the provider's words as extracted from the body; on a
 * transport failure, or a body the extractor could not read, it is
 * ours. `response_body` is the lossless evidence either way.
 */
message: string, 
/**
 * The raw response body, verbatim (`APICallError.responseBody`) — the
 * lossless evidence when `message`/`provider_code` are extractions.
 * `None` when the error did not come from a response body.
 */
response_body: string | null, 
/**
 * Provider-assigned request id, from the `x-request-id` / `request-id`
 * response header when one was sent. Filled by the shared HTTP layer.
 */
request_id: string | null, 
/**
 * Retry hint in milliseconds, when the provider advertised one. Two
 * sources: the `retry-after-ms` / `retry-after` response headers on any
 * retryable status (RFC 7231 defines `Retry-After` for 503 as well as
 * 429), and the `retry_after_ms` / `retry_after` members of a JSON error
 * payload, which arrive on whatever status that payload came with. The
 * classification lives in `status_code`; this is the matching action
 * input, and it is never fabricated locally.
 */
retry_after_ms: number | null, 
/**
 * Whether retrying can help (`APICallError.isRetryable`) — stored at
 * construction, exactly like the AI SDK: the response path computes it
 * from the status (408/409/429 or 5xx), and the transport path (no response, so
 * no status to compute from) sets it to `true` explicitly.
 */
is_retryable: boolean, };
