// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationInput } from "./EvaluationInput";

/**
 * The optional descriptions of a Boolean question's outcomes. An absent key
 * and an explicit `null` differ: `Some(None)` is `null` (no description).
 */
export type BooleanCriteria = { true?: EvaluationInput | null, false?: EvaluationInput | null, };
