// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedFileData } from "./GeneratedFileData";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A part of a multi-part message.
 *
 * Shared between `ModelMessage` (user-facing) and `LanguageModelPrompt` (provider-facing).
 */
export type ContentPart = { "type": "text", text: string, 
/**
 * Provider-specific options for this part (e.g. `openai.promptCacheBreakpoint`).
 */
provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "custom", kind: string, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "reasoning_file", data: GeneratedFileData, media_type: string, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "tool_approval_request", approval_id: string, tool_call_id: string, reason?: string | null, is_automatic?: boolean | null, signature?: string | null, input_schema_input?: JsonValue | null, } | { "type": "image", image: Array<number>, media_type: string, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "file", data: Array<number>, media_type: string, filename?: string | null, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "file_base64", data: string, media_type: string, filename?: string | null, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "file_url", url: string, media_type: string, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "file_reference", media_type: string, reference: JsonValue, filename?: string | null, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "reasoning", text: string, signature: string | null, 
/**
 * Provider-specific options for this part (e.g.
 * `anthropic.signature`, `anthropic.redactedData`,
 * `anthropic.cacheControl`).
 */
provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "tool_call", tool_call_id: string, tool_name: string, 
/**
 * Arguments as a JSON value (usually an object).
 */
input: JsonValue, 
/**
 * Whether the tool call is executed by the provider rather than by
 * the client. This is part of the prompt contract because providers
 * need it to replay server tool calls on a later turn.
 */
provider_executed?: boolean | null, 
/**
 * Provider-assigned thought signature (e.g. Google Gemini
 * `thoughtSignature`). Must be echoed back verbatim on the follow-up
 * turn when the tool result is sent.
 */
thought_signature?: string | null, 
/**
 * Provider-specific options for this part (e.g.
 * `anthropic.cacheControl`).
 */
provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, } | { "type": "tool_result", tool_call_id: string, 
/**
 * The tool's output (usually a JSON value or plain text).
 *
 * Accepts the legacy `output` field name (used by the Vercel AI SDK
 * and the 0.1.0 TypeScript bindings) as an alias during deserialization,
 * so multi-part tool messages constructed either way round-trip
 * correctly. Serialization always emits `result`.
 */
result: JsonValue, 
/**
 * The name of the tool that produced this result (optional on the
 * user-input side; providers that need it can look it up from the
 * preceding tool call).
 */
tool_name?: string | null, 
/**
 * Whether the result is an error or error message.
 */
is_error?: boolean | null, 
/**
 * Whether the result is preliminary (replaces prior, e.g. image previews).
 */
preliminary?: boolean | null, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean | null, 
/**
 * Provider-specific options for this part (e.g.
 * `anthropic.cacheControl`).
 */
provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, };
