// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Provider-specific custom content.
 */
export type CustomPart = { kind: string, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, };
