// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Provider-specific content identified by its provider and kind.
 */
export type CustomPart = { kind: string, providerOptions?: { [key in string]: { [key in string]: JsonValue } }, };
