// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionDescription } from "./DecisionDescription";

export type DecisionAnswer = { "type": "refusal" } | { "type": "boolean", probability_true: number, } | { "type": "choice", selected: string, probabilities: { [key in string]: number } | null, confidence: number | null, } | { "type": "score", expected_value: number, levels: Array<DecisionDescription>, probabilities: Array<number> | null, confidence: number | null, };
