// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the provider produced probability values. This is provenance, not a
 * calibration guarantee. Raw provider metadata retains calibration details.
 */
export type DecisionProbabilitySource = "native" | "logit_scoring" | "model_estimate";
