// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A native choice value, distinct from the canonical option label used as a key.
 */
export type DecisionValue = string | boolean;
