// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionProbabilitySource } from "./DecisionProbabilitySource";
import type { DecisionRounding } from "./DecisionRounding";

export type DecisionCapabilities = { rounding: DecisionRounding, probability_source: DecisionProbabilitySource, supports_boolean: boolean, supports_choice: boolean, supports_score: boolean, returns_distributions: boolean, max_questions: number | null, min_choices: number | null, max_choices: number | null, max_score_levels: number | null, };
