// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named score level with a separate description (OpenAI's native rubric).
 * Convert into `DecisionDescription` to use it in `DecisionQuestion::Score`.
 */
export type DecisionScoreLevel = { label: string, description?: string | null, };
