// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionQuestion } from "./DecisionQuestion";
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { JsonValue } from "./serde_json/JsonValue";

export type DecisionCallOptions = { state: JsonValue, questions: Array<DecisionQuestion>, max_retries?: number | null, timeout?: TimeoutConfiguration | null, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, headers?: { [key in string]: string } | null, };
