// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Options passed to [`EmbeddingModel::do_embed`].
 *
 * Aligned with V4 `EmbeddingModelV4CallOptions`.
 */
export type EmbeddingCallOptions = {
/**
 * List of text values to generate embeddings for.
 */
values: Array<string>,
/**
 * Per-call retry override. `None` uses the model default.
 */
max_retries: number | null,
/**
 * Per-call operation timeout.
 */
timeout: TimeoutConfiguration | null,
/**
 * Additional provider-specific options, keyed by provider name.
 */
provider_options: { [key in string]: JsonValue } | null,
/**
 * Additional HTTP headers to send with the request.
 */
headers: { [key in string]: string } | null, };
