// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared state or structured instructions for an evaluation
 * (`EvaluationModelV4Input`: a string, a JSON object or a JSON array).
 */
export type EvaluationInput = string | Record<string, unknown> | Array<unknown>;
