// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationAnswer } from "./EvaluationAnswer";
import type { EvaluationRounding } from "./EvaluationRounding";
import type { EvaluationUsage } from "./EvaluationUsage";
import type { ResponseInfo } from "./ResponseInfo";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of [`EvaluationModel::do_evaluate`] (`EvaluationModelV4Result`).
 */
export type EvaluationResult = {
/**
 * Exactly one answer per question, under the original question ids.
 */
answers: { [key in string]: EvaluationAnswer }, rounding?: EvaluationRounding, usage?: EvaluationUsage, warnings: Array<Warning>, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, response?: ResponseInfo, };
