// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileData } from "./FileData";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * File content part (the only file part; `data` is a tagged `FileData`).
 */
export type FilePart = { data: FileData, mediaType: string, filename?: string, providerOptions?: { [key in string]: { [key in string]: JsonValue } }, };
