// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Either raw bytes or a base64-encoded string.
 *
 * Providers should pass file data through without unnecessary conversion: if
 * the upstream API returns base64, return [`FileBytes::Base64`]; if it
 * returns binary, return [`FileBytes::Binary`].
 */
export type FileBytes = { "Binary": Array<number> } | { "Base64": string };
