// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool definition passed to the model in `CallOptions.tools`.
 */
export type FunctionTool = { 
/**
 * Unique tool name.
 */
name: string, 
/**
 * Human-readable description.
 */
description: string | null, 
/**
 * JSON Schema describing the tool's parameters.
 */
input_schema: JsonValue, 
/**
 * Whether the tool supports strict schema enforcement (OpenAI strict mode).
 */
strict: boolean | null, 
/**
 * Provider-specific options, keyed by provider name
 * (e.g. `{"anthropic": {"eagerInputStreaming": true}}`). Aligned with the
 * V4 `providerOptions` field on function tools.
 */
provider_options?: { [key in string]: JsonValue } | null, 
/**
 * Example inputs for the tool (V4 `inputExamples`), used by some providers
 * to emit `input_examples` in the request body.
 */
input_examples?: Array<JsonValue> | null, };
