// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { GenerateResult } from "./GenerateResult";
import type { ToolCall } from "./ToolCall";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";

/**
 * Result of `generate_text` (user-facing).
 */
export type GenerateTextResult = { 
/**
 * The generated text (concatenated from all text content parts).
 */
text: string, 
/**
 * Tool calls requested by the model.
 */
tool_calls: Array<ToolCall>, 
/**
 * Why generation stopped.
 */
finish_reason: FinishReason, 
/**
 * Token usage.
 */
usage: Usage, 
/**
 * Warnings from the provider.
 */
warnings: Array<Warning>, 
/**
 * Raw provider result (for advanced use).
 */
raw: GenerateResult, };
