// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { GenerateTextResult } from "./GenerateTextResult";
import type { ResponseMetadata } from "./ResponseMetadata";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Result of `generate_object` (user-facing, M12). The parsed JSON object plus
 * convenience fields from the underlying `generate_text` call.
 */
export type GenerateObjectResult = { 
/**
 * The parsed JSON object returned by the model.
 */
object: JsonValue, 
/**
 * Why generation stopped.
 */
finish_reason: FinishReason, 
/**
 * Raw provider-specific finish reason string.
 */
raw_finish_reason: string | null, 
/**
 * Token usage.
 */
usage: Usage, 
/**
 * Warnings from the provider.
 */
warnings: Array<Warning>, 
/**
 * Concatenated reasoning text (if the model produced reasoning/thinking).
 */
reasoning: string | null, 
/**
 * Provider-specific metadata (e.g. Anthropic cache info).
 */
provider_metadata: JsonValue | null, 
/**
 * Response metadata (id, timestamp, model_id).
 */
response: ResponseMetadata, 
/**
 * The full `generate_text` result (for advanced use).
 */
raw: GenerateTextResult, };
