// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileData } from "./FileData";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A content item in the generation result.
 */
export type GenerateContent = { "Text": { text: string, provider_metadata?: JsonValue | null, } } | { "ToolCall": { tool_call_id: string, tool_name: string, 
/**
 * The model's raw argument text, exactly as the provider delivered
 * it (possibly malformed). Providers never parse it — `generate_text`
 * owns parsing, schema validation, and repair.
 *
 * Always serializes as a JSON string. Deserializes a JSON string
 * (the current wire shape) unchanged, and also re-serializes the
 * pre-refactor shape — an already-parsed JSON value — to its compact
 * JSON text, so a `GenerateResult` persisted before this field
 * became a `String` keeps loading. See docs/api/gaps.md §9.
 */
input: string, 
/**
 * Whether the tool call will be executed by the provider.
 * If false/unset, the tool call is executed by the client.
 */
provider_executed?: boolean | null, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean | null, 
/**
 * Provider-assigned thought signature (e.g. Google Gemini
 * `thoughtSignature`). Must be echoed back verbatim on the follow-up
 * turn when the tool result is sent.
 */
thought_signature?: string | null, 
/**
 * Additional provider-specific metadata for the tool call.
 */
provider_metadata?: JsonValue | null, } } | { "Source": { id: string, source_type: string, url: string | null, title: string | null, provider_metadata?: JsonValue | null, } } | { "Reasoning": { text: string, provider_metadata: JsonValue | null, } } | { "File": { data: FileData, media_type: string, provider_metadata?: JsonValue | null, } } | { "ToolResult": { tool_call_id: string, tool_name: string, result: JsonValue, 
/**
 * Whether the result is an error or error message.
 */
is_error?: boolean | null, 
/**
 * Whether the result is preliminary (replaces prior, e.g. image previews).
 */
preliminary?: boolean | null, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean | null, 
/**
 * Additional provider-specific metadata for the tool result.
 */
provider_metadata?: JsonValue | null, } };
