// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { GenerateContent } from "./GenerateContent";
import type { GeneratedFile } from "./GeneratedFile";
import type { RawToolApprovalRequest } from "./RawToolApprovalRequest";
import type { RawToolCall } from "./RawToolCall";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Result of `LanguageModel::do_generate` (non-streaming).
 */
export type GenerateResult = { content: Array<GenerateContent<RawToolCall, RawToolApprovalRequest, GeneratedFile>>, finish_reason: FinishReason, usage: Usage, warnings: Array<Warning>, provider_metadata: JsonValue | null, response: { id: string | null, timestamp: string | null, model_id: string | null, body?: JsonValue | null, } | null, request_body: JsonValue | null, response_headers: { [key in string]: string } | null, };
