// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response metadata and HTTP details from a generation call.
 */
export type GenerateResponse = { id: string | null, timestamp: string | null, model_id: string | null, headers: { [key in string]: string } | null, body: JsonValue | null, };
