// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ResponseFormat } from "./ResponseFormat";
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * User-facing options for `generate_text` and `stream_text`.
 *
 * Unlike `CallOptions` (provider-facing), this does not include `prompt`
 * (passed separately) and defaults are more ergonomic.
 */
export type GenerateTextOptions = { maxOutputTokens?: number, temperature?: number, stopSequences?: Array<string>, topP?: number, topK?: number, presencePenalty?: number, frequencyPenalty?: number, responseFormat?: ResponseFormat, seed?: number, tools?: Array<Tool>, toolChoice?: ToolChoice, headers?: { [key in string]: string }, providerOptions?: { [key in string]: { [key in string]: JsonValue } }, 
/**
 * Top-level reasoning effort.
 */
reasoning?: ReasoningEffort, 
/**
 * System instructions prepended to the prompt.
 */
instructions?: string, 
/**
 * Per-call retry count override. `None` = provider default, `Some(0)` = disable.
 */
maxRetries?: number, 
/**
 * Per-call timeout configuration (total / first-chunk / chunk idle).
 */
timeout?: TimeoutConfiguration, 
/**
 * Session identifier, for grouping consecutive calls into a session
 * (observability, see RFC-0024). Orthogonal to RFC-0019 session-affinity
 * headers. When `None` and the optional session inferer is enabled, one
 * may be inferred from prompt-prefix continuation.
 */
sessionId?: string, 
/**
 * Emit raw provider stream chunks as `StreamPart::Raw` (debugging aid).
 */
includeRawChunks?: boolean, };
