// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedFile } from "./GeneratedFile";
import type { RawToolApprovalRequest } from "./RawToolApprovalRequest";
import type { RawToolCall } from "./RawToolCall";
import type { ReasoningOutput } from "./ReasoningOutput";
import type { Source } from "./Source";
import type { ToolResult } from "./ToolResult";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A content item in the generation result.
 */
export type GenerateContent<C = RawToolCall, A = RawToolApprovalRequest, R = GeneratedFile> = { "type": "text", text: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-call" } & C | { "type": "source" } & Source | { "type": "reasoning" } & ReasoningOutput | { "type": "file" } & GeneratedFile | { "type": "reasoning-file" } & R | { "type": "custom", kind: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-approval-request" } & A | { "type": "tool-result" } & ToolResult;
