// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ResponseFormat } from "./ResponseFormat";
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * User-facing options for `generate_text` and `stream_text`.
 *
 * Unlike `CallOptions` (provider-facing), this does not include `prompt`
 * (passed separately) and defaults are more ergonomic.
 */
export type GenerateTextOptions = { max_output_tokens: number | null, temperature: number | null, stop_sequences: Array<string> | null, top_p: number | null, top_k: number | null, presence_penalty: number | null, frequency_penalty: number | null, response_format: ResponseFormat | null, seed: bigint | null, tools: Array<Tool> | null, tool_choice: ToolChoice | null, headers: { [key in string]: string } | null, provider_options: { [key in string]: JsonValue } | null, 
/**
 * Top-level reasoning effort.
 */
reasoning: ReasoningEffort | null, 
/**
 * System instructions prepended to the prompt.
 */
instructions: string | null, 
/**
 * Per-call request body overrides (deep-merged). See RFC-0017.
 */
body_overrides: JsonValue | null, 
/**
 * Per-call retry count override. `None` = provider default, `Some(0)` = disable.
 */
max_retries: number | null, 
/**
 * Per-call timeout configuration (total / first-chunk / chunk idle).
 */
timeout: TimeoutConfiguration | null, };