// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileData } from "./FileData";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A file generated by the model (e.g. an image or document). Mirrors the Vercel
 * AI SDK `file` content type: `data` is a tagged union covering base64 data,
 * URL, or provider reference. The payload of both `GenerateContent::File` and
 * `StreamPart::File`, and the element of the text results' `files`.
 */
export type GeneratedFile = { data: FileData, media_type: string, provider_metadata?: { [key in string]: { [key in string]: JsonValue } } | null, };
