// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The generated images, returned as a homogeneous collection.
 *
 * The TS result type is `Array<string> | Array<Uint8Array>` — i.e. either all
 * base64 strings or all binary blobs, never mixed. This enum models that
 * union. Providers should return data without unnecessary conversion: if the
 * upstream API returns base64, return [`ImageOutputs::Base64`]; if binary,
 * return [`ImageOutputs::Binary`].
 */
export type ImageOutputs = { "Base64": Array<string> } | { "Binary": Array<Array<number>> };
