// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage for an image generation call (if the provider reports it).
 *
 * Aligned with V4 `ImageModelV4Usage`.
 */
export type ImageUsage = { 
/**
 * Number of input (prompt) tokens used.
 */
input_tokens: number | null, 
/**
 * Number of output tokens used, if reported.
 */
output_tokens: number | null, 
/**
 * Total tokens as reported by the provider.
 */
total_tokens: number | null, };
