// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input token usage detail.
 */
export type InputTokenUsage = { 
/**
 * Total tokens.
 */
total?: number, 
/**
 * Tokens that were not served from cache.
 */
noCache?: number, 
/**
 * Tokens served from cache (read).
 */
cacheRead?: number, 
/**
 * Tokens written to cache.
 */
cacheWrite?: number, };
