// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantPart } from "./AssistantPart";
import type { ToolPart } from "./ToolPart";
import type { UserPart } from "./UserPart";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single provider-facing message, a union by role.
 *
 * `provider_options` is message-level (e.g. `anthropic.cacheControl`),
 * mirroring `LanguageModelV4Message.providerOptions`.
 */
export type LanguageModelMessage = { "role": "system", content: string, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, } | { "role": "user", content: Array<UserPart>, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, } | { "role": "assistant", content: Array<AssistantPart>, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, } | { "role": "tool", content: Array<ToolPart>, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, };
