// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentPart } from "./ContentPart";
import type { Role } from "./Role";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single provider-facing message.
 *
 * Unlike `ModelMessage` (which can have string content), this always has
 * `content: Vec<ContentPart>` — strings are normalized to `ContentPart::Text`.
 */
export type LanguageModelPromptMessage = { role: Role, content: Array<ContentPart>, 
/**
 * Message-level provider-specific options (e.g.
 * `anthropic.cacheControl`), applied to the last part of the message when
 * converting to a provider prompt. Mirrors the Vercel AI SDK
 * `LanguageModelV4Message.providerOptions`.
 */
provider_options: JsonValue | null, };
