// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentPart } from "./ContentPart";

/**
 * Message body: either a simple string or multi-part content.
 */
export type MessageContent = string | Array<ContentPart>;
