// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model identifier in `"provider/model-name"` format, e.g. `"openai/gpt-4o"`.
 */
export type ModelId = { provider: string, model: string, };
