// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pricing (advisory, read-only metadata). Units follow the source catalog
 * (anya2a uses USD per 1M tokens).
 */
export type ModelCost = { input?: number, output?: number, cacheRead?: number, cacheWrite?: number, };
