// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token / request limits for a model.
 */
export type ModelLimits = { 
/**
 * Maximum total context window (input + output), in tokens.
 */
context?: number | null, 
/**
 * Maximum output tokens.
 */
output?: number | null, 
/**
 * Maximum input tokens (when distinct from `context`).
 */
input?: number | null, };
