// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model-level capability flags (more precise than provider-level `supports_*`).
 */
export type ModelCapabilities = { 
/**
 * Supports function/tool calling.
 */
toolCall: boolean, 
/**
 * Supports structured / JSON-schema output.
 */
structuredOutput: boolean, 
/**
 * Accepts a `temperature` parameter.
 */
temperature: boolean, 
/**
 * Accepts multimodal attachments (image/audio/pdf input).
 */
attachment: boolean, };
