// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 调用终结状态。
 */
export type OutcomeStatus = "pending" | "success" | "error" | "incomplete" | "cancelled";
