// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeStatus } from "./OutcomeStatus";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 最终结果摘要。
 */
export type OutcomeRecord = { status: OutcomeStatus, finish_reason: string | null, error: string | null,
/**
 * Lossless structured domain error. In particular, `RetryError.errors`
 * keeps the complete attempt history rather than only its display text.
 */
error_value: JsonValue | null,
/**
 * 序列化的 Usage。
 */
usage: JsonValue | null, };
