// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output token usage detail.
 */
export type OutputTokenUsage = { total?: number, 
/**
 * Text (non-reasoning) tokens (output side).
 */
text?: number, 
/**
 * Reasoning tokens (output side).
 */
reasoning?: number, };
