// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider family (only families with distinct invariants need dispatch;
 * gran/threshold/ttl live in `ProviderAuditSpec`).
 */
export type ProviderFamily = "OpenAi" | "DeepSeek" | "Anthropic" | "Gemini" | "Vllm" | "Generic";
