// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Provider-facing tool call before Core parses and validates its input.
 *
 * The wire shape matches [`ToolCall`] field for field, except that `input`
 * is the provider's raw argument *text* rather than a parsed value.
 */
export type RawToolCall = { toolCallId: string, toolName: string, input: string, providerExecuted?: boolean, dynamic?: boolean, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, };
