// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Provider approval request for a provider-executed call.
 */
export type RawToolApprovalRequest = { approval_id: string, tool_call_id: string, provider_metadata?: { [key in string]: { [key in string]: JsonValue } } | null, };
