// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningFileOutput } from "./ReasoningFileOutput";
import type { ReasoningOutput } from "./ReasoningOutput";

/**
 * Text or a generated file produced during reasoning.
 */
export type ReasoningPart = ReasoningOutput | ReasoningFileOutput;
