// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reasoning / thinking segment, extracted to the top level (M7).
 */
export type ReasoningPart = { 
/**
 * The reasoning text.
 */
text: string, };
