// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedFileData } from "./GeneratedFileData";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A file generated as part of reasoning.
 */
export type ReasoningFilePart = { data: GeneratedFileData, media_type: string, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, };
