// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A reasoning / thinking segment produced by the model. Mirrors the Vercel AI
 * SDK `reasoning` content type; `provider_metadata` carries provider-specific
 * data such as the Anthropic thinking-block signature
 * (`providerMetadata.anthropic.signature`). The payload of
 * `GenerateContent::Reasoning` and the element of the text results' `reasoning`.
 */
export type ReasoningOutput = { text: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, };
