// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operation stored in a unified recording. Older recordings are language calls.
 */
export type RecordingOperation = "language_model" | "decision";
