// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Optional request information for telemetry and debugging.
 *
 * Aligned with the `request?` object that appears on some V4 model results.
 */
export type RequestInfo = { 
/**
 * The request body that was sent (opaque JSON).
 */
body: JsonValue | null, };
