// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSpec } from "./ModelSpec";

/**
 * A model discovered at runtime, optionally enriched with a static portrait.
 *
 * `spec` is `Some` when community knowledge (anya2a) had an entry for this
 * `(provider, model_id)`; otherwise `None` and the caller falls back to
 * provider-level defaults (today's behaviour).
 */
export type ResolvedModel = { id: string, owned_by?: string | null, created?: number | null, spec?: ModelSpec | null, };
