// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about the API response.
 */
export type ResponseMetadata = { id: string | null, timestamp: string | null, model_id: string | null, };
