// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response information for telemetry and debugging.
 *
 * Aligned with the `response` object that appears on most V4 model results.
 * All fields are optional because different providers populate different
 * subsets; traits whose TS spec marks `response` as required use
 * `ResponseInfo` directly, while those that mark it optional use
 * `Option<ResponseInfo>`.
 */
export type ResponseInfo = { 
/**
 * Timestamp for the start of the generated response (ISO 8601 string).
 */
timestamp: string | null, 
/**
 * The ID of the model that was used to generate the response.
 */
model_id: string | null, 
/**
 * Response headers.
 */
headers: { [key in string]: string } | null, 
/**
 * The response body (opaque JSON).
 */
body: JsonValue | null, };
