// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Options passed to [`SearchModel::do_search`].
 */
export type SearchCallOptions = { 
/**
 * The search query string.
 */
query: string, 
/**
 * Maximum number of results to return.
 */
maxResults?: number, 
/**
 * Whether to include raw page content in results.
 *
 * Provider support varies; providers that cannot honor this should
 * issue a warning rather than erroring.
 */
includeRawContent?: boolean, 
/**
 * Optional time range filter (e.g. `"day"`, `"week"`, `"month"`,
 * `"year"`). Provider support varies.
 */
timeRange?: string, 
/**
 * Optional list of domains to include in results.
 */
includeDomains?: Array<string>, 
/**
 * Optional list of domains to exclude from results.
 */
excludeDomains?: Array<string>, 
/**
 * Per-call retry override. `None` uses the model default.
 */
maxRetries?: number, 
/**
 * Per-call operation timeout.
 */
timeout?: TimeoutConfiguration, 
/**
 * Additional provider-specific options, keyed by provider name.
 */
providerOptions?: { [key in string]: { [key in string]: JsonValue } }, 
/**
 * Additional HTTP headers to send with the request.
 */
headers?: { [key in string]: string }, };
