// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResponse } from "./SearchResponse";
import type { SearchResultItem } from "./SearchResultItem";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of [`SearchModel::do_search`].
 */
export type SearchResult = { 
/**
 * Ordered list of search results.
 */
results: Array<SearchResultItem>, 
/**
 * An optional direct answer / summary (some providers return
 * an AI-generated answer alongside results).
 */
answer?: string, 
/**
 * Additional provider-specific metadata.
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, 
/**
 * Warnings for the call.
 */
warnings: Array<Warning>, 
/**
 * Optional response information for debugging.
 */
response?: SearchResponse, };
