// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single search result item.
 */
export type SearchResultItem = { 
/**
 * The title of the result (e.g. page title).
 */
title: string | null, 
/**
 * The URL of the result.
 */
url: string | null, 
/**
 * A snippet/summary of the result content.
 */
content: string | null, 
/**
 * Raw page content (when `include_raw_content` is requested and
 * supported by the provider).
 */
raw_content: string | null, 
/**
 * A relevance score (0.0–1.0) if the provider returns one.
 */
score: number | null, 
/**
 * Provider-specific metadata for this result.
 */
provider_metadata: { [key in string]: JsonValue } | null, };
