// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict";

/**
 * One step of a session's cache-hit trajectory (RFC-0024 §4.3).
 */
export type SessionStepStat = { 
/**
 * Step within the session (0-based, session order).
 */
step: number, 
/**
 * The call's id (association key into Recording / replay, RFC-0023).
 */
callId: string, 
/**
 * Reported hit rate for this step (`cache_read / input_total`); `None`
 * when the call carried no input/cache-read usage.
 */
hitRate?: number, 
/**
 * Audit verdict (present only when an auditor is attached).
 */
verdict?: Verdict, 
/**
 * Error string for failed calls (failures are part of the session).
 */
error?: string, };
