// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single call within a session (an index entry only — call content lives
 * in Recording (RFC-0023) / TraceRecord (RFC-0015)).
 */
export type SessionCall = { 
/**
 * Call-level unique id. This is the association key for the future
 * Recording / TraceRecord `call_id` (RFC-0015/0023): once those land,
 * this field carries their value.
 */
call_id: string, 
/**
 * Step within the session (0-based).
 */
step: number, 
/**
 * When the call was recorded (RFC 3339 UTC, millisecond precision).
 */
recorded_at: string, };
