// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image/video size in `{width}x{height}` format (e.g. `"1024x1024"`).
 *
 * Newtype that enforces the `WxH` format used by V4 image `size` and video
 * `resolution` options. Aligned with the TS template-literal type
 * `` `${number}x${number}` ``.
 */
export type Size = { width: number, height: number, };
