// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A source / citation (e.g. URL citation from search-preview models). The
 * payload of both `GenerateContent::Source` and `StreamPart::Source`, and the
 * element of the text results' `sources`.
 */
export type Source = { "sourceType": "url", id: string, url: string, title?: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "sourceType": "document", id: string, mediaType: string, title: string, filename?: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, };
