// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Optional request information for a speech call.
 */
export type SpeechRequest = { 
/**
 * Response body (HTTP providers only).
 */
body: JsonValue | null, };
