// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMuxError } from "./AiMuxError";
import type { FinishReason } from "./FinishReason";
import type { GeneratedFile } from "./GeneratedFile";
import type { RawToolApprovalRequest } from "./RawToolApprovalRequest";
import type { RawToolCall } from "./RawToolCall";
import type { ResponseMetadata } from "./ResponseMetadata";
import type { Source } from "./Source";
import type { ToolResult } from "./ToolResult";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single chunk in the stream returned by `do_stream`.
 *
 * Generic over the tool-call payload: providers emit the default
 * [`StreamPart`] (raw argument text); `stream_text` emits [`TextStreamPart`]
 * (parsed and validated [`ToolCall`]).
 */
export type StreamPart = { "type": "text-start", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "text-delta", id: string, delta: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "text-end", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "stream-start", warnings: Array<Warning>, } | { "type": "finish", finishReason: FinishReason, usage: Usage, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "error", error: AiMuxError, } | { "type": "tool-input-start", id: string, toolName: string, 
/**
 * Whether the tool call will be executed by the provider.
 */
providerExecuted?: boolean, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean, 
/**
 * Optional title for the tool call.
 */
title?: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-input-delta", id: string, delta: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-input-end", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-call" } & RawToolCall | { "type": "tool-result" } & ToolResult | { "type": "file" } & GeneratedFile | { "type": "reasoning-file" } & GeneratedFile | { "type": "custom", kind: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-approval-request" } & RawToolApprovalRequest | { "type": "reasoning-start", id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "reasoning-delta", id: string, delta: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "reasoning-end", id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "response-metadata" } & ResponseMetadata | { "type": "source" } & Source | { "type": "raw", rawValue: JsonValue, };
