// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response information returned when starting a language-model stream.
 */
export type StreamResponseInfo = { headers?: { [key in string]: string }, };
