// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMuxError } from "./AiMuxError";
import type { FinishReason } from "./FinishReason";
import type { GeneratedFile } from "./GeneratedFile";
import type { ReasoningFileOutput } from "./ReasoningFileOutput";
import type { ResponseMetadata } from "./ResponseMetadata";
import type { Source } from "./Source";
import type { ToolApprovalRequestOutput } from "./ToolApprovalRequestOutput";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single chunk in the stream returned by `do_stream`.
 *
 * Generic over the tool-call payload: providers emit the default
 * [`StreamPart`] (raw argument text); `stream_text` emits [`TextStreamPart`]
 * (parsed and validated [`ToolCall`]).
 */
export type StreamPart = { "TextStart": { id: string, provider_metadata?: JsonValue | null, } } | { "TextDelta": { id: string, delta: string, provider_metadata?: JsonValue | null, } } | { "TextEnd": { id: string, provider_metadata?: JsonValue | null, } } | { "StreamStart": { warnings: Array<Warning>, } } | { "Finish": { finish_reason: FinishReason, usage: Usage, provider_metadata: JsonValue | null, } } | { "Error": { error: AiMuxError, } } | { "ToolInputStart": { id: string, tool_name: string, 
/**
 * Whether the tool call will be executed by the provider.
 */
provider_executed?: boolean | null, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean | null, 
/**
 * Optional title for the tool call.
 */
title?: string | null, provider_metadata?: JsonValue | null, } } | { "ToolInputDelta": { id: string, delta: string, provider_metadata?: JsonValue | null, } } | { "ToolInputEnd": { id: string, provider_metadata?: JsonValue | null, } } | { "ToolCall": ToolCall } | { "ToolResult": ToolResult } | { "File": GeneratedFile } | { "ReasoningFile": ReasoningFileOutput } | { "Custom": { kind: string, provider_metadata?: JsonValue | null, } } | { "ToolApprovalRequest": ToolApprovalRequestOutput } | { "ReasoningStart": { id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
provider_metadata: JsonValue | null, } } | { "ReasoningDelta": { id: string, delta: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
provider_metadata: JsonValue | null, } } | { "ReasoningEnd": { id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
 */
provider_metadata: JsonValue | null, } } | { "ResponseMetadata": ResponseMetadata } | { "Source": Source } | { "Raw": { raw_value: JsonValue, } };
