// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePart } from "./FilePart";
import type { FinishReason } from "./FinishReason";
import type { ModelMessage } from "./ModelMessage";
import type { ReasoningPart } from "./ReasoningPart";
import type { ResponseMetadata } from "./ResponseMetadata";
import type { SourcePart } from "./SourcePart";
import type { ToolCall } from "./ToolCall";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Aggregated result of `stream_text().consume()` (M11). Mirrors
 * `GenerateTextResult`'s user-facing fields (without `raw`, since streaming
 * has no `GenerateResult` equivalent).
 */
export type StreamTextResultAggregated = { 
/**
 * The generated text (concatenated `TextDelta`).
 */
text: string, 
/**
 * Reasoning / thinking segments.
 */
reasoning: Array<ReasoningPart>, 
/**
 * Concatenated reasoning text.
 */
reasoning_text: string, 
/**
 * Tool calls requested by the model.
 */
tool_calls: Array<ToolCall>, 
/**
 * Sources / citations.
 */
sources: Array<SourcePart>, 
/**
 * Files generated by the model.
 */
files: Array<FilePart>, 
/**
 * Why generation stopped.
 */
finish_reason: FinishReason, 
/**
 * Raw provider-specific finish reason string.
 */
raw_finish_reason: string | null, 
/**
 * Token usage.
 */
usage: Usage, 
/**
 * Total token usage across all steps. In single-step mode (aimux's
 * default), `total_usage` equals `usage`. Provided for AI SDK parity.
 */
total_usage: Usage, 
/**
 * Warnings from the provider.
 */
warnings: Array<Warning>, 
/**
 * Provider-specific metadata from the Finish chunk.
 */
provider_metadata: JsonValue | null, 
/**
 * Response metadata (id, timestamp, model_id) if emitted by the stream.
 */
response: ResponseMetadata | null, 
/**
 * Assistant messages ready to append for the next turn.
 */
response_messages: Array<ModelMessage>, };
