// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMuxError } from "./AiMuxError";
import type { FinishReason } from "./FinishReason";
import type { GeneratedFile } from "./GeneratedFile";
import type { ReasoningFileOutput } from "./ReasoningFileOutput";
import type { ResponseInfo } from "./ResponseInfo";
import type { Source } from "./Source";
import type { ToolApprovalRequestOutput } from "./ToolApprovalRequestOutput";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { Usage } from "./Usage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A public call-layer stream chunk, with parsed tool calls.
 */
export type TextStreamPart = { "type": "text-start", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "text-delta", id: string, delta: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "text-end", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "stream-start", warnings: Array<Warning>, } | { "type": "finish", finishReason: FinishReason, usage: Usage, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "finish-step", finishReason: FinishReason, usage: Usage, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, response: ResponseInfo, } | { "type": "error", error: AiMuxError, } | { "type": "tool-input-start", id: string, toolName: string, 
/**
 * Whether the tool call will be executed by the provider.
 */
providerExecuted?: boolean, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean, 
/**
 * Optional title for the tool call.
 */
title?: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-input-delta", id: string, delta: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-input-end", id: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-call" } & ToolCall | { "type": "tool-result" } & ToolResult | { "type": "file" } & GeneratedFile | { "type": "reasoning-file" } & ReasoningFileOutput | { "type": "custom", kind: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-approval-request" } & ToolApprovalRequestOutput | { "type": "reasoning-start", id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "reasoning-delta", id: string, delta: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "reasoning-end", id: string, 
/**
 * Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "source" } & Source | { "type": "raw", rawValue: JsonValue, };
