// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedFile } from "./GeneratedFile";
import type { RawToolApprovalRequest } from "./RawToolApprovalRequest";
import type { RawToolCall } from "./RawToolCall";
import type { ReasoningFileOutput } from "./ReasoningFileOutput";
import type { ReasoningOutput } from "./ReasoningOutput";
import type { Source } from "./Source";
import type { ToolApprovalRequestOutput } from "./ToolApprovalRequestOutput";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { JsonValue } from "./serde_json/JsonValue";

export type TextContent = { "Text": { text: string, provider_metadata?: JsonValue | null, } } | { "ToolCall": ToolCall } | { "Source": Source } | { "Reasoning": ReasoningOutput } | { "File": GeneratedFile } | { "ReasoningFile": ReasoningFileOutput } | { "Custom": { kind: string, provider_metadata?: JsonValue | null, } } | { "ToolApprovalRequest": ToolApprovalRequestOutput } | { "ToolResult": ToolResult };
