// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Text content part.
 */
export type TextPart = { text: string, providerOptions?: { [key in string]: { [key in string]: JsonValue } }, };
