// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedFile } from "./GeneratedFile";
import type { RawToolApprovalRequest } from "./RawToolApprovalRequest";
import type { RawToolCall } from "./RawToolCall";
import type { ReasoningFileOutput } from "./ReasoningFileOutput";
import type { ReasoningOutput } from "./ReasoningOutput";
import type { Source } from "./Source";
import type { ToolApprovalRequestOutput } from "./ToolApprovalRequestOutput";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { JsonValue } from "./serde_json/JsonValue";

export type TextContent = { "type": "text", text: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-call" } & ToolCall | { "type": "source" } & Source | { "type": "reasoning" } & ReasoningOutput | { "type": "file" } & GeneratedFile | { "type": "reasoning-file" } & ReasoningFileOutput | { "type": "custom", kind: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, } | { "type": "tool-approval-request" } & ToolApprovalRequestOutput | { "type": "tool-result" } & ToolResult;
