// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
/**
 * Per-call timeout configuration.
 *
 * Aligned with V4 `LanguageModelV4CallOptions.timeout`
 * (`TimeoutConfiguration`). All values are milliseconds; `None` disables the
 * corresponding limit. A `total` timeout also covers retry backoff and the
 * whole streamed response.
 */
export type TimeoutConfiguration = { total_ms: number | null, first_chunk_ms: number | null, chunk_ms: number | null, };
