// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultPart } from "./ToolResultPart";

/**
 * Parts allowed in a tool message.
 */
export type ToolPart = { "type": "tool_result" } & ToolResultPart;
