// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMuxError } from "./AiMuxError";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool call requested by the model.
 */
export type ToolCall = { 
/**
 * Provider-assigned call id.
 */
toolCallId: string, 
/**
 * Tool name.
 */
toolName: string, 
/**
 * Parsed arguments, or the original string when `invalid` is true and the
 * provider input was not valid JSON.
 */
input: JsonValue, 
/**
 * Whether the tool call will be executed by the provider.
 */
providerExecuted?: boolean, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean, 
/**
 * Additional provider-specific metadata associated with this call.
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, 
/**
 * Set when lookup, JSON parsing, or schema validation still failed after
 * the optional repair attempt.
 */
invalid?: boolean, 
/**
 * Typed failure associated with an invalid tool call.
 */
error?: AiMuxError, };
