// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The user's decision for a provider-executed tool approval request.
 */
export type ToolApprovalResponsePart = { approvalId: string, approved: boolean, reason?: string, providerOptions?: { [key in string]: { [key in string]: JsonValue } }, };
