// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Tool result content part.
 */
export type ToolResultPart = { tool_call_id: string, tool_name?: string | null, result: JsonValue, is_error?: boolean | null, preliminary?: boolean | null, dynamic?: boolean | null, provider_options?: { [key in string]: { [key in string]: JsonValue } } | null, };
