// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool call requested by the model.
 */
export type ToolCall = { 
/**
 * Provider-assigned call id.
 */
tool_call_id: string, 
/**
 * Tool name.
 */
tool_name: string, 
/**
 * Arguments as a JSON value (usually an object).
 */
input: JsonValue, 
/**
 * Whether the tool call will be executed by the provider.
 */
provider_executed?: boolean | null, 
/**
 * Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
 */
dynamic?: boolean | null, 
/**
 * Provider-assigned thought signature (e.g. Google Gemini
 * `thoughtSignature`). Must be echoed back verbatim on the follow-up turn
 * when the tool result is sent; thinking models reject the request
 * otherwise.
 */
thought_signature?: string | null, };
