// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePart } from "./FilePart";
import type { TextPart } from "./TextPart";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Content within a tool result.
 */
export type ToolResultContent = { "type": "text" } & TextPart | { "type": "file" } & FilePart | { "type": "custom", providerOptions?: { [key in string]: { [key in string]: JsonValue } }, };
