// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated statistics (RFC-0015 §5.2 — the two hit rates are reported
 * side by side, never merged into a single number).
 */
export type TraceStats = { provider: string, model: string, requests: bigint, inputTokensTotal: bigint, claimedCacheReadTotal: bigint, claimedCacheWriteTotal: bigint, reportedHitRate?: number, clientUpperBoundHitRate?: number, verdictCounts: { [key in string]: bigint }, ttftP50Ms?: bigint, ttftP95Ms?: bigint, errors: bigint, };
