// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionRequest } from "./TranscriptionRequest";
import type { TranscriptionResponse } from "./TranscriptionResponse";
import type { TranscriptionSegment } from "./TranscriptionSegment";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of [`TranscriptionModel::do_generate`].
 *
 * Aligned with V4 `TranscriptionModelV4Result`.
 */
export type TranscriptionResult = { 
/**
 * The complete transcribed text from the audio.
 */
text: string, 
/**
 * Transcript segments with timing information.
 */
segments: Array<TranscriptionSegment>, 
/**
 * The detected language (ISO 639-1 code, e.g. `"en"`), if detected.
 */
language?: string, 
/**
 * The total duration of the audio in seconds, if determined.
 */
durationInSeconds?: number, 
/**
 * Warnings for the call, e.g. unsupported settings.
 */
warnings: Array<Warning>, 
/**
 * Optional request information for telemetry and debugging.
 */
request?: TranscriptionRequest, 
/**
 * Response information for telemetry and debugging.
 */
response: TranscriptionResponse, 
/**
 * Additional provider-specific metadata, keyed by provider name.
 */
providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, };
