// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transcript segment with timing information.
 */
export type TranscriptionSegment = { 
/**
 * The text content of this segment.
 */
text: string, 
/**
 * The start time of this segment in seconds.
 */
start_second: number, 
/**
 * The end time of this segment in seconds.
 */
end_second: number, };
