// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional request information for a transcription call.
 */
export type TranscriptionRequest = { 
/**
 * Raw request HTTP body that was sent (JSON stringified).
 */
body: string | null, };
