// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioInput } from "./AudioInput";
import type { TimeoutConfiguration } from "./TimeoutConfiguration";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Options passed to [`TranscriptionModel::do_generate`].
 *
 * Aligned with V4 `TranscriptionModelV4CallOptions`.
 */
export type TranscriptionCallOptions = { 
/**
 * Audio data to transcribe (raw bytes or a base64-encoded string).
 */
audio: AudioInput, 
/**
 * The IANA media type of the audio data, e.g. `"audio/mp3"`.
 */
mediaType: string, 
/**
 * Additional provider-specific options, keyed by provider name.
 */
providerOptions?: { [key in string]: { [key in string]: JsonValue } }, 
/**
 * Per-call retry override. `None` uses the model default.
 */
maxRetries?: number, 
/**
 * Per-call operation timeout.
 */
timeout?: TimeoutConfiguration, 
/**
 * Additional HTTP headers to send with the request.
 */
headers?: { [key in string]: string }, };
