// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Response information for a transcription call.
 */
export type TranscriptionResponse = { 
/**
 * Timestamp for the start of the generated response (ISO 8601 string).
 */
timestamp?: string, 
/**
 * The ID of the model that was used to generate the response.
 */
modelId?: string, 
/**
 * Response headers.
 */
headers?: { [key in string]: string }, 
/**
 * Response body (opaque JSON).
 */
body?: JsonValue, };
