// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

export type UploadSkillResult = { providerReference: { [key in string]: string }, displayTitle?: string, name?: string, description?: string, latestVersion?: string, providerMetadata?: { [key in string]: { [key in string]: JsonValue } }, warnings: Array<Warning>, };
