// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileBytes } from "./FileBytes";

/**
 * File data accepted by [`Files::upload_file`].
 *
 * The V4 spec restricts upload input to the `data` and `text` variants of
 * `SharedV4FileData` (URLs and provider references are not valid uploads), so
 * this is a dedicated two-variant enum rather than the full [`crate::shared::FileData`].
 */
export type UploadFileData = { "Data": { data: FileBytes, } } | { "Text": { text: string, } };
