// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillFile } from "./SkillFile";
import type { JsonValue } from "./serde_json/JsonValue";

export type UploadSkillCallOptions = { files: Array<SkillFile>, display_title: string | null, provider_options: { [key in string]: { [key in string]: JsonValue } } | null, };
