// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputTokenUsage } from "./InputTokenUsage";
import type { OutputTokenUsage } from "./OutputTokenUsage";

/**
 * Token usage statistics.
 */
export type Usage = { input_tokens: InputTokenUsage, output_tokens: OutputTokenUsage, 
/**
 * Raw usage information from the provider (opaque, provider-specific).
 */
raw?: Record<string, unknown> | null, };
