// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Token usage statistics.
 */
export type Usage = { input_tokens: TokenUsage, output_tokens: TokenUsage, 
/**
 * Raw usage information from the provider (opaque, provider-specific).
 */
raw?: JsonValue | null, };
