// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generated video data: a URL, base64-encoded string, or binary data.
 *
 * Aligned with V4 `VideoModelV4VideoData`. Most providers return URLs due to
 * large file sizes.
 */
export type VideoData = { "type": "url", url: string, mediaType: string, } | { "type": "base64", data: string, mediaType: string, } | { "type": "binary", data: Array<number>, mediaType: string, };
