// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File payload for a [`VideoFile::File`]: base64 string or raw bytes.
 */
export type VideoFileData = string | Array<number>;
