// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireContentPart } from "./WireContentPart";

/**
 * A chat message in the wire format.
 */
export type WireMessage = { 
/**
 * "system" | "user" | "assistant" | "tool".
 */
role: string, content: Array<WireContentPart>, };
