//! `Provider` trait wiring for the vendors' `impl Provider` blocks (RFC-0036 A1).
//!
//! Every vendor answers the three required constructors with a model or with
//! `NoSuchModel { model_type }`, and the optional ones with `Some`/`None`
//! according to what its inherent constructors offer. Checked through
//! `Arc<dyn Provider>` so the trait object is what is exercised.

use std::sync::Arc;

use aimux_core::AiMuxError;
use aimux_core::provider::{Provider, ProviderDiscovery};
use aimux_providers::deepseek::{DeepSeekProviderSettings, create_deepseek};
use aimux_providers::groq::{GroqProviderSettings, create_groq};
use aimux_providers::openai::{OpenAIProviderSettings, create_openai};
use aimux_providers::openai_compatible::{
    OpenAICompatibleProviderSettings, create_openai_compatible,
};
use aimux_providers::{
    GoogleConfig, GoogleProvider, SerperConfig, SerperProvider, VoyageConfig, VoyageProvider,
    provider_discovery, provider_handle,
};

/// Unwrap the `NoSuchModel` model type of a failed `Arc<dyn _>` lookup
/// (`Arc<dyn Model>` is not `Debug`, so `unwrap_err` is unavailable).
fn no_such_model_type<T: ?Sized>(result: Result<Arc<T>, AiMuxError>, id: &str) -> String {
    match result {
        Err(AiMuxError::NoSuchModel {
            model_id,
            model_type,
        }) => {
            assert_eq!(model_id, id);
            model_type
        }
        Err(other) => panic!("expected NoSuchModel, got {other}"),
        Ok(_) => panic!("expected NoSuchModel, got a model"),
    }
}

#[test]
fn openai_offers_every_modality_it_has_constructors_for() {
    let p: Arc<dyn Provider> = Arc::new(create_openai(OpenAIProviderSettings::default()).unwrap());
    assert_eq!(p.language_model("gpt-4o").unwrap().model_id(), "gpt-4o");
    assert!(p.embedding_model("text-embedding-3-small").is_ok());
    assert!(p.image_model("gpt-image-1").is_ok());
    assert!(p.speech_model("tts-1").unwrap().is_ok());
    assert!(p.transcription_model("whisper-1").unwrap().is_ok());
    assert!(p.files().is_some());
    assert!(p.reranking_model("r").is_none());
    assert!(p.video_model("v").is_none());
    assert!(p.search_model("s").is_none());
}

#[test]
fn google_offers_video_and_files() {
    let p: Arc<dyn Provider> = Arc::new(GoogleProvider::new(GoogleConfig::new("k")));
    assert!(p.language_model("gemini-2.0-flash").is_ok());
    assert!(p.embedding_model("text-embedding-004").is_ok());
    assert!(p.image_model("imagen-3.0-generate-002").is_ok());
    assert!(p.video_model("veo-2.0-generate-001").unwrap().is_ok());
    assert!(p.files().is_some());
    assert!(p.speech_model("s").is_none());
}

#[test]
fn embedding_only_vendor_rejects_language_and_image_models() {
    let p: Arc<dyn Provider> = Arc::new(VoyageProvider::new(VoyageConfig::new("k")));
    assert_eq!(
        no_such_model_type(p.language_model("m"), "m"),
        "languageModel"
    );
    assert_eq!(no_such_model_type(p.image_model("m"), "m"), "imageModel");
    assert!(p.embedding_model("voyage-3").is_ok());
    assert!(p.reranking_model("rerank-2.5").unwrap().is_ok());
}

#[test]
fn language_only_vendor_packages_reject_embedding_and_image_models() {
    let vendors: Vec<(&str, Arc<dyn Provider>)> = vec![
        (
            "groq",
            Arc::new(create_groq(GroqProviderSettings::default()).unwrap()),
        ),
        (
            "deepseek",
            Arc::new(create_deepseek(DeepSeekProviderSettings::default()).unwrap()),
        ),
    ];
    for (name, p) in vendors {
        assert_eq!(
            p.language_model("m").unwrap().provider(),
            format!("{name}.chat")
        );
        assert_eq!(
            no_such_model_type(p.embedding_model("e"), "e"),
            "embeddingModel",
            "{name}"
        );
        assert_eq!(
            no_such_model_type(p.image_model("i"), "i"),
            "imageModel",
            "{name}"
        );
        assert!(p.files().is_none(), "{name}");
    }
}

#[test]
fn compatible_provider_offers_chat_embedding_and_image_only() {
    let p: Arc<dyn Provider> = Arc::new(
        create_openai_compatible(OpenAICompatibleProviderSettings {
            name: "local".to_string(),
            base_url: "http://127.0.0.1:8080/v1".to_string(),
            ..Default::default()
        })
        .unwrap(),
    );
    assert_eq!(p.language_model("llama").unwrap().model_id(), "llama");
    assert!(p.embedding_model("e").is_ok());
    assert!(p.image_model("i").is_ok());
    assert!(p.speech_model("s").is_none());
    assert!(p.transcription_model("t").is_none());
    assert!(p.files().is_none());
}

#[test]
fn search_only_vendor_serves_search_and_nothing_else() {
    // `SerperProvider` is generated by `impl_single_modality_provider!` with an
    // optional (non-required) modality.
    let p: Arc<dyn Provider> = Arc::new(SerperProvider::new(SerperConfig::new("k")));
    let search = p.search_model("ignored").unwrap().unwrap();
    assert_eq!(search.provider(), "serper");
    assert_eq!(
        no_such_model_type(p.language_model("m"), "m"),
        "languageModel"
    );
    assert_eq!(
        no_such_model_type(p.embedding_model("m"), "m"),
        "embeddingModel"
    );
    assert_eq!(no_such_model_type(p.image_model("m"), "m"), "imageModel");
    assert!(p.speech_model("m").is_none());
    assert!(p.video_model("m").is_none());
}

#[test]
fn registry_handles_split_models_from_discovery() {
    let handle = provider_handle("groq", Some("k".into()), None).unwrap();
    assert_eq!(
        handle.language_model("llama-3.3-70b").unwrap().provider(),
        "groq.chat"
    );
    // The registry builds an OpenAI-compatible provider: it also serves the
    // other required modalities through the compatible package.
    assert!(handle.embedding_model("e").is_ok());
    let _discovery: Arc<dyn ProviderDiscovery> =
        provider_discovery("groq", Some("k".into()), None).unwrap();
}
