"""Typed wrapper for the aimux Python binding.

This layer sits *on top* of the native PyO3 ``Model.generate_text`` /
``Model.stream_text`` methods (which exchange JSON strings) and exposes a
typed API: inputs and outputs are Pydantic models / native Python objects, so
callers never have to ``json.dumps`` / ``json.loads`` by hand.

The native (raw) JSON-string API in :mod:`aimux` is left untouched — this
module is an additional, optional layer::

    from aimux.wrapper import generate_text, GenerateTextOptions, ModelMessage

The Pydantic models mirror the Rust core types in ``aimux-core/src/`` (see
``bindings/node/src/types/*.ts`` for the field structure generated by ts-rs).
The wire format is the AI SDK's: JSON keys are camelCase and unions are
discriminated by ``type`` (kebab-case values). Python attributes stay
``snake_case``; every model maps them to the camelCase JSON keys through an
alias generator, so both ``tool_call_id`` and ``toolCallId`` validate and
serialization uses the camelCase form.
"""

from __future__ import annotations

import json
from typing import Annotated, Any, Callable, Dict, Iterator, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter
from pydantic.alias_generators import to_camel

from . import _repair
from .aimux import Model

__all__ = [
    # type aliases
    "Role",
    "FinishReasonUnified",
    "ReasoningEffort",
    "MessageContent",
    "ContentPart",
    "Tool",
    "ToolChoice",
    "ResponseFormat",
    "StreamPart",
    "GenerateContent",
    "Source",
    "TextContent",
    "FileData",
    "FileBytes",
    "Warning",
    "AiMuxErrorValue",
    # models
    "InputTokenUsage",
    "OutputTokenUsage",
    "GeneratedFileData",
    "Usage",
    "FinishReason",
    "ResponseMetadata",
    "ToolCall",
    "RawToolCall",
    "ToolCallRepairContext",
    "RepairToolCall",
    "ModelMessage",
    "FunctionTool",
    "FunctionToolInputExample",
    "ProviderTool",
    "TextContentPart",
    "GenerateTextOptions",
    "GenerateTextResult",
    "GenerateObjectResult",
    "StreamTextResultAggregated",
    "GenerateResult",
    "GenerateResponseMetadata",
    "RequestInfo",
    # functions
    "generate_text",
    "stream_text",
    "parse_stream_part",
    # OpenAI Chat Completions output (RFC-0026)
    "ChatCompletion",
    "ChatCompletionChoice",
    "ChatCompletionMessage",
    "ChatCompletionToolCall",
    "ChatCompletionFunction",
    "ChatCompletionUsage",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionDelta",
    "ChatCompletionChunkToolCall",
    "ChatCompletionChunkFunction",
    "PromptTokensDetails",
    "CompletionTokensDetails",
    "generate_text_as_openai",
    "stream_text_as_openai",
]


class _Wire(BaseModel):
    """Base of every aimux model: ``snake_case`` attributes, camelCase JSON keys."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class _Meta(_Wire):
    provider_metadata: Optional[Dict[str, Any]] = None


# ─────────────────────────────────────────────────────────────────────────────
# String-literal type aliases (mirror serde rename rules)
# ─────────────────────────────────────────────────────────────────────────────

#: Message sender. Rust ``Role`` serializes as lowercase strings.
Role = Literal["system", "user", "assistant", "tool"]

#: Unified finish reason. Rust ``FinishReasonUnified`` uses ``kebab-case``.
FinishReasonUnified = Literal[
    "stop", "length", "content-filter", "tool-calls", "error", "other"
]

#: Reasoning effort. Rust ``ReasoningEffort`` uses ``kebab-case``.
ReasoningEffort = Literal[
    "provider-default", "none", "minimal", "low", "medium", "high", "xhigh"
]

#: Opaque provider error value (Rust ``AiMuxError``): an object discriminated
#: by ``name`` (``"AI_APICallError"`` …), left as an arbitrary JSON value.
#: Named ``AiMuxErrorValue`` to avoid confusion with the raised ``AimuxError``
#: exception.
AiMuxErrorValue = Any


# ─────────────────────────────────────────────────────────────────────────────
# Simple struct models
# ─────────────────────────────────────────────────────────────────────────────

class InputTokenUsage(_Wire):
    total: Optional[int] = None
    no_cache: Optional[int] = None
    cache_read: Optional[int] = None
    cache_write: Optional[int] = None


class OutputTokenUsage(_Wire):
    total: Optional[int] = None
    text: Optional[int] = None
    reasoning: Optional[int] = None


class Usage(_Wire):
    """Token usage statistics (Rust ``Usage``)."""

    input_tokens: InputTokenUsage = Field(default_factory=InputTokenUsage)
    output_tokens: OutputTokenUsage = Field(default_factory=OutputTokenUsage)
    raw: Optional[Dict[str, Any]] = None


class FinishReason(_Wire):
    """Why generation stopped (Rust ``FinishReason``)."""

    unified: FinishReasonUnified
    raw: Optional[str] = None


class ResponseMetadata(_Wire):
    """Metadata about the API response (Rust ``ResponseMetadata``)."""

    id: Optional[str] = None
    timestamp: Optional[str] = None
    model_id: Optional[str] = None


class GenerateResponseMetadata(ResponseMetadata):
    """Response metadata with headers and body (Rust ``ResponseInfo``)."""

    headers: Optional[Dict[str, str]] = None
    body: Optional[Any] = None


class ToolCall(_Meta):
    """A tool call requested by the model (Rust ``tool::ToolCall``)."""

    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    invalid: Optional[bool] = None
    error: Optional[AiMuxErrorValue] = None


class RawToolCall(_Meta):
    """A tool call as the provider emitted it (Rust ``RawToolCall``).

    Unlike :class:`ToolCall`, ``input`` is the **raw argument text** — the
    string the model produced, parsed by nobody yet. This is both what a
    repair function is shown and what it returns.
    """

    tool_call_id: str
    tool_name: str
    input: str
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None


# ─────────────────────────────────────────────────────────────────────────────
# Unions: internally tagged by ``type`` (kebab-case), as in the AI SDK.
# ─────────────────────────────────────────────────────────────────────────────

# ── Warning ──────────────────────────────────────────────────────────────────

class _WarningUnsupported(_Wire):
    type: Literal["unsupported"]
    feature: str
    details: Optional[str] = None


class _WarningCompatibility(_Wire):
    type: Literal["compatibility"]
    feature: str
    details: Optional[str] = None


class _WarningDeprecated(_Wire):
    type: Literal["deprecated"]
    setting: str
    message: str


class _WarningOther(_Wire):
    type: Literal["other"]
    message: str


#: A provider warning (Rust ``Warning``).
Warning = Annotated[
    Union[_WarningUnsupported, _WarningCompatibility, _WarningDeprecated, _WarningOther],
    Field(discriminator="type"),
]


# ── FileBytes / FileData ────────────────────────────────────────────────────

#: Raw bytes (a JSON number array) or a base64 string (Rust ``FileBytes``).
FileBytes = Union[List[int], str]


class _FileDataData(_Wire):
    type: Literal["data"]
    data: FileBytes


class _FileDataUrl(_Wire):
    type: Literal["url"]
    url: str
    original_url: Optional[str] = None


class _FileDataReference(_Wire):
    type: Literal["reference"]
    reference: Dict[str, str]


class _FileDataText(_Wire):
    type: Literal["text"]
    text: str


#: File data (Rust ``FileData``).
FileData = Annotated[
    Union[_FileDataData, _FileDataUrl, _FileDataReference, _FileDataText],
    Field(discriminator="type"),
]

#: Data or a URL returned for a generated file (Rust ``GeneratedFileData``).
GeneratedFileData = Annotated[
    Union[_FileDataData, _FileDataUrl], Field(discriminator="type")
]


class GeneratedFile(_Meta):
    data: GeneratedFileData
    media_type: str


# ── Content / stream parts ──────────────────────────────────────────────────

class _UrlSource(_Meta):
    id: str
    source_type: Literal["url"]
    url: str
    title: Optional[str] = None


class _DocumentSource(_Meta):
    id: str
    source_type: Literal["document"]
    media_type: str
    title: str
    filename: Optional[str] = None


Source = Annotated[Union[_UrlSource, _DocumentSource], Field(discriminator="source_type")]


class _ContentUrlSource(_UrlSource):
    type: Literal["source"]


class _ContentDocumentSource(_DocumentSource):
    type: Literal["source"]


_ContentSource = Annotated[
    Union[_ContentUrlSource, _ContentDocumentSource], Field(discriminator="source_type")
]


class _Text(_Meta):
    type: Literal["text"]
    text: str


class _Reasoning(_Meta):
    type: Literal["reasoning"]
    text: str


class _Custom(_Meta):
    type: Literal["custom"]
    kind: str


class _File(GeneratedFile):
    type: Literal["file"]


class _ReasoningFile(GeneratedFile):
    type: Literal["reasoning-file"]


class _ReasoningFileOutput(_Meta):
    type: Literal["reasoning-file"]
    file: GeneratedFile


class _RawToolCallPart(RawToolCall):
    type: Literal["tool-call"]


class _ToolCallPart(ToolCall):
    type: Literal["tool-call"]


class _ToolResultPart(_Meta):
    type: Literal["tool-result"]
    tool_call_id: str
    tool_name: str
    result: Any
    is_error: Optional[bool] = None
    preliminary: Optional[bool] = None
    dynamic: Optional[bool] = None


class _RawApprovalRequest(_Meta):
    type: Literal["tool-approval-request"]
    approval_id: str
    tool_call_id: str


class _ApprovalRequest(_Wire):
    type: Literal["tool-approval-request"]
    approval_id: str
    tool_call: ToolCall
    reason: Optional[str] = None
    is_automatic: Optional[bool] = None
    signature: Optional[str] = None


#: A content item in the raw generation result (Rust ``GenerateContent``).
GenerateContent = Annotated[
    Union[
        _Text,
        _RawToolCallPart,
        _ContentSource,
        _Reasoning,
        _File,
        _ReasoningFile,
        _Custom,
        _RawApprovalRequest,
        _ToolResultPart,
    ],
    Field(discriminator="type"),
]

#: A content item of the user-facing result (Rust ``TextContent``).
TextContent = Annotated[
    Union[
        _Text,
        _ToolCallPart,
        _ContentSource,
        _Reasoning,
        _File,
        _ReasoningFileOutput,
        _Custom,
        _ApprovalRequest,
        _ToolResultPart,
    ],
    Field(discriminator="type"),
]


# ── StreamPart ───────────────────────────────────────────────────────────────

class _SPIdMeta(_Meta):
    id: str


class _SPDelta(_SPIdMeta):
    delta: str


class _SPTextStart(_SPIdMeta):
    type: Literal["text-start"]


class _SPTextDelta(_SPDelta):
    type: Literal["text-delta"]


class _SPTextEnd(_SPIdMeta):
    type: Literal["text-end"]


class _SPStreamStart(_Wire):
    type: Literal["stream-start"]
    warnings: List[Warning]


class _SPFinish(_Meta):
    type: Literal["finish"]
    finish_reason: FinishReason
    usage: Usage


class _SPFinishStep(_SPFinish):
    type: Literal["finish-step"]
    response: GenerateResponseMetadata


class _SPError(_Wire):
    type: Literal["error"]
    error: AiMuxErrorValue


class _SPToolInputStart(_SPIdMeta):
    type: Literal["tool-input-start"]
    tool_name: str
    provider_executed: Optional[bool] = None
    dynamic: Optional[bool] = None
    title: Optional[str] = None


class _SPToolInputDelta(_SPDelta):
    type: Literal["tool-input-delta"]


class _SPToolInputEnd(_SPIdMeta):
    type: Literal["tool-input-end"]


class _SPReasoningStart(_SPIdMeta):
    type: Literal["reasoning-start"]


class _SPReasoningDelta(_SPDelta):
    type: Literal["reasoning-delta"]


class _SPReasoningEnd(_SPIdMeta):
    type: Literal["reasoning-end"]


class _SPRaw(_Wire):
    type: Literal["raw"]
    raw_value: Any


#: A single chunk of the stream returned by ``stream_text`` (Rust
#: ``TextStreamPart``), e.g. ``{"type": "text-delta", "id": ..., "delta": ...}``.
StreamPart = Annotated[
    Union[
        _SPTextStart,
        _SPTextDelta,
        _SPTextEnd,
        _SPStreamStart,
        _SPFinish,
        _SPFinishStep,
        _SPError,
        _SPToolInputStart,
        _SPToolInputDelta,
        _SPToolInputEnd,
        _ToolCallPart,
        _ToolResultPart,
        _File,
        _ReasoningFileOutput,
        _Custom,
        _ApprovalRequest,
        _SPReasoningStart,
        _SPReasoningDelta,
        _SPReasoningEnd,
        _ContentSource,
        _SPRaw,
    ],
    Field(discriminator="type"),
]


# ─────────────────────────────────────────────────────────────────────────────
# ResponseFormat — ``{"type": "text"}`` | ``{"type": "json", schema?, ...}``
# ─────────────────────────────────────────────────────────────────────────────

class _ResponseFormatText(_Wire):
    type: Literal["text"] = "text"


class _ResponseFormatJson(_Wire):
    type: Literal["json"] = "json"
    schema_: Optional[Any] = Field(default=None, alias="schema")
    name: Optional[str] = None
    description: Optional[str] = None


#: How the model should format its response (Rust ``ResponseFormat``).
ResponseFormat = Annotated[
    Union[_ResponseFormatText, _ResponseFormatJson], Field(discriminator="type")
]


# ─────────────────────────────────────────────────────────────────────────────
# Tools
# ─────────────────────────────────────────────────────────────────────────────

class FunctionToolInputExample(_Wire):
    input: Dict[str, Any]


class FunctionTool(_Wire):
    """A user-defined function tool (Rust ``FunctionTool``)."""

    type: Literal["function"] = "function"
    name: str
    description: Optional[str] = None
    input_schema: Any
    strict: Optional[bool] = None
    provider_options: Optional[Dict[str, Any]] = None
    input_examples: Optional[List[FunctionToolInputExample]] = None


class ProviderTool(_Wire):
    """A provider-defined tool (Rust ``ProviderTool``)."""

    type: Literal["provider"] = "provider"
    id: str
    name: str
    args: Dict[str, Any]


Tool = Annotated[
    Union[FunctionTool, ProviderTool],
    Field(discriminator="type"),
]


# ── ContentPart (prompt parts: internal tag ``type``, kebab-case) ───────────

class _PartOptions(_Wire):
    provider_options: Optional[Any] = None


class TextContentPart(_PartOptions):
    """A text content part (Rust ``ContentPart::Text``)."""

    type: Literal["text"] = "text"
    text: str


class _ImageContentPart(_PartOptions):
    type: Literal["image"] = "image"
    image: List[int]
    media_type: str


class _FileContentPart(_PartOptions):
    type: Literal["file"] = "file"
    data: List[int]
    media_type: str
    filename: Optional[str] = None


class _FileBase64ContentPart(_PartOptions):
    type: Literal["file-base64"] = "file-base64"
    data: str
    media_type: str
    filename: Optional[str] = None


class _FileUrlContentPart(_PartOptions):
    type: Literal["file-url"] = "file-url"
    url: str
    media_type: str


class _FileReferenceContentPart(_PartOptions):
    type: Literal["file-reference"] = "file-reference"
    media_type: str
    reference: Any
    filename: Optional[str] = None


class _ReasoningContentPart(_PartOptions):
    type: Literal["reasoning"] = "reasoning"
    text: str
    signature: Optional[str] = None


class _ToolCallContentPart(_PartOptions):
    type: Literal["tool-call"] = "tool-call"
    tool_call_id: str
    tool_name: str
    input: Any
    provider_executed: Optional[bool] = None


class _ToolResultContentPart(_PartOptions):
    """``output`` is a ``{"type": "text" | "json" | "execution-denied" |
    "error-text" | "error-json" | "content", ...}`` object."""

    type: Literal["tool-result"] = "tool-result"
    tool_call_id: str
    tool_name: str
    output: Any


class _CustomContentPart(_PartOptions):
    type: Literal["custom"] = "custom"
    kind: str


class _ReasoningFileContentPart(_PartOptions):
    type: Literal["reasoning-file"] = "reasoning-file"
    data: GeneratedFileData
    media_type: str


class _ToolApprovalRequestContentPart(_Wire):
    type: Literal["tool-approval-request"] = "tool-approval-request"
    approval_id: str
    tool_call_id: str
    reason: Optional[str] = None
    is_automatic: Optional[bool] = None
    signature: Optional[str] = None
    input_schema_input: Optional[Any] = None


ContentPart = Annotated[
    Union[
        TextContentPart,
        _ImageContentPart,
        _FileContentPart,
        _FileBase64ContentPart,
        _FileUrlContentPart,
        _FileReferenceContentPart,
        _ReasoningContentPart,
        _ToolCallContentPart,
        _ToolResultContentPart,
        _CustomContentPart,
        _ReasoningFileContentPart,
        _ToolApprovalRequestContentPart,
    ],
    Field(discriminator="type"),
]


#: Message body: a plain string or multi-part content (Rust ``MessageContent``).
MessageContent = Union[str, List[ContentPart]]


# ─────────────────────────────────────────────────────────────────────────────
# ToolChoice — ``"auto" | "none" | "required" | {"type": "tool", "toolName": ...}``
# ─────────────────────────────────────────────────────────────────────────────

class ToolChoiceTool(_Wire):
    """The ``tool`` tool-choice variant (forces a specific tool)."""

    type: Literal["tool"] = "tool"
    tool_name: str


ToolChoice = Union[Literal["auto", "none", "required"], ToolChoiceTool]


# ─────────────────────────────────────────────────────────────────────────────
# User-facing prompt / message models
# ─────────────────────────────────────────────────────────────────────────────

class ModelMessage(_Wire):
    """A single user-facing chat message (Rust ``ModelMessage``).

    ``content`` is untagged on the wire: a bare string or a list of content
    parts.
    """

    role: Role
    content: MessageContent


# ─────────────────────────────────────────────────────────────────────────────
# Options + results
# ─────────────────────────────────────────────────────────────────────────────

class TimeoutConfiguration(_Wire):
    """Per-call timeout configuration (Rust ``TimeoutConfiguration``).

    All values are milliseconds; ``None`` disables the corresponding limit.
    """

    total_ms: Optional[int] = None
    step_ms: Optional[int] = None
    first_chunk_ms: Optional[int] = None
    chunk_ms: Optional[int] = None


class ToolCallRepairContext(_Wire):
    """What a ``repair_tool_call`` function is given (RFC-0035).

    Mirrors the AI SDK ``repairToolCall`` argument: the offending call with its
    raw argument text, the error it failed with, the schema it was checked
    against, and the tools, messages and instructions the call was generated
    with.
    """

    tool_call: RawToolCall
    error: AiMuxErrorValue
    input_schema: Any = None
    tools: List[Tool] = Field(default_factory=list)
    messages: List[ModelMessage] = Field(default_factory=list)
    instructions: Optional[str] = None


#: A ``repair_tool_call`` function: return a replacement :class:`RawToolCall`
#: to re-validate, or ``None`` to leave the call invalid. Raising marks the
#: repair failed, with the exception message as the cause.
RepairToolCall = Callable[[ToolCallRepairContext], Optional[RawToolCall]]


class GenerateTextOptions(_Wire):
    """User-facing options for ``generate_text`` / ``stream_text``.

    Mirrors Rust ``GenerateTextOptions``. All fields are optional; unset fields
    default to ``None`` (Rust treats absent / ``null`` as ``None``).

    Invalid tool calls arrive with ``invalid``/``error`` set on the tool call;
    set :attr:`repair_tool_call` to get a shot at fixing them.
    """

    max_output_tokens: Optional[int] = None
    temperature: Optional[float] = None
    stop_sequences: Optional[List[str]] = None
    top_p: Optional[float] = None
    top_k: Optional[float] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    response_format: Optional[ResponseFormat] = None
    seed: Optional[int] = None
    tools: Optional[List[Tool]] = None
    tool_choice: Optional[ToolChoice] = None
    headers: Optional[Dict[str, str]] = None
    provider_options: Optional[Dict[str, Any]] = None
    reasoning: Optional[ReasoningEffort] = None
    instructions: Optional[str] = None
    max_retries: Optional[int] = None
    session_id: Optional[str] = None
    """Session identifier (RFC-0024): groups consecutive calls into a session.

    Explicit values take precedence; when ``None`` and the optional session
    inferer is enabled (``init_session_infer(True)`` or ``AIMUX_SESSION_INFER=1``),
    one may be inferred from prompt-prefix continuation.
    """
    timeout: Optional[TimeoutConfiguration] = None
    include_raw_chunks: Optional[bool] = None

    repair_tool_call: Optional[RepairToolCall] = Field(default=None, exclude=True)
    """One-shot repair for tool calls that came back ``invalid`` (RFC-0035).

    Called once per invalid call, after generation and before the result is
    decoded, with a :class:`ToolCallRepairContext`. Return a
    :class:`RawToolCall` to re-validate, or ``None`` to leave the call as it
    is; raising marks the repair failed and the call keeps its original error
    with the exception message as the cause.

    It runs outside the native call and may itself call back into aimux (e.g.
    ask a model to rewrite the arguments). A call generated without ``tools``
    is never repaired. ``generate_text_as_openai`` repairs the native result
    before converting it; ``stream_text_as_openai`` does not reflect repair
    (its tool-argument deltas are the provider's text, as in the AI SDK).
    Only an exception raised by this function means "failed"; returning
    something other than a :class:`RawToolCall` or ``None`` is an error.
    Host-only: it is never serialized into the options sent across the
    boundary.
    """


class RequestInfo(_Wire):
    body: Optional[Any] = None


class GenerateResult(_Wire):
    """Raw provider result (Rust ``GenerateResult``), exposed via ``raw``."""

    content: List[GenerateContent]
    finish_reason: FinishReason
    usage: Usage
    warnings: List[Warning]
    provider_metadata: Optional[Any] = None
    request: Optional[RequestInfo] = None
    response: Optional[GenerateResponseMetadata] = None


class GenerateTextResult(_Wire):
    """Result of ``generate_text`` (user-facing, Rust ``GenerateTextResult``)."""

    content: List[TextContent] = Field(default_factory=list)
    text: str
    tool_calls: List[ToolCall]
    finish_reason: FinishReason
    usage: Usage
    warnings: List[Warning]
    raw: GenerateResult
    # M7: top-level aggregation fields.
    # reasoning/files use weak types (Dict) — use raw.content for
    # full typing; response_messages reuses ModelMessage for next-turn prompt.
    reasoning: List[Dict[str, Any]] = Field(default_factory=list)
    reasoning_text: str = ""
    sources: List[Source] = Field(default_factory=list)
    files: List[Dict[str, Any]] = Field(default_factory=list)
    response_messages: List[ModelMessage] = Field(default_factory=list)
    # M12: raw provider-specific finish reason string (e.g. "stop", "end_turn").
    raw_finish_reason: Optional[str] = None
    # Provider-specific metadata (e.g. Anthropic cache info). Mirrored from
    # raw.provider_metadata for top-level convenience. Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    request: RequestInfo = Field(default_factory=RequestInfo)
    response: GenerateResponseMetadata = Field(default_factory=GenerateResponseMetadata)
    # Total token usage across all steps. In single-step mode (aimux's
    # default), equals usage. Provided for AI SDK parity.
    total_usage: Usage = Field(default_factory=Usage)


class GenerateObjectResult(_Wire):
    """Result of ``generate_object`` (user-facing, M12, Rust
    ``GenerateObjectResult``). The parsed JSON object plus convenience fields
    from the underlying ``generate_text`` call.
    """

    # `object` is an arbitrary JSON value — weak type (Any).
    object: Any
    finish_reason: FinishReason
    raw_finish_reason: Optional[str] = None
    usage: Usage
    warnings: List[Warning] = Field(default_factory=list)
    # Concatenated reasoning text (if the model produced reasoning/thinking).
    reasoning: Optional[str] = None
    # Provider-specific metadata (e.g. Anthropic cache info). Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    # Response metadata (id, timestamp, model_id).
    response: ResponseMetadata = Field(default_factory=ResponseMetadata)
    raw: GenerateTextResult


class StreamTextResultAggregated(_Wire):
    """Aggregated result of ``stream_text().consume()`` (M11, Rust
    ``StreamTextResultAggregated``). Mirrors ``GenerateTextResult``'s
    user-facing fields (without ``raw``, since streaming has no
    ``GenerateResult`` equivalent).
    """

    content: List[TextContent] = Field(default_factory=list)
    text: str = ""
    # reasoning/files use weak types (Dict) — same strategy as
    # GenerateTextResult.
    reasoning: List[Dict[str, Any]] = Field(default_factory=list)
    reasoning_text: str = ""
    tool_calls: List[ToolCall] = Field(default_factory=list)
    sources: List[Source] = Field(default_factory=list)
    files: List[Dict[str, Any]] = Field(default_factory=list)
    finish_reason: FinishReason
    raw_finish_reason: Optional[str] = None
    usage: Usage = Usage()
    # Total token usage across all steps. In single-step mode (aimux's
    # default), equals usage. Provided for AI SDK parity.
    total_usage: Usage = Field(default_factory=Usage)
    warnings: List[Warning] = Field(default_factory=list)
    # Provider-specific metadata from the Finish chunk. Weak type (Dict).
    provider_metadata: Optional[Dict[str, Any]] = None
    request: RequestInfo = Field(default_factory=RequestInfo)
    response: GenerateResponseMetadata = Field(default_factory=GenerateResponseMetadata)
    response_messages: List[ModelMessage] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# OpenAI Chat Completions output (RFC-0026)
#
# Mirrors ``aimux_core::openai_output``. Field names match the serde wire
# format; ``skip_serializing_if = "Option::is_none"`` maps to ``Optional[...] =
# None``. The Rust field ``tool_type`` serializes as ``"type"`` (via
# ``#[serde(rename = "type")]``), so the pydantic field is named ``type``
# directly (same convention as ``FunctionTool`` above).
# ─────────────────────────────────────────────────────────────────────────────

class ChatCompletionFunction(BaseModel):
    """Function payload of a tool call (Rust ``ChatCompletionFunction``)."""

    name: str
    arguments: str


class ChatCompletionToolCall(BaseModel):
    """A tool call in an assistant message (Rust ``ChatCompletionToolCall``)."""

    id: str
    type: str
    function: ChatCompletionFunction


class ChatCompletionMessage(BaseModel):
    """The assistant message in a ChatCompletion (Rust ``ChatCompletionMessage``)."""

    role: str
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChatCompletionToolCall]] = None
    annotations: Optional[List[Any]] = None


class ChatCompletionChoice(BaseModel):
    """A single choice in a ChatCompletion (Rust ``ChatCompletionChoice``)."""

    index: int
    message: ChatCompletionMessage
    finish_reason: Optional[str] = None
    logprobs: Optional[Any] = None


class PromptTokensDetails(BaseModel):
    """Prompt token breakdown (Rust ``PromptTokensDetails``)."""

    cached_tokens: int
    cache_write_tokens: Optional[int] = None


class CompletionTokensDetails(BaseModel):
    """Completion token breakdown (Rust ``CompletionTokensDetails``)."""

    reasoning_tokens: Optional[int] = None


class ChatCompletionUsage(BaseModel):
    """Token usage for a Chat Completion (Rust ``ChatCompletionUsage``)."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_tokens_details: Optional[PromptTokensDetails] = None
    completion_tokens_details: Optional[CompletionTokensDetails] = None


class ChatCompletion(BaseModel):
    """A complete OpenAI Chat Completion response (Rust ``ChatCompletion``)."""

    id: str
    object: str
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: ChatCompletionUsage
    system_fingerprint: Optional[str] = None


class ChatCompletionChunkFunction(BaseModel):
    """Function payload of a chunk tool call (Rust ``ChatCompletionChunkFunction``)."""

    name: Optional[str] = None
    arguments: Optional[str] = None


class ChatCompletionChunkToolCall(BaseModel):
    """A tool-call delta in a streaming chunk (Rust ``ChatCompletionChunkToolCall``)."""

    index: int
    id: Optional[str] = None
    type: Optional[str] = None
    function: ChatCompletionChunkFunction


class ChatCompletionDelta(BaseModel):
    """The delta payload of a streaming chunk (Rust ``ChatCompletionDelta``)."""

    role: Optional[str] = None
    content: Optional[str] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[ChatCompletionChunkToolCall]] = None


class ChatCompletionChunkChoice(BaseModel):
    """A single choice in a streaming chunk (Rust ``ChatCompletionChunkChoice``)."""

    index: int
    delta: ChatCompletionDelta
    finish_reason: Optional[str] = None
    logprobs: Optional[Any] = None


class ChatCompletionChunk(BaseModel):
    """A single OpenAI Chat Completion streaming chunk (Rust ``ChatCompletionChunk``)."""

    id: str
    object: str
    created: int
    model: str
    choices: List[ChatCompletionChunkChoice]
    usage: Optional[ChatCompletionUsage] = None


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

Prompt = Union[str, List[ModelMessage], List[Dict[str, Any]]]


def _prompt_to_json(prompt: Prompt) -> str:
    """Build the JSON prompt string expected by the native layer.

    A bare string is emitted as a JSON string (→ ``ModelPrompt::Text``). A list
    of messages is wrapped as ``{"prompt": [...]}`` (→ ``ModelPrompt::Messages``).
    ``ModelMessage`` instances are serialized with ``mode="json"`` so nested
    models become JSON primitives.
    """
    if isinstance(prompt, str):
        return json.dumps(prompt)
    if not isinstance(prompt, list):
        raise TypeError(
            f"prompt must be str or list of messages, got {type(prompt).__name__}"
        )
    msgs = [
        m.model_dump(mode="json", exclude_none=True, by_alias=True)
        if isinstance(m, BaseModel)
        else m
        for m in prompt
    ]
    return json.dumps({"prompt": msgs})


def _opts_to_json(options: Optional[GenerateTextOptions]) -> Optional[str]:
    """Serialize options to the JSON string expected by the native layer."""
    if options is None:
        return None
    if not isinstance(options, GenerateTextOptions):
        raise TypeError(
            "options must be a GenerateTextOptions instance, got "
            f"{type(options).__name__}"
        )
    # ``exclude_none`` mirrors Rust's ``#[serde(skip_serializing_if = "Option::is_none")]``
    # on the inner struct fields, producing clean payloads (absent == None for the
    # Rust deserializer). ``by_alias`` emits the ``schema`` field of the JSON
    # response-format body and the camelCase keys of every model.
    return options.model_dump_json(exclude_none=True, by_alias=True)


def _repair_adapter(options: Optional[GenerateTextOptions]):
    """Bridge the typed repair function to the JSON-level loop in ``_repair``."""
    fn = options.repair_tool_call if options is not None else None
    if fn is None:
        return None

    def adapter(context: dict) -> Optional[dict]:
        typed = ToolCallRepairContext.model_validate(context)
        replacement = _repair.run_hook(fn, typed)
        if replacement is None:
            return None
        return replacement.model_dump(mode="json", exclude_none=True, by_alias=True)

    return adapter


# ─────────────────────────────────────────────────────────────────────────────
# Typed API
# ─────────────────────────────────────────────────────────────────────────────

def generate_text(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> GenerateTextResult:
    """Generate text (non-streaming), returning a typed result.

    Args:
        model: A model instance from ``openai()``, ``anthropic()``, etc.
        prompt: A string or a list of ``ModelMessage`` / message dicts.
        options: Optional typed generation options.

    Returns:
        A :class:`GenerateTextResult` with ``.text``, ``.tool_calls``,
        ``.finish_reason``, ``.usage``, ``.warnings`` and ``.raw``.
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    result_json = model.generate_text(prompt_json, opts_json)
    repair = _repair_adapter(options)
    if repair is not None:
        result_json = _repair.repair_result(result_json, prompt_json, opts_json, repair)
    return GenerateTextResult.model_validate_json(result_json)


def stream_text(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> Iterator[dict]:
    """Stream text from a model, yielding parsed ``StreamPart`` dicts.

    Each yielded item is the dict form produced by the Rust core, tagged by
    ``type``, e.g. ``{"type": "text-delta", "id": ..., "delta": ...}``. For
    typed access, pass the dict through :func:`parse_stream_part`.

    Usage::

        for part in stream_text(model, "Write a haiku about Rust."):
            if part["type"] == "text-delta":
                print(part["delta"], end="")
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    repair = _repair_adapter(options)
    for part_json in model.stream_text(prompt_json, opts_json):
        if repair is not None:
            part_json = _repair.repair_stream_part(
                part_json, prompt_json, opts_json, repair
            )
        yield json.loads(part_json)


_STREAM_PART = TypeAdapter(StreamPart)


def parse_stream_part(part: dict) -> BaseModel:
    """Validate a yielded stream-part dict into its typed model (see ``StreamPart``)."""
    return _STREAM_PART.validate_python(part)


def generate_text_as_openai(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> ChatCompletion:
    """Generate text and return the result as an OpenAI Chat Completion.

    Identical to :func:`generate_text` except the result is a
    :class:`ChatCompletion` (OpenAI ``chat.completion`` object) rather than a
    :class:`GenerateTextResult`. Works with any provider.

    Args:
        model: A model instance from ``openai()``, ``anthropic()``, etc.
        prompt: A string or a list of ``ModelMessage`` / message dicts.
        options: Optional typed generation options.

    Returns:
        A :class:`ChatCompletion` with ``.id``, ``.choices``, ``.usage``, …

    With ``options.repair_tool_call``, invalid calls are repaired on the
    native result first and the completion is converted from it, so its
    ``tool_calls`` carry the repaired arguments.
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    return ChatCompletion.model_validate_json(
        _repair.generate_openai_with_repair(model, prompt_json, opts_json, _repair_adapter(options))
    )


def stream_text_as_openai(
    model: Model,
    prompt: Prompt,
    options: Optional[GenerateTextOptions] = None,
) -> Iterator[ChatCompletionChunk]:
    """Stream text as OpenAI Chat Completion chunks.

    Identical to :func:`stream_text` except each yielded item is a typed
    :class:`ChatCompletionChunk` (OpenAI ``chat.completion.chunk`` object).
    Works with any provider.

    Stream options (``include_usage``, ``include_reasoning``) are read from
    ``options.provider_options.openai.stream_options`` (both default to ``True``).

    Usage::

        for chunk in stream_text_as_openai(model, "Write a haiku about Rust."):
            if chunk.choices and chunk.choices[0].delta.content:
                print(chunk.choices[0].delta.content, end="")
    """
    prompt_json = _prompt_to_json(prompt)
    opts_json = _opts_to_json(options)
    for chunk_json in model.stream_text_as_openai(prompt_json, opts_json):
        yield ChatCompletionChunk.model_validate_json(chunk_json)
