// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified error type for all aimux operations.
 */
export type AiMuxError = { "Provider": string } | { "Http": string } | { "Json": string } | { "Stream": string } | { "Tool": string } | { "InvalidArgument": string } | { "InvalidPrompt": string } | { "RateLimited": { retry_after_ms: bigint, } } | { "Auth": string } | { "ModelNotFound": string } | { "Unsupported": string } | { "NoSuchModel": string } | { "UnknownProvider": string } | { "ApiCall": string } | { "Timeout": string } | "Aborted" | { "Other": string };
