// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AspectRatio } from "./AspectRatio";
import type { ImageFile } from "./ImageFile";
import type { Size } from "./Size";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Options passed to [`ImageModel::do_generate`].
 *
 * Aligned with V4 `ImageModelV4CallOptions`.
 */
export type ImageCallOptions = { 
/**
 * Prompt for the image generation. `None` for operations (e.g. upscaling)
 * that do not require a prompt.
 */
prompt: string | null, 
/**
 * Number of images to generate.
 */
n: number, 
/**
 * Size of the images, in `{width}x{height}` format.
 * `None` uses the provider's default size.
 */
size: Size | null, 
/**
 * Aspect ratio of the images, in `{width}:{height}` format.
 * `None` uses the provider's default aspect ratio.
 */
aspect_ratio: AspectRatio | null, 
/**
 * Seed for deterministic generation. `None` uses the provider's default.
 */
seed: bigint | null, 
/**
 * Images for image editing or variation generation.
 */
files: Array<ImageFile> | null, 
/**
 * Mask image for inpainting operations.
 */
mask: ImageFile | null, 
/**
 * Additional provider-specific options, keyed by provider name.
 */
provider_options: { [key in string]: JsonValue }, 
/**
 * Additional HTTP headers to send with the request.
 */
headers: { [key in string]: string } | null, };
