// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioData } from "./AudioData";
import type { SpeechRequest } from "./SpeechRequest";
import type { SpeechResponse } from "./SpeechResponse";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of [`SpeechModel::do_generate`].
 *
 * Aligned with V4 `SpeechModelV4Result`.
 */
export type SpeechResult = { 
/**
 * Generated audio (base64 string or binary data).
 */
audio: AudioData, 
/**
 * Warnings for the call, e.g. unsupported settings.
 */
warnings: Array<Warning>, 
/**
 * Optional request information for telemetry and debugging.
 */
request: SpeechRequest | null, 
/**
 * Response information for telemetry and debugging.
 */
response: SpeechResponse, 
/**
 * Additional provider-specific metadata, keyed by provider name.
 */
provider_metadata: { [key in string]: JsonValue } | null, };
