// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of executing a tool call, to be sent back to the model.
 */
export type ToolResult = { 
/**
 * Must match the corresponding `ToolCall::tool_call_id`.
 */
tool_call_id: string, 
/**
 * The tool's output (usually a JSON-serializable value or plain text).
 */
output: JsonValue, 
/**
 * Whether the result is an error or error message.
 */
is_error?: boolean | null, 
/**
 * Whether the result is preliminary (replaces prior, e.g. image previews).
 */
preliminary?: boolean | null, };
