// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role a frame image plays in video generation.
 *
 * Aligned with V4 `VideoModelV4FrameType`.
 */
export type VideoFrameType = "FirstFrame" | "LastFrame";
