// aimux — Unified LLM service layer for Node.js (flagship binding)
//
// This wrapper layer parses JSON strings from the native layer into typed
// objects, using TypeScript types auto-generated by ts-rs from the Rust core.

export { Model, StreamTextGenerator } from './index.js'
export { openai, anthropic, deepseek } from './index.js'

// Re-export the ts-rs generated types as the public type surface.
export type {
  GenerateTextOptions,
  GenerateTextResult,
  StreamPart,
  ToolChoice,
  Tool,
  FunctionTool,
  ToolCall,
  ToolResult,
  Usage,
  FinishReason,
  Warning,
  Role,
  ModelMessage,
  MessageContent,
  ContentPart,
  ResponseFormat,
  ReasoningEffort,
  AiMuxError,
} from './types.js'

/**
 * Generate text (non-streaming). Returns a typed result.
 *
 * @param model - A model instance from `openai()`, `anthropic()`, etc.
 * @param prompt - A string or an array of messages.
 * @param options - Optional generation options.
 */
export async function generateText(
  model: Model,
  prompt: string | ModelMessage[],
  options?: GenerateTextOptions,
): Promise<GenerateTextResult> {
  const promptJson = JSON.stringify(
    typeof prompt === 'string' ? prompt : { prompt },
  )
  const optsJson = options ? JSON.stringify(options) : undefined
  const resultJson = await model.generateText(
    typeof prompt === 'string' ? JSON.stringify(prompt) : JSON.stringify({ prompt }),
    optsJson,
  )
  return JSON.parse(resultJson) as GenerateTextResult
}

/**
 * Stream text from a model. Returns an async iterator of typed StreamParts.
 *
 * @example
 * ```ts
 * const model = await openai(process.env.OPENAI_API_KEY!, 'gpt-4o')
 * for await (const part of streamText(model, 'Write a haiku about Rust.')) {
 *   if (part.type === 'text-delta') {
 *     process.stdout.write(part.textDelta)
 *   }
 * }
 * ```
 */
export async function* streamText(
  model: Model,
  prompt: string | ModelMessage[],
  options?: GenerateTextOptions,
): AsyncGenerator<StreamPart> {
  const promptJson =
    typeof prompt === 'string' ? JSON.stringify(prompt) : JSON.stringify({ prompt })
  const optsJson = options ? JSON.stringify(options) : undefined
  const gen = model.streamText(promptJson, optsJson)
  for await (const json of gen) {
    yield JSON.parse(json) as StreamPart
  }
}
