/* auto-generated by NAPI-RS */
/* eslint-disable */
declare global {
  interface __NapiRsAsyncGenerator<TOwner, T, TReturn, TNext> {
    next(...[value]: [] | [TNext]): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    return(...[value]: [] | [TReturn]): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    throw(exception?: unknown): globalThis.Promise<globalThis.IteratorResult<T, TReturn | undefined>>
    [globalThis.Symbol.asyncIterator](): this
  }
}

export declare class Model {
  /**
   * Generate text (non-streaming).
   *
   * `prompt` — a JSON string: bare prompt (`"text"` or `[{...}]`) or `{"prompt": ...}`.
   * `options` — optional JSON-serialized `GenerateTextOptions`.
   * Returns a JSON-serialized `GenerateTextResult`.
   */
  generateText(prompt: string, options?: string | undefined | null): Promise<string>
  /**
   * Stream text from the model.
   *
   * Returns an `AsyncGenerator<string>` yielding `StreamPart` JSON strings.
   * Use `for await (const part of model.streamText(...))` to consume.
   */
  streamText(prompt: string, options?: string | undefined | null): Promise<AsyncGenerator<string>>
}

/**
 * AsyncGenerator that yields StreamPart JSON strings.
 *
 * The stream is started eagerly in `stream_text()` — a tokio task drives
 * the Rust Stream and sends each chunk through a channel. `next()` simply
 * receives from the channel.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class StreamTextGenerator {

  [globalThis.Symbol.asyncIterator](): globalThis.__NapiRsAsyncGenerator<StreamTextGenerator, string, void, undefined>
}

/** Create an Anthropic model instance. */
export declare function anthropic(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<Model>

/** Create a DeepSeek model instance. */
export declare function deepseek(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<Model>

/** Create an OpenAI model instance. */
export declare function openai(apiKey: string, modelId: string, baseUrl?: string | undefined | null): Promise<Model>
