//! Auto-generated registry of OpenAI-compatible thin-wrapper providers.
//!
//! Each line invokes [`declare_openai_compat_provider!`] to expand a
//! `<Type>Config` + `<Type>Provider` pair behaviourally identical to the
//! hand-written wrappers it replaces (RFC-0012 §3.1). The whole module is
//! re-exported from the crate root via `pub use openai_compat_registry::*;`
//! in `lib.rs` (RFC-0012 §3.2).
//!
//! Each provider is one declaration on a single line — the intended manifest
//! format (RFC-0012 §3.1): adding a compatible vendor is a one-line edit here,
//! with no new file and no `lib.rs` change.

use crate::openai::OpenAICompatProfile;
use crate::openai_compat::declare_openai_compat_provider;

declare_openai_compat_provider!(
    abacus,
    AbacusConfig,
    AbacusProvider,
    "Abacus",
    "https://routellm.abacus.ai/v1",
    "ABACUS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    abliteration_ai,
    AbliterationAiConfig,
    AbliterationAiProvider,
    "Abliteration AI",
    "https://api.abliteration.ai/v1",
    "ABLIT_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ai21,
    Ai21Config,
    Ai21Provider,
    "AI21 Labs",
    "https://api.ai21.ai/v1",
    "AI21_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ai302,
    Ai302Config,
    Ai302Provider,
    "302.AI",
    "https://api.302.ai/v1",
    "AI302_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ai_router,
    AiRouterConfig,
    AiRouterProvider,
    "AI-ROUTER",
    "https://api.ai-router.dev/v1",
    "AI_ROUTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aiand,
    AiandConfig,
    AiandProvider,
    "AIand",
    "https://api.aiand.com/v1",
    "AIAND_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aibadgr,
    AibadgrConfig,
    AibadgrProvider,
    "AI Badgr",
    "https://api.aibadgr.com/v1",
    "AIBADGR_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aigc2d,
    Aigc2dConfig,
    Aigc2dProvider,
    "AIGC2D",
    "https://api.aigc2d.com/v1",
    "AIGC2D_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aihubmix,
    AihubmixConfig,
    AihubmixProvider,
    "AIHubMix",
    "https://aihubmix.com/v1",
    "AIHUBMIX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ails,
    AilsConfig,
    AilsProvider,
    "AILS",
    "https://api.caipacity.com/v1",
    "AILS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aiml,
    AimlConfig,
    AimlProvider,
    "AI/ML API",
    "https://api.aimlapi.com/v1",
    "AIML_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    aki_io,
    AkiIoConfig,
    AkiIoProvider,
    "AKI.IO",
    "https://aki.io/openai/v1",
    "AKI_IO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    albert,
    AlbertConfig,
    AlbertProvider,
    "Albert",
    "https://api.albert.ai/v1",
    "ALBERT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    alibaba,
    AlibabaConfig,
    AlibabaProvider,
    "Alibaba Cloud (DashScope)",
    "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    "ALIBABA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    alibaba_coding_plan,
    AlibabaCodingPlanConfig,
    AlibabaCodingPlanProvider,
    "Alibaba Coding Plan",
    "https://coding-intl.dashscope.aliyuncs.com/v1",
    "ALIBABA_CODING_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    alibaba_coding_plan_cn,
    AlibabaCodingPlanCnConfig,
    AlibabaCodingPlanCnProvider,
    "Alibaba Coding Plan (China)",
    "https://coding.dashscope.aliyuncs.com/v1",
    "ALIBABA_CODING_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    alibaba_token_plan,
    AlibabaTokenPlanConfig,
    AlibabaTokenPlanProvider,
    "Alibaba Token Plan",
    "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    "ALIBABA_TOKEN_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    alibaba_token_plan_cn,
    AlibabaTokenPlanCnConfig,
    AlibabaTokenPlanCnProvider,
    "Alibaba Token Plan (China)",
    "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    "ALIBABA_TOKEN_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ambient,
    AmbientConfig,
    AmbientProvider,
    "Ambient",
    "https://api.ambient.xyz/v1",
    "AMBIENT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    anyapi,
    AnyapiConfig,
    AnyapiProvider,
    "AnyAPI",
    "https://api.anyapi.ai/v1",
    "ANYAPI_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    anyscale,
    AnyscaleConfig,
    AnyscaleProvider,
    "Anyscale",
    "https://api.endpoints.anyscale.com/v1",
    "ANYSCALE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    apertis,
    ApertisConfig,
    ApertisProvider,
    "Apertis",
    "https://api.stima.tech/v1",
    "STIMA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    api2d,
    Api2dConfig,
    Api2dProvider,
    "API2D",
    "https://oa.api2d.net/v1",
    "API2D_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    api2gpt,
    Api2gptConfig,
    Api2gptProvider,
    "API2GPT",
    "https://api.api2gpt.com/v1",
    "API2GPT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    apiserpent,
    ApiserpentConfig,
    ApiserpentProvider,
    "API Serpent",
    "https://api.apiserpent.com/v1",
    "APISERPENT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    atlascloud,
    AtlascloudConfig,
    AtlascloudProvider,
    "AtlasCloud",
    "https://api.atlascloud.com/v1",
    "ATLASCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    atomic_chat,
    AtomicChatConfig,
    AtomicChatProvider,
    "Atomic Chat",
    "http://127.0.0.1:1337/v1",
    "ATOMIC_CHAT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    auriko,
    AurikoConfig,
    AurikoProvider,
    "Auriko",
    "https://api.auriko.ai/v1",
    "AURIKO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    azure_ai,
    AzureAiConfig,
    AzureAiProvider,
    "Azure AI",
    "https://models.inference.ai.azure.com",
    "AZURE_AI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    baichuan,
    BaichuanConfig,
    BaichuanProvider,
    "Baichuan AI",
    "https://api.baichuan-ai.com/v1",
    "BAICHUAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    baidu,
    BaiduConfig,
    BaiduProvider,
    "Baidu (文心/ERNIE)",
    "https://qianfan.baidubce.com/v2",
    "BAIDU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    baidu_v2,
    BaiduV2Config,
    BaiduV2Provider,
    "BaiduV2",
    "https://qianfan.baidubce.com/v2",
    "QIANFAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    bailing,
    BailingConfig,
    BailingProvider,
    "Bailing",
    "https://api.ant-ling.com/v1",
    "BAILING_API_TOKEN",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    baseten,
    BasetenConfig,
    BasetenProvider,
    "Baseten",
    "https://inference.baseten.co/v1",
    "BASETEN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    berget,
    BergetConfig,
    BergetProvider,
    "Berget.AI",
    "https://api.berget.ai/v1",
    "BERGET_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    bigmodel,
    BigmodelConfig,
    BigmodelProvider,
    "BigModel (智谱)",
    "https://open.bigmodel.cn/api/paas/v4",
    "BIGMODEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    blueclaw,
    BlueclawConfig,
    BlueclawProvider,
    "Blue Claw",
    "https://openai.blueclaw.network/v1",
    "BLUECLAW_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    bytedance,
    ByteDanceConfig,
    ByteDanceProvider,
    "ByteDance",
    "https://ark.cn-beijing.volces.com/api/v3",
    "ARK_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    byteplus,
    ByteplusConfig,
    ByteplusProvider,
    "BytePlus (Volcano)",
    "https://ark.bytepluses.com/api/v3",
    "BYTEPLUS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    bytez,
    BytezConfig,
    BytezProvider,
    "Bytez",
    "https://api.bytez.com/v2",
    "BYTEZ_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    canopywave,
    CanopywaveConfig,
    CanopywaveProvider,
    "Canopywave",
    "https://api.canopywave.com/v1",
    "CANOPYWAVE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cerebras,
    CerebrasConfig,
    CerebrasProvider,
    "Cerebras",
    "https://api.cerebras.ai/v1",
    "CEREBRAS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    chatgpt,
    ChatgptConfig,
    ChatgptProvider,
    "ChatGPT (订阅)",
    "https://chatgpt.com/backend-api/codex",
    "CHATGPT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cherryin,
    CherryinConfig,
    CherryinProvider,
    "cherryin",
    "https://open.cherryin.net",
    "CHERRYIN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    chutes,
    ChutesConfig,
    ChutesProvider,
    "Chutes",
    "https://llm.chutes.ai/v1",
    "CHUTES_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    clarifai,
    ClarifaiConfig,
    ClarifaiProvider,
    "Clarifai",
    "https://api.clarifai.com/v2/ext/openai/v1",
    "CLARIFAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    claudinio,
    ClaudinioConfig,
    ClaudinioProvider,
    "Claudinio",
    "https://api.claudin.io",
    "CLAUDINIO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cline_pass,
    ClinePassConfig,
    ClinePassProvider,
    "Cline",
    "https://api.cline.bot/v1",
    "CLINE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    closeai,
    CloseaiConfig,
    CloseaiProvider,
    "CloseAI",
    "https://api.closeai-proxy.xyz/v1",
    "CLOSEAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cloudferro_sherlock,
    CloudferroSherlockConfig,
    CloudferroSherlockProvider,
    "CloudFerro Sherlock",
    "https://api-sherlock.cloudferro.com/openai/v1",
    "CLOUDFERRO_SHERLOCK_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cloudflare,
    CloudflareConfig,
    CloudflareProvider,
    "Cloudflare",
    "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1",
    "CLOUDFLARE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cloudflare_workers_ai,
    CloudflareWorkersAiConfig,
    CloudflareWorkersAiProvider,
    "Cloudflare Workers AI",
    "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1",
    "CLOUDFLARE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    codestral,
    CodestralConfig,
    CodestralProvider,
    "Codestral (Mistral)",
    "https://api.mistral.ai/v1",
    "CODESTRAL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cometapi,
    CometapiConfig,
    CometapiProvider,
    "CometAPI",
    "https://api.cometapi.com/v1",
    "COMETAPI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    commandcode,
    CommandcodeConfig,
    CommandcodeProvider,
    "CommandCode",
    "https://api.commandcode.com/v1",
    "COMMANDCODE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    compactifai,
    CompactifaiConfig,
    CompactifaiProvider,
    "CompactifAI",
    "https://api.compactif.ai/v1",
    "COMPACTIFAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    copilot,
    CopilotConfig,
    CopilotProvider,
    "GitHub Copilot",
    "https://api.githubcopilot.com",
    "COPILOT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    cortecs,
    CortecsConfig,
    CortecsProvider,
    "Cortecs",
    "https://api.cortecs.ai/v1/",
    "CORTECS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    coze,
    CozeConfig,
    CozeProvider,
    "Coze (扣子)",
    "https://api.coze.cn/v1",
    "COZE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    crof,
    CrofConfig,
    CrofProvider,
    "CrofAI",
    "https://crof.ai/v1",
    "CROF_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    crossmodel,
    CrossmodelConfig,
    CrossmodelProvider,
    "CrossModel",
    "https://api.crossmodel.ai/v1",
    "CROSSMODEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    crusoe,
    CrusoeConfig,
    CrusoeProvider,
    "Crusoe",
    "https://api.inference.crusoecloud.com/v1",
    "CRUSOE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    daoxe,
    DaoxeConfig,
    DaoxeProvider,
    "DaoXE",
    "https://daoxe.com/v1",
    "DAOXE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    darkbloom,
    DarkbloomConfig,
    DarkbloomProvider,
    "Darkbloom",
    "https://api.darkbloom.dev/v1",
    "DARKBLOOM_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    databricks,
    DatabricksConfig,
    DatabricksProvider,
    "Databricks",
    "https://databricks.com/serving-endpoints",
    "DATABRICKS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    datarobot,
    DatarobotConfig,
    DatarobotProvider,
    "DataRobot",
    "https://app.datarobot.com/api/v2",
    "DATAROBOT_API_TOKEN",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    deepbricks,
    DeepbricksConfig,
    DeepbricksProvider,
    "DeepBricks",
    "https://api.deepbricks.ai/v1",
    "DEEPBRICKS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    deepinfra,
    DeepInfraConfig,
    DeepInfraProvider,
    "DeepInfra",
    "https://api.deepinfra.com/v1/openai",
    "DEEPINFRA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    deepseek,
    DeepSeekConfig,
    DeepSeekProvider,
    "DeepSeek",
    "https://api.deepseek.com/v1",
    "DEEPSEEK_API_KEY",
    OpenAICompatProfile::deepseek()
);
declare_openai_compat_provider!(
    digitalocean,
    DigitaloceanConfig,
    DigitaloceanProvider,
    "DigitalOcean",
    "https://inference.do-ai.run",
    "DIGITALOCEAN_ACCESS_TOKEN",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    dinference,
    DinferenceConfig,
    DinferenceProvider,
    "DInference",
    "https://api.dinference.com/v1",
    "DINFERENCE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    doubao,
    DoubaoConfig,
    DoubaoProvider,
    "Doubao",
    "https://ark.cn-beijing.volces.com/api/v3",
    "ARK_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    doubleword,
    DoublewordConfig,
    DoublewordProvider,
    "Doubleword",
    "https://api.doubleword.ai/v1",
    "DOUBLEWORD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    drun,
    DrunConfig,
    DrunProvider,
    "D.Run (China)",
    "https://chat.d.run/v1",
    "DRUN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ebcloud,
    EbcloudConfig,
    EbcloudProvider,
    "EBCloud",
    "https://maas-api.ebcloud.com/v1",
    "EBCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    embercloud,
    EmbercloudConfig,
    EmbercloudProvider,
    "Embercloud",
    "https://api.embercloud.com/v1",
    "EMBERCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    empiriolabs,
    EmpiriolabsConfig,
    EmpiriolabsProvider,
    "EmpirioLabs AI",
    "https://api.empiriolabs.ai/v1",
    "EMPIRIOLABS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    evroc,
    EvrocConfig,
    EvrocProvider,
    "evroc",
    "https://models.think.evroc.com/v1",
    "EVROC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    fastcrw,
    FastcrwConfig,
    FastcrwProvider,
    "FastCRW",
    "https://fastcrw.com/api/v1",
    "FASTCRW_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    fastgpt,
    FastgptConfig,
    FastgptProvider,
    "FastGPT",
    "https://api.fastgpt.in/v1",
    "FASTGPT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    fastrouter,
    FastrouterConfig,
    FastrouterProvider,
    "FastRouter",
    "https://api.fastrouter.ai/v1",
    "FASTROUTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    featherless_ai,
    FeatherlessAiConfig,
    FeatherlessAiProvider,
    "Featherless AI",
    "https://api.featherless.ai/v1",
    "FEATHERLESS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    firepass,
    FirepassConfig,
    FirepassProvider,
    "Fireworks (Firepass)",
    "https://api.fireworks.ai/inference/v1（OpenAI",
    "FIREWORKS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    fireworks,
    FireworksConfig,
    FireworksProvider,
    "Fireworks",
    "https://api.fireworks.ai/inference/v1",
    "FIREWORKS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    freemodel,
    FreemodelConfig,
    FreemodelProvider,
    "FreeModel",
    "client.chat.completions.create",
    "FREEMODEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    friendliai,
    FriendliAIConfig,
    FriendliAIProvider,
    "FriendliAI",
    "https://inference.friendli.ai/v1",
    "FRIENDLIAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    frogbot,
    FrogbotConfig,
    FrogbotProvider,
    "FrogBot",
    "https://app.frogbot.ai/api/v1",
    "FROGBOT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    galadriel,
    GaladrielConfig,
    GaladrielProvider,
    "Galadriel",
    "https://api.galadriel.com/v1",
    "GALADRIEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gdc,
    GdcConfig,
    GdcProvider,
    "GDC",
    "https://api.gdc.ai/v1",
    "GDC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gigachat,
    GigaChatConfig,
    GigaChatProvider,
    "GigaChat (Sberbank)",
    "https://gigachat.devices.sberbank.ru/api/v1",
    "GIGACHAT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    github,
    GithubConfig,
    GithubProvider,
    "GitHub Models",
    "https://models.inference.ai.azure.com",
    "GITHUB_TOKEN",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gmi,
    GmiConfig,
    GmiProvider,
    "GMI",
    "https://api.gmi-serving.com/v1（与",
    "GMI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gmicloud,
    GmicloudConfig,
    GmicloudProvider,
    "GMI Cloud",
    "https://api.gmi-serving.com/v1",
    "GMI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gonka24,
    Gonka24Config,
    Gonka24Provider,
    "Gonka24",
    "https://api.gonka24.com/v1",
    "GONKA24_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    gradient_ai,
    GradientAiConfig,
    GradientAiProvider,
    "Gradient AI",
    "https://inference.do-ai.run/v1",
    "GRADIENT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    groq,
    GroqConfig,
    GroqProvider,
    "Groq",
    "https://api.groq.com/openai/v1",
    "GROQ_API_KEY",
    OpenAICompatProfile::groq()
);
declare_openai_compat_provider!(
    helicone,
    HeliconeConfig,
    HeliconeProvider,
    "Helicone",
    "https://api.helicone.ai/v1",
    "HELICONE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    heroku,
    HerokuConfig,
    HerokuProvider,
    "Heroku AI",
    "https://api.heroku.com/inference/v1",
    "HEROKU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    hetzner,
    HetznerConfig,
    HetznerProvider,
    "Hetzner",
    "https://inference.hetzner.com/api/v1",
    "HETZNER_VLLM_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    hosted_vllm,
    HostedVllmConfig,
    HostedVllmProvider,
    "Hosted vLLM",
    "https://hosted-vllm-api.com/v1",
    "HOSTED_VLLM_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    hpc_ai,
    HpcAiConfig,
    HpcAiProvider,
    "HPC-AI",
    "https://api.hpc-ai.com/inference/v1",
    "INFERENCE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    hyperbolic,
    HyperbolicConfig,
    HyperbolicProvider,
    "Hyperbolic",
    "https://api.hyperbolic.xyz/v1",
    "HYPERBOLIC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    iflowcn,
    IflowcnConfig,
    IflowcnProvider,
    "iFlow",
    "https://apis.iflow.cn/v1（chat",
    "IFLOW_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    inception,
    InceptionConfig,
    InceptionProvider,
    "Inception Labs",
    "https://api.inceptionlabs.ai/v1",
    "INCEPTION_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    inceptron,
    InceptronConfig,
    InceptronProvider,
    "Inceptron",
    "https://api.inceptron.io/v1",
    "INCEPTRON_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    inference_net,
    InferenceNetConfig,
    InferenceNetProvider,
    "Inference.net",
    "https://api.inference.net/v1",
    "INFERENCE_NET_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    inferx,
    InferxConfig,
    InferxProvider,
    "InferX",
    "https://model.inferx.net/v1",
    "INFERX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    infinity,
    InfinityConfig,
    InfinityProvider,
    "Infinity AI",
    "https://infinity.ai/api/v1",
    "INFINITY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    io_net,
    IoNetConfig,
    IoNetProvider,
    "IO.NET",
    "https://api.intelligence.io.solutions/api/v1",
    "IOINTELLIGENCE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    jiekou,
    JiekouConfig,
    JiekouProvider,
    "Jiekou.AI",
    "https://api.highwayapi.ai/openai",
    "JIEKOU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kenari,
    KenariConfig,
    KenariProvider,
    "Kenari",
    "https://kenari.id/v1",
    "KENARI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kilo,
    KiloConfig,
    KiloProvider,
    "Kilo",
    "https://api.kilo.ai/v1",
    "KILO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kimi,
    KimiConfig,
    KimiProvider,
    "Kimi",
    "https://api.moonshot.ai/v1",
    "MOONSHOT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kimi_for_coding,
    KimiForCodingConfig,
    KimiForCodingProvider,
    "Kimi For Coding",
    "https://api.kimi.com/coding/v1",
    "KIMI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kiro,
    KiroConfig,
    KiroProvider,
    "Kiro",
    "https://api.kiro.dev/v1",
    "KIRO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kluster_ai,
    KlusterAiConfig,
    KlusterAiProvider,
    "Kluster AI",
    "https://api.kluster.ai/v1",
    "KLUSTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    krutrim,
    KrutrimConfig,
    KrutrimProvider,
    "Krutrim",
    "https://api.krutrim.ai/v1",
    "KRUTRIM_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    kuae_cloud_coding_plan,
    KuaeCloudCodingPlanConfig,
    KuaeCloudCodingPlanProvider,
    "KUAE Cloud Coding Plan",
    "https://coding-plan-endpoint.kuaecloud.net/v1",
    "KUAE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lambda_ai,
    LambdaAiConfig,
    LambdaAiProvider,
    "Lambda AI",
    "https://api.lambda.ai/v1",
    "LAMBDA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lemonade,
    LemonadeConfig,
    LemonadeProvider,
    "Lemonade",
    "http://localhost:13305/v1",
    "LEMONADE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lemonfox_ai,
    LemonfoxAiConfig,
    LemonfoxAiProvider,
    "Lemonfox AI",
    "https://api.lemonfox.ai/v1",
    "LEMONFOX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    libertai,
    LibertaiConfig,
    LibertaiProvider,
    "Libertai",
    "https://api.libertai.io/v1",
    "LIBERTAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lilac,
    LilacConfig,
    LilacProvider,
    "Lilac",
    "https://api.getlilac.com/v1",
    "LILAC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lingyiwanwu,
    LingyiwanwuConfig,
    LingyiwanwuProvider,
    "Lingyiwanwu (零一万物)",
    "https://api.lingyiwanwu.com/v1",
    "LINGYIWANWU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    llama,
    LlamaConfig,
    LlamaProvider,
    "Llama",
    "https://api.llama.com/compat/v1/",
    "LLAMA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    llamagate,
    LlamagateConfig,
    LlamagateProvider,
    "Llamagate",
    "https://api.llamagate.dev/v1",
    "LLAMAGATE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    llmgateway,
    LlmgatewayConfig,
    LlmgatewayProvider,
    "LLM Gateway",
    "https://api.llmgateway.io/v1",
    "LLM_GATEWAY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    llmtr,
    LlmtrConfig,
    LlmtrProvider,
    "LLMTR",
    "https://llmtr.com/v1",
    "LLMTR_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    longcat,
    LongcatConfig,
    LongcatProvider,
    "LongCat",
    "https://api.longcat.chat/v1",
    "LONGCAT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lucidquery,
    LucidqueryConfig,
    LucidqueryProvider,
    "LucidQuery",
    "https://api.lucidquery.com/v1",
    "LUCIDQUERY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    lynkr,
    LynkrConfig,
    LynkrProvider,
    "Lynkr",
    "http://localhost:8081/v1",
    "LYNKR_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    matterai,
    MatteraiConfig,
    MatteraiProvider,
    "Matter AI",
    "https://api.matterai.com/v1",
    "MATTERAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    meganova,
    MeganovaConfig,
    MeganovaProvider,
    "Meganova",
    "https://api.meganova.ai/v1",
    "MEGANOVA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    merge_gateway,
    MergeGatewayConfig,
    MergeGatewayProvider,
    "Merge Gateway",
    "https://api-gateway.merge.dev/v1/openai",
    "MERGE_GATEWAY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    meta,
    MetaConfig,
    MetaProvider,
    "Meta",
    "https://api.meta.ai/v1",
    "MODEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    meta_llama,
    MetaLlamaConfig,
    MetaLlamaProvider,
    "Meta Llama API",
    "https://api.llama.com/compat/v1",
    "LLAMA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    mimo,
    MimoConfig,
    MimoProvider,
    "Mimo",
    "https://api.xiaomimimo.com/v1",
    "MIMO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    minimax,
    MinimaxConfig,
    MinimaxProvider,
    "MiniMax",
    "https://api.minimax.io/v1",
    "MINIMAX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    minimax_cn,
    MinimaxCnConfig,
    MinimaxCnProvider,
    "MiniMax (minimaxi.com)",
    "https://api.minimaxi.com/v1",
    "MINIMAX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    minimax_cn_coding_plan,
    MinimaxCnCodingPlanConfig,
    MinimaxCnCodingPlanProvider,
    "MiniMax Token Plan (minimaxi.com)",
    "https://api.minimaxi.com/v1",
    "MINIMAX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    minimax_coding_plan,
    MinimaxCodingPlanConfig,
    MinimaxCodingPlanProvider,
    "MiniMax Token Plan (minimax.io)",
    "https://api.minimax.io/anthropic/v1",
    "MINIMAX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    mira,
    MiraConfig,
    MiraProvider,
    "Mira",
    "https://api.mira.so/v1",
    "MIRA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    mixlayer,
    MixlayerConfig,
    MixlayerProvider,
    "Mixlayer",
    "https://models.mixlayer.ai/v1",
    "MIXLAYER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    moark,
    MoarkConfig,
    MoarkProvider,
    "Moark",
    "https://api.moark.com/v1",
    "MOARK_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    modal,
    ModalConfig,
    ModalProvider,
    "Modal",
    "https://modal.com/v1",
    "MODAL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    model_oracle_ai,
    ModelOracleAiConfig,
    ModelOracleAiProvider,
    "Model Oracle AI",
    "https://api.modeloracle.com/api/v1",
    "MODEL_ORACLE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    modelscope,
    ModelscopeConfig,
    ModelscopeProvider,
    "ModelScope",
    "https://api-inference.modelscope.cn/v1",
    "MODELSCOPE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    moonshotai,
    MoonshotAIConfig,
    MoonshotAIProvider,
    "Moonshot AI",
    "https://api.moonshot.cn/v1",
    "MOONSHOT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    moonshotai_cn,
    MoonshotaiCnConfig,
    MoonshotaiCnProvider,
    "Moonshot AI (China)",
    "https://api.moonshot.cn/anthropic/v1（Anthropic",
    "MOONSHOT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    morph,
    MorphConfig,
    MorphProvider,
    "Morph LLM",
    "https://api.morphllm.com/v1",
    "MORPH_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nanogpt,
    NanogptConfig,
    NanogptProvider,
    "NanoGPT",
    "https://api.nanogpt.com/v1",
    "NANOGPT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ncompass,
    NcompassConfig,
    NcompassProvider,
    "Ncompass",
    "https://api.ncompass.tech/v1",
    "NCOMPASS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nearai,
    NearaiConfig,
    NearaiProvider,
    "NEAR AI Cloud",
    "https://cloud-api.near.ai/v1",
    "NEARAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nebius,
    NebiusConfig,
    NebiusProvider,
    "Nebius AI",
    "https://api.studio.nebius.ai/v1",
    "NEBIUS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    neon,
    NeonConfig,
    NeonProvider,
    "Neon",
    "https://<branch-host>/v1",
    "NEON_AI_GATEWAY_TOKEN",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    neuralwatt,
    NeuralwattConfig,
    NeuralwattProvider,
    "Neuralwatt",
    "https://api.neuralwatt.com/v1",
    "NEURALWATT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nextbit,
    NextbitConfig,
    NextbitProvider,
    "NextBit",
    "https://api.nextbit.ai/v1",
    "NEXTBIT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nlp_cloud,
    NlpCloudConfig,
    NlpCloudProvider,
    "NLP Cloud",
    "https://api.nlpcloud.io/v1",
    "NLPCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nous_research,
    NousResearchConfig,
    NousResearchProvider,
    "Nous Research",
    "https://api.nousresearch.com/v1",
    "NOUS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    novita,
    NovitaConfig,
    NovitaProvider,
    "Novita AI",
    "https://api.novita.ai/v1",
    "NOVITA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nscale,
    NscaleConfig,
    NscaleProvider,
    "Nscale",
    "https://inference.api.nscale.com/v1",
    "NSCALE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    nvidia_nim,
    NvidiaNimConfig,
    NvidiaNimProvider,
    "NVIDIA NIM",
    "https://integrate.api.nvidia.com/v1",
    "NVIDIA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    oci,
    OciConfig,
    OciProvider,
    "OCI",
    "https://inference.generativeai.${region}.oci.oraclecloud.com/openai/v1",
    "OCI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ofox,
    OfoxConfig,
    OfoxProvider,
    "OfoxAI",
    "https://api.ofox.ai/v1",
    "OFOX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ohmygpt,
    OhmygptConfig,
    OhmygptProvider,
    "OhMyGPT",
    "https://api.ohmygpt.com/v1",
    "OHMYGPT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ollama_cloud,
    OllamaCloudConfig,
    OllamaCloudProvider,
    "Ollama Cloud",
    "https://api.ollama.com/v1",
    "OLLAMA_CLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    openaimax,
    OpenaimaxConfig,
    OpenaimaxProvider,
    "OpenAIMax",
    "https://api.openaimax.com/v1",
    "OPENAIMAX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    openaisb,
    OpenaisbConfig,
    OpenaisbProvider,
    "OpenAI-SB",
    "https://api.openaisb.com/v1",
    "OPENAISB_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    opencode,
    OpencodeConfig,
    OpencodeProvider,
    "OpenCode Zen",
    "opencode_zen.rs",
    "OPENCODE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    opencode_go,
    OpencodeGoConfig,
    OpencodeGoProvider,
    "OpenCode Go",
    "https://api.opencode.dev/v1",
    "OPENCODE_GO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    opencode_zen,
    OpencodeZenConfig,
    OpencodeZenProvider,
    "OpenCode Zen",
    "https://api.opencode.zen/v1",
    "OPENCODE_ZEN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    orcarouter,
    OrcarouterConfig,
    OrcarouterProvider,
    "OrcaRouter",
    "https://api.orcarouter.com/v1",
    "ORCAROUTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ovhcloud,
    OvhcloudConfig,
    OvhcloudProvider,
    "OVHcloud AI",
    "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    "OVHCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    parasail,
    ParasailConfig,
    ParasailProvider,
    "Parasail",
    "https://api.parasail.io/v1",
    "PARASAIL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    perfxcloud,
    PerfxcloudConfig,
    PerfxcloudProvider,
    "PerfXCloud",
    "https://api.perfxcloud.com/v1",
    "PERFXCLOUD_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    perplexity,
    PerplexityConfig,
    PerplexityProvider,
    "Perplexity",
    "https://api.perplexity.ai",
    "PERPLEXITY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    perplexity_agent,
    PerplexityAgentConfig,
    PerplexityAgentProvider,
    "Perplexity Agent",
    "https://api.perplexity.ai/v1",
    "PERPLEXITY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    petals,
    PetalsConfig,
    PetalsProvider,
    "Petals",
    "https://api.petals.dev/v1",
    "PETALS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    pinstripes,
    PinstripesConfig,
    PinstripesProvider,
    "Pinstripes",
    "https://api.pinstripes.io/v1",
    "PINSTRIPES_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    pioneer,
    PioneerConfig,
    PioneerProvider,
    "Pioneer",
    "https://api.pioneer.ai/v1",
    "PIONEER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    poe,
    PoeConfig,
    PoeProvider,
    "Poe",
    "https://api.poe.com/v1",
    "POE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    poolside,
    PoolsideConfig,
    PoolsideProvider,
    "Poolside",
    "https://inference.poolside.ai/v1",
    "POOLSIDE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    portkey,
    PortkeyConfig,
    PortkeyProvider,
    "Portkey Gateway",
    "https://api.portkey.ai/v1",
    "PORTKEY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    ppinfra,
    PpinfraConfig,
    PpinfraProvider,
    "PPInfra（PPIO 派欧云）",
    "https://api.ppio.com/openai",
    "PPIO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    predibase,
    PredibaseConfig,
    PredibaseProvider,
    "Predibase",
    "https://serving.app.predibase.com/v1",
    "PREDIBASE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    privatemode_ai,
    PrivatemodeAiConfig,
    PrivatemodeAiProvider,
    "Privatemode AI",
    "http://localhost:8080/v1",
    "PRIVATEMODE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    publicai,
    PublicaiConfig,
    PublicaiProvider,
    "Publicai",
    "https://platform.publicai.co/v1",
    "PUBLICAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    qihang_ai,
    QihangAiConfig,
    QihangAiProvider,
    "QiHang（启航 AI）",
    "https://api.qhaigc.net/v1",
    "QIHANG_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    qihoo360,
    Qihoo360Config,
    Qihoo360Provider,
    "360 AI",
    "https://api.360.cn/v1",
    "AI360_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    qiniu_ai,
    QiniuAiConfig,
    QiniuAiProvider,
    "Qiniu AI",
    "https://api.qiniu.com/v1",
    "QINIU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    regolo_ai,
    RegoloAiConfig,
    RegoloAiProvider,
    "Regolo AI",
    "https://api.regolo.ai/v1",
    "REGOLO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    reka_ai,
    RekaAiConfig,
    RekaAiProvider,
    "Reka AI",
    "https://api.reka.ai/v1",
    "REKA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    requesty,
    RequestyConfig,
    RequestyProvider,
    "Requesty",
    "https://api.requesty.ai/v1",
    "REQUESTY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    reve,
    ReveConfig,
    ReveProvider,
    "Reve",
    "https://api.reve.ai/v1",
    "REVE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    routing_run,
    RoutingRunConfig,
    RoutingRunProvider,
    "routing.run",
    "https://api.routing.run/v1",
    "ROUTING_RUN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    sakana,
    SakanaConfig,
    SakanaProvider,
    "Sakana AI",
    "https://api.sakana.ai/v1",
    "SAKANA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    sambanova,
    SambaNovaConfig,
    SambaNovaProvider,
    "SambaNova",
    "https://api.sambanova.ai/v1",
    "SAMBANOVA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    sarvam,
    SarvamConfig,
    SarvamProvider,
    "Sarvam AI",
    "https://api.sarvam.ai/v1",
    "SARVAM_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    scaleway,
    ScalewayConfig,
    ScalewayProvider,
    "Scaleway AI",
    "https://api.scaleway.ai/v1",
    "SCALEWAY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    scx_ai,
    ScxAiConfig,
    ScxAiProvider,
    "SCX AI",
    "https://api.scx.ai/v1",
    "SCX_AI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    siliconflow,
    SiliconFlowConfig,
    SiliconFlowProvider,
    "SiliconFlow",
    "https://api.siliconflow.cn/v1",
    "SILICONFLOW_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    snowflake,
    SnowflakeConfig,
    SnowflakeProvider,
    "Snowflake",
    "https://<account-identifier>.snowflakecomputing.com/api/v2/cortex/v1",
    "SNOWFLAKE_PAT",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    snowflake_cortex,
    SnowflakeCortexConfig,
    SnowflakeCortexProvider,
    "Snowflake Cortex",
    "https://<account-identifier>.snowflakecomputing.com/api/v2/cortex/v1",
    "SNOWFLAKE_CORTEX_PAT",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    stackit,
    StackitConfig,
    StackitProvider,
    "STACKIT",
    "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
    "STACKIT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    stepfun,
    StepfunConfig,
    StepfunProvider,
    "StepFun (阶跃星辰)",
    "https://api.stepfun.com/v1",
    "STEPFUN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    stepfun_ai_step_plan,
    StepfunAiStepPlanConfig,
    StepfunAiStepPlanProvider,
    "StepFun Step Plan (Global)",
    "https://api.stepfun.ai/step_plan/v1",
    "STEPFUN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    stepfun_step_plan,
    StepfunStepPlanConfig,
    StepfunStepPlanProvider,
    "StepFun Step Plan (China)",
    "https://api.stepfun.com/step_plan/v1",
    "STEPFUN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    subconscious,
    SubconsciousConfig,
    SubconsciousProvider,
    "Subconscious",
    "https://api.subconscious.dev/v1",
    "SUBCONSCIOUS_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    submodel,
    SubmodelConfig,
    SubmodelProvider,
    "SubModel",
    "https://api.submodel.com/v1",
    "SUBMODEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    synthetic,
    SyntheticConfig,
    SyntheticProvider,
    "Synthetic",
    "https://api.synthetic.new/openai/v1",
    "SYNTHETIC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent,
    TencentConfig,
    TencentProvider,
    "Tencent (混元/Hunyuan)",
    "https://api.hunyuan.cloud.tencent.com/v1",
    "TENCENT_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_coding_plan,
    TencentCodingPlanConfig,
    TencentCodingPlanProvider,
    "Tencent Coding Plan (China)",
    "https://api.lkeap.cloud.tencent.com/coding/v3",
    "TENCENT_CODING_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_token_plan,
    TencentTokenPlanConfig,
    TencentTokenPlanProvider,
    "Tencent Token Plan",
    "https://api.lkeap.cloud.tencent.com/plan/v3",
    "TENCENT_TOKEN_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_token_plan_enterprise_auto,
    TencentTokenPlanEnterpriseAutoConfig,
    TencentTokenPlanEnterpriseAutoProvider,
    "腾讯云 Token Plan / Token Plan 企业版轻享套餐",
    "https://tokenhub.tencentmaas.com/plan/v3",
    "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_token_plan_enterprise_pro,
    TencentTokenPlanEnterpriseProConfig,
    TencentTokenPlanEnterpriseProProvider,
    "腾讯云 Token Plan / Token Plan 企业版专业套餐",
    "https://tokenhub.tencentmaas.com/plan/v3",
    "TENCENT_TOKEN_PLAN_ENTERPRISE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_token_plan_general_personal,
    TencentTokenPlanGeneralPersonalConfig,
    TencentTokenPlanGeneralPersonalProvider,
    "腾讯云 Token Plan / 通用 Token Plan（个人版）",
    "https://api.lkeap.cloud.tencent.com/plan/v3",
    "TENCENT_TOKEN_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_token_plan_hy_personal,
    TencentTokenPlanHyPersonalConfig,
    TencentTokenPlanHyPersonalProvider,
    "腾讯云 Token Plan / Hy Token Plan（个人版）",
    "https://api.lkeap.cloud.tencent.com/plan/v3",
    "TENCENT_TOKEN_PLAN_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tencent_tokenhub,
    TencentTokenhubConfig,
    TencentTokenhubProvider,
    "Tencent TokenHub",
    "https://tokenhub.tencentmaas.com/v1",
    "TENCENT_TOKENHUB_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tensormesh,
    TensormeshConfig,
    TensormeshProvider,
    "Tensormesh",
    "https://serverless.tensormesh.ai",
    "YOUR_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    the_grid_ai,
    TheGridAiConfig,
    TheGridAiProvider,
    "The Grid AI",
    "https://thegrid.ai/docs",
    "THEGRIDAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    thinkingmachines,
    ThinkingmachinesConfig,
    ThinkingmachinesProvider,
    "Thinking Machines",
    "https://tinker.thinkingmachines.dev/services/tinker-prod/oai/api/v1",
    "TINKER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tinfoil,
    TinfoilConfig,
    TinfoilProvider,
    "Tinfoil",
    "https://inference.tinfoil.sh/v1",
    "TINFOIL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    togetherai,
    TogetherAIConfig,
    TogetherAIProvider,
    "Together AI",
    "https://api.together.xyz/v1",
    "TOGETHER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tokenflux,
    TokenfluxConfig,
    TokenfluxProvider,
    "Tokenflux",
    "https://tokenflux.ai/v1",
    "TOKENFLUX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tokenpony,
    TokenponyConfig,
    TokenponyProvider,
    "TokenPony",
    "https://api.tokenpony.com/v1",
    "TOKENPONY_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    trustedrouter,
    TrustedrouterConfig,
    TrustedrouterProvider,
    "TrustedRouter",
    "https://api.trustedrouter.com/v1",
    "TRUSTEDROUTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    tundra,
    TundraConfig,
    TundraProvider,
    "Tundra",
    "https://api.tundra.ai/v1",
    "TUNDRA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    umans_ai,
    UmansAiConfig,
    UmansAiProvider,
    "Umans AI",
    "https://api.code.umans.ai/v1",
    "UMANS_AI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    unorouter,
    UnorouterConfig,
    UnorouterProvider,
    "UnoRouter",
    "https://unorouter.com/en",
    "UNOROUTER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    upstage,
    UpstageConfig,
    UpstageProvider,
    "Upstage",
    "https://api.upstage.ai/v1",
    "UPSTAGE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    v0,
    V0Config,
    V0Provider,
    "v0 (Vercel)",
    "https://api.v0.dev/v1",
    "V0_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    venice,
    VeniceConfig,
    VeniceProvider,
    "Venice",
    "https://api.venice.ai/api/v1",
    "VENICE_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    vercel,
    VercelConfig,
    VercelProvider,
    "Vercel",
    "https://api.v0.dev/v1",
    "VERCEL_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    vivgrid,
    VivgridConfig,
    VivgridProvider,
    "Vivgrid",
    "https://api.vivgrid.com/v1",
    "VIVGRID_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    volc_engine,
    VolcEngineConfig,
    VolcEngineProvider,
    "VolcEngine",
    "https://ark.cn-beijing.volces.com",
    "ARK_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    vultr,
    VultrConfig,
    VultrProvider,
    "Vultr",
    "https://api.vultrinference.com/v1",
    "VULTR_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    wafer,
    WaferConfig,
    WaferProvider,
    "Wafer",
    "https://api.wafer.ai/v1",
    "WAFER_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    wandb,
    WandbConfig,
    WandbProvider,
    "Weights & Biases",
    "https://api.inference.wandb.ai/v1",
    "WANDB_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xiaomi_token_plan_ams,
    XiaomiTokenPlanAmsConfig,
    XiaomiTokenPlanAmsProvider,
    "Xiaomi Token Plan (Europe)",
    "https://token-plan-ams.xiaomimimo.com/v1",
    "MIMO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xiaomi_token_plan_cn,
    XiaomiTokenPlanCnConfig,
    XiaomiTokenPlanCnProvider,
    "Xiaomi Token Plan (China)",
    "https://token-plan-cn.xiaomimimo.com/v1",
    "MIMO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xiaomi_token_plan_sgp,
    XiaomiTokenPlanSgpConfig,
    XiaomiTokenPlanSgpProvider,
    "Xiaomi Token Plan (Singapore)",
    "https://token-plan-sgp.xiaomimimo.com/v1",
    "MIMO_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xiaomimimo,
    XiaomimimoConfig,
    XiaomimimoProvider,
    "Xiaomi MiMo",
    "https://mimo.xiaomi.com/v1",
    "XIAOMI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xpersona,
    XpersonaConfig,
    XpersonaProvider,
    "Xpersona",
    "/v1",
    "XPERSONA_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    xunfei,
    XunfeiConfig,
    XunfeiProvider,
    "Xunfei",
    "https://spark-api-open.xf-yun.com/v1",
    "XUNFEI_API_PASSWORD",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zai,
    ZaiConfig,
    ZaiProvider,
    "Zai",
    "https://api.z.ai/api/paas/v4",
    "ZAI_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zai_coding_plan,
    ZaiCodingPlanConfig,
    ZaiCodingPlanProvider,
    "Z.AI Coding Plan",
    "https://api.z.ai/api/anthropic",
    "ZHIPU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zeldoc,
    ZeldocConfig,
    ZeldocProvider,
    "Zeldoc",
    "https://api.zeldoc.ai/v1",
    "ZELDOC_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zenmux,
    ZenmuxConfig,
    ZenmuxProvider,
    "ZenMux",
    "https://zenmux.ai/api/v1",
    "ZENMUX_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zhipu_v4,
    ZhipuV4Config,
    ZhipuV4Provider,
    "ZhipuV4",
    "https://open.bigmodel.cn",
    "ZHIPU_API_KEY",
    OpenAICompatProfile::full()
);
declare_openai_compat_provider!(
    zhipuai_coding_plan,
    ZhipuaiCodingPlanConfig,
    ZhipuaiCodingPlanProvider,
    "Zhipu AI Coding Plan",
    "https://docs.bigmodel.cn/cn/coding-plan/quick-start",
    "ZHIPU_API_KEY",
    OpenAICompatProfile::full()
);
