//! Registry-backed provider construction (RFC-0017 phase 4).
//!
//! Single source of truth: [`provider_registry.json`](provider_registry.json)
//! (generated by `scripts/gen_provider_registry.py`). All built-in
//! OpenAI-compatible providers are looked up by name at runtime — there are no
//! per-provider `XxxConfig`/`XxxProvider` types anymore (retired in phase 4).
//!
//! ```
//! use aimux_providers::{provider, ProviderOptions};
//!
//! # fn smoke() -> Result<(), aimux_core::error::AiMuxError> {
//! // Key from env var (GROQ_API_KEY), base URL & profile from the registry.
//! let model = provider("groq", None, "llama-3.3-70b", None)?;
//! # let _ = model;
//! # Ok(())
//! # }
//! ```

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::Value;

use aimux_core::error::AiMuxError;
use aimux_core::language_model::LanguageModel;
use aimux_core::provider::Provider;
use aimux_provider_utils::RetryConfig;

use crate::openai::{OpenAICompatProfile, OpenAIConfig, OpenAIProvider};
use crate::provider_name::ProviderName;

/// One entry of `provider-registry.json` (registry slice).
#[derive(Debug, Clone, Deserialize)]
struct RegistryEntry {
    name: String,
    display: String,
    base_url: String,
    env_var: String,
    #[serde(default)]
    profile: RegistryProfile,
}

/// Profile differences expressed as data (non-default fields only in JSON).
#[derive(Debug, Clone, Default, Deserialize)]
struct RegistryProfile {
    #[serde(default = "default_true")]
    supports_top_k: bool,
    #[serde(default = "default_true")]
    supports_tools: bool,
    #[serde(default = "default_true")]
    supports_response_format: bool,
    stream_usage_key: Option<String>,
    max_tokens_key: Option<String>,
}

fn default_true() -> bool {
    true
}

static REGISTRY: OnceLock<Vec<RegistryEntry>> = OnceLock::new();

/// Load + validate the embedded registry exactly once.
fn registry() -> &'static [RegistryEntry] {
    REGISTRY.get_or_init(|| {
        let raw = include_str!("provider_registry.json");
        let entries: Vec<RegistryEntry> = serde_json::from_str(raw).unwrap_or_else(|e| {
            panic!(
                "provider_registry.json is invalid: {e} — regenerate with \
                 scripts/gen_provider_registry.py"
            )
        });
        for entry in &entries {
            assert!(!entry.name.is_empty(), "registry entry missing name");
            assert!(
                !entry.display.is_empty(),
                "registry entry '{}' missing display",
                entry.name
            );
            assert!(
                !entry.base_url.is_empty(),
                "registry entry '{}' missing base_url",
                entry.name
            );
            assert!(
                !entry.env_var.is_empty(),
                "registry entry '{}' missing env_var",
                entry.name
            );
        }
        entries
    })
}

/// Per-call construction options for [`provider`] (overrides the registry entry).
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ProviderOptions {
    /// Override the registry base URL.
    pub base_url: Option<String>,
    /// Extra headers merged into every request.
    pub headers: Option<HashMap<String, String>>,
    /// OpenAI organization ID (`OpenAI-Organization` header).
    pub organization: Option<String>,
    /// OpenAI project ID (`OpenAI-Project` header).
    pub project: Option<String>,
    /// Retry count override; `Some(0)` disables retries.
    pub max_retries: Option<u32>,
    /// Request-body overrides (deep-merged; RFC-0017 phase 1).
    pub body_overrides: Option<Value>,
}

/// Build a language model for a built-in provider by name.
///
/// - `api_key = None` reads the provider's env var from the registry entry
///   (replaces the retired `XxxConfig::from_env()`).
/// - `options` overrides individual fields of the registry entry
///   (replaces the retired `with_base_url` etc.).
/// - Unknown names return [`AiMuxError::UnknownProvider`] with the full list.
pub fn provider(
    name: impl AsRef<str>,
    api_key: Option<String>,
    model_id: &str,
    options: Option<ProviderOptions>,
) -> Result<Box<dyn LanguageModel>, AiMuxError> {
    let name = name.as_ref();
    let entry = registry().iter().find(|e| e.name == name).ok_or_else(|| {
        AiMuxError::UnknownProvider(format!(
            "unknown provider '{name}' — available providers: {}",
            ProviderName::all_names()
        ))
    })?;

    let key = match api_key {
        Some(key) => key,
        None => aimux_provider_utils::load_api_key(None, &entry.env_var, &entry.display)?,
    };

    let mut config = OpenAIConfig::new(key)
        .with_base_url(entry.base_url.clone())
        .with_provider(entry.name.clone())
        .with_profile(profile_from_registry(&entry.profile));

    if let Some(opts) = options {
        if let Some(url) = opts.base_url {
            config = config.with_base_url(url);
        }
        if let Some(headers) = opts.headers {
            config = config.with_headers(headers);
        }
        if let Some(org) = opts.organization {
            config = config.with_org_id(org);
        }
        if let Some(project) = opts.project {
            config = config.with_project(project);
        }
        if let Some(max_retries) = opts.max_retries {
            config = config.with_retry_config(RetryConfig {
                max_retries,
                ..RetryConfig::default()
            });
        }
        if let Some(overrides) = opts.body_overrides {
            config = config.with_body_overrides(overrides);
        }
    }

    OpenAIProvider::new(config).language_model(model_id)
}

/// Translate a registry profile into the runtime profile.
///
/// `stream_usage_key` / `max_tokens_key` are `&'static str` in
/// `OpenAICompatProfile`; the registry strings are leaked once at first use
/// (bounded: at most one string per field per entry).
fn profile_from_registry(p: &RegistryProfile) -> OpenAICompatProfile {
    OpenAICompatProfile {
        supports_top_k: p.supports_top_k,
        supports_tools: p.supports_tools,
        supports_response_format: p.supports_response_format,
        stream_usage_key: p.stream_usage_key.as_deref().map(|s| {
            let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
            leaked
        }),
        max_tokens_key: p.max_tokens_key.as_deref().map(|s| {
            let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
            leaked
        }),
    }
}

/// Convenience: build from the env-var key of the registry entry.
pub fn provider_from_env(
    name: impl AsRef<str>,
    model_id: &str,
    options: Option<ProviderOptions>,
) -> Result<Box<dyn LanguageModel>, AiMuxError> {
    provider(name, None, model_id, options)
}

/// Public lookup of a registered provider's runtime profile — used by tests
/// that assert registry wiring (e.g. `max_tokens_key`) without constructing a
/// model. Returns `None` for unknown provider names.
pub fn provider_registry_entry(name: &str) -> Option<OpenAICompatProfile> {
    registry()
        .iter()
        .find(|e| e.name == name)
        .map(|e| profile_from_registry(&e.profile))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provider_builds_groq_model() {
        let model = match provider("groq", Some("sk-test".into()), "llama-3.3-70b", None) {
            Ok(m) => m,
            Err(e) => panic!("groq should construct: {e}"),
        };
        assert_eq!(model.provider(), "openai"); // LanguageModel::provider() is the protocol impl name (same as before phase 4)
        assert_eq!(model.model_id(), "llama-3.3-70b");
    }

    #[test]
    fn provider_applies_registry_profile() {
        // groq entry: supports_top_k=false, stream_usage_key="x_groq",
        // max_tokens_key="max_completion_tokens" — verify the config carries them.
        let entry = registry().iter().find(|e| e.name == "groq").unwrap();
        let profile = profile_from_registry(&entry.profile);
        assert!(!profile.supports_top_k);
        assert_eq!(profile.stream_usage_key, Some("x_groq"));
        assert_eq!(profile.max_tokens_key, Some("max_completion_tokens"));

        // stepfun entry: max_tokens_key="max_tokens".
        let entry = registry().iter().find(|e| e.name == "stepfun").unwrap();
        let profile = profile_from_registry(&entry.profile);
        assert_eq!(profile.max_tokens_key, Some("max_tokens"));
    }

    #[test]
    fn provider_accepts_typed_and_string_names() {
        // Both spellings work: typed ProviderName (recommended) and string.
        let typed = match provider(ProviderName::Groq, Some("sk-test".into()), "llama-3.3-70b", None) {
            Ok(m) => m,
            Err(e) => panic!("typed name should construct: {e}"),
        };
        assert_eq!(typed.model_id(), "llama-3.3-70b");
        let string = match provider("groq", Some("sk-test".into()), "llama-3.3-70b", None) {
            Ok(m) => m,
            Err(e) => panic!("string name should construct: {e}"),
        };
        assert_eq!(string.model_id(), "llama-3.3-70b");
    }

    #[test]
    fn provider_unknown_name_lists_available() {
        let err = match provider("no-such-provider", Some("k".into()), "m", None) {
            Ok(_) => panic!("unknown name must fail"),
            Err(e) => e,
        };
        match err {
            AiMuxError::UnknownProvider(msg) => {
                assert!(msg.contains("no-such-provider"));
                assert!(
                    msg.contains("groq"),
                    "error should list available providers"
                );
            }
            other => panic!("expected UnknownProvider, got {other:?}"),
        }
    }

    #[test]
    fn provider_missing_env_key_fails() {
        // env var almost certainly unset in CI; the error must be the missing-key
        // error, not a registry problem.
        let err = match provider("abacus", None, "m", None) {
            Ok(_) => panic!("missing env key must fail"),
            Err(e) => e,
        };
        assert!(err.to_string().to_lowercase().contains("api key"));
    }

    #[test]
    fn registry_entries_are_valid() {
        let entries = registry();
        assert_eq!(entries.len(), 250);
        for e in entries {
            assert!(e.name.starts_with(|c: char| c.is_ascii_lowercase()));
            assert!(!e.base_url.is_empty());
            assert!(!e.env_var.is_empty());
        }
    }

    #[test]
    fn provider_name_roundtrip() {
        assert_eq!(ProviderName::Groq.as_str(), "groq");
        assert_eq!(
            "deepseek".parse::<ProviderName>().ok(),
            Some(ProviderName::Deepseek)
        );
        assert_eq!("nope".parse::<ProviderName>().ok(), None);
        assert!(ProviderName::all_names().contains("groq"));
        assert_eq!(ProviderName::ALL.len(), 250);
    }

    #[test]
    fn provider_name_matches_registry_json() {
        // Anti-drift: every registry name must exist as a ProviderName variant
        // and round-trip; counts must match (guards against editing the JSON
        // without regenerating provider_name.rs).
        let registry: serde_json::Value =
            serde_json::from_str(include_str!("provider_registry.json"))
                .expect("registry JSON is valid");
        let names: Vec<&str> = registry
            .as_array()
            .expect("registry is an array")
            .iter()
            .map(|e| e["name"].as_str().expect("name is a string"))
            .collect();
        assert_eq!(ProviderName::ALL.len(), names.len());
        for name in &names {
            let variant = name
                .parse::<ProviderName>()
                .unwrap_or_else(|_| panic!("registry name {name} missing from ProviderName"));
            assert_eq!(variant.as_str(), *name);
        }
    }
}
