//! Registry-backed provider construction (RFC-0017 phase 4).
//!
//! Single source of truth: [`provider_registry.json`](provider_registry.json)
//! (generated by `scripts/gen_provider_registry.py`). All built-in
//! OpenAI-compatible providers are looked up by name at runtime — there are no
//! per-provider `XxxConfig`/`XxxProvider` types anymore (retired in phase 4).
//!
//! ```
//! use aimux_providers::{provider, ProviderOptions};
//!
//! # fn smoke() -> Result<(), aimux_core::error::AiMuxError> {
//! // Key from env var (GROQ_API_KEY), base URL & profile from the registry.
//! let model = provider("groq", None, "llama-3.3-70b", None)?;
//! # let _ = model;
//! # Ok(())
//! # }
//! ```

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::Value;

use aimux_core::error::AiMuxError;
use aimux_core::language_model::LanguageModel;
use aimux_core::provider::Provider;
use aimux_provider_utils::RetryConfig;

use crate::openai::{OpenAICompatProfile, OpenAIConfig, OpenAIProvider};
use crate::provider_name::ProviderName;

/// One entry of `provider-registry.json` (registry slice).
#[derive(Debug, Clone, Deserialize)]
struct RegistryEntry {
    name: String,
    display: String,
    base_url: String,
    env_var: String,
    #[serde(default)]
    profile: RegistryProfile,
}

/// Profile differences expressed as data (non-default fields only in JSON).
#[derive(Debug, Clone, Default, Deserialize)]
struct RegistryProfile {
    #[serde(default = "default_true")]
    supports_top_k: bool,
    #[serde(default = "default_true")]
    supports_tools: bool,
    #[serde(default = "default_true")]
    supports_response_format: bool,
    stream_usage_key: Option<String>,
    max_tokens_key: Option<String>,
}

fn default_true() -> bool {
    true
}

static REGISTRY: OnceLock<Vec<RegistryEntry>> = OnceLock::new();

/// Load + validate the embedded registry exactly once.
fn registry() -> &'static [RegistryEntry] {
    REGISTRY.get_or_init(|| {
        let raw = include_str!("provider_registry.json");
        let entries: Vec<RegistryEntry> = serde_json::from_str(raw).unwrap_or_else(|e| {
            panic!(
                "provider_registry.json is invalid: {e} — regenerate with \
                 scripts/gen_provider_registry.py"
            )
        });
        for entry in &entries {
            assert!(!entry.name.is_empty(), "registry entry missing name");
            assert!(
                !entry.display.is_empty(),
                "registry entry '{}' missing display",
                entry.name
            );
            assert!(
                !entry.base_url.is_empty(),
                "registry entry '{}' missing base_url",
                entry.name
            );
            assert!(
                !entry.env_var.is_empty(),
                "registry entry '{}' missing env_var",
                entry.name
            );
        }
        entries
    })
}

/// Detect unexpanded placeholder syntax in a registry `base_url`.
///
/// Templated entries (cloudflare, neon, snowflake, oci, ...) carry account- or
/// region-scoped placeholders that the caller must fill in via
/// [`ProviderOptions::base_url`]. Recognized forms: `{VAR}` (covers `${var}`
/// too) and `<host>`. If a new placeholder form is introduced in the
/// registry, extend this function.
fn base_url_has_placeholder(base_url: &str) -> bool {
    base_url.contains('{') || base_url.contains('<')
}

/// Per-call construction options for [`provider`] (overrides the registry entry).
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ProviderOptions {
    /// Override the registry base URL.
    pub base_url: Option<String>,
    /// Extra headers merged into every request.
    pub headers: Option<HashMap<String, String>>,
    /// OpenAI organization ID (`OpenAI-Organization` header).
    pub organization: Option<String>,
    /// OpenAI project ID (`OpenAI-Project` header).
    pub project: Option<String>,
    /// Retry count override; `Some(0)` disables retries.
    pub max_retries: Option<u32>,
    /// Request-body overrides (deep-merged; RFC-0017 phase 1).
    pub body_overrides: Option<Value>,
}

/// Build a language model for a built-in provider by name.
///
/// - `api_key = None` reads the provider's env var from the registry entry
///   (replaces the retired `XxxConfig::from_env()`).
/// - `options` overrides individual fields of the registry entry
///   (replaces the retired `with_base_url` etc.).
/// - Unknown names return [`AiMuxError::UnknownProvider`] with the full list.
pub fn provider(
    name: impl AsRef<str>,
    api_key: Option<String>,
    model_id: &str,
    options: Option<ProviderOptions>,
) -> Result<Box<dyn LanguageModel>, AiMuxError> {
    let p = provider_handle(name, api_key, options)?;
    p.language_model(model_id)
}

/// Build a **provider handle** for a built-in provider by name (RFC-0027).
///
/// Unlike [`provider`] (which binds to a single `model_id` and returns a
/// `LanguageModel`), this returns the [`Provider`] itself, so callers can call
/// [`Provider::list_models`] for runtime discovery, then
/// [`Provider::language_model`] on a chosen id.
///
/// Same key/options semantics as [`provider`].
pub fn provider_handle(
    name: impl AsRef<str>,
    api_key: Option<String>,
    options: Option<ProviderOptions>,
) -> Result<Box<dyn Provider>, AiMuxError> {
    let name = name.as_ref();
    let entry = registry().iter().find(|e| e.name == name).ok_or_else(|| {
        AiMuxError::UnknownProvider(format!(
            "unknown provider '{name}' — available providers: {}",
            ProviderName::all_names()
        ))
    })?;

    // Reject registry base_urls that still carry unexpanded placeholders
    // (e.g. cloudflare's `{CLOUDFLARE_ACCOUNT_ID}`, snowflake's
    // `<account-identifier>`). These entries are intentionally templated —
    // the caller MUST supply a concrete base_url via ProviderOptions.
    let base_url_overridden = options.as_ref().is_some_and(|o| o.base_url.is_some());
    if !base_url_overridden && base_url_has_placeholder(&entry.base_url) {
        return Err(AiMuxError::InvalidArgument(format!(
            "provider '{name}' has a templated base_url {:?} with an unexpanded \
             placeholder; pass a concrete `base_url` via ProviderOptions to use it",
            entry.base_url
        )));
    }

    // api_key 来源标注(回放重建用):显式传 key → explicit;否则 env。
    let source: Option<String> = if api_key.is_some() {
        Some("explicit".to_string())
    } else {
        Some(format!("env:{}", entry.env_var))
    };

    let key = match api_key {
        Some(key) => key,
        None => aimux_provider_utils::load_api_key(None, &entry.env_var, &entry.display)?,
    };

    let mut config = build_provider_config(entry, key, options);
    // api_key 来源标注(回放重建用):explicit/env 在 provider() 已解析。
    config = config.with_api_key_source(source.as_deref());
    Ok(Box::new(OpenAIProvider::new(config)))
}

/// Resolve the registry entry + options into a fully-wired `OpenAIConfig`.
fn build_provider_config(
    entry: &RegistryEntry,
    key: String,
    options: Option<ProviderOptions>,
) -> OpenAIConfig {
    let mut config = OpenAIConfig::new(key)
        .with_base_url(entry.base_url.clone())
        .with_provider(entry.name.clone())
        .with_profile(profile_from_registry(&entry.profile));

    if let Some(opts) = options {
        if let Some(url) = opts.base_url {
            config = config.with_base_url(url);
        }
        if let Some(headers) = opts.headers {
            config = config.with_headers(headers);
        }
        if let Some(org) = opts.organization {
            config = config.with_org_id(org);
        }
        if let Some(project) = opts.project {
            config = config.with_project(project);
        }
        if let Some(max_retries) = opts.max_retries {
            config = config.with_retry_config(RetryConfig {
                max_retries,
                ..RetryConfig::default()
            });
        }
        if let Some(overrides) = opts.body_overrides {
            config = config.with_body_overrides(overrides);
        }
    }
    config
}

/// Translate a registry profile into the runtime profile.
///
/// `stream_usage_key` / `max_tokens_key` are `&'static str` in
/// `OpenAICompatProfile`; the registry strings are leaked once at first use
/// (bounded: at most one string per field per entry).
fn profile_from_registry(p: &RegistryProfile) -> OpenAICompatProfile {
    OpenAICompatProfile {
        supports_top_k: p.supports_top_k,
        supports_tools: p.supports_tools,
        supports_response_format: p.supports_response_format,
        stream_usage_key: p.stream_usage_key.as_deref().map(|s| {
            let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
            leaked
        }),
        max_tokens_key: p.max_tokens_key.as_deref().map(|s| {
            let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
            leaked
        }),
    }
}

/// Convenience: build from the env-var key of the registry entry.
pub fn provider_from_env(
    name: impl AsRef<str>,
    model_id: &str,
    options: Option<ProviderOptions>,
) -> Result<Box<dyn LanguageModel>, AiMuxError> {
    provider(name, None, model_id, options)
}

/// Public lookup of a registered provider's runtime profile — used by tests
/// that assert registry wiring (e.g. `max_tokens_key`) without constructing a
/// model. Returns `None` for unknown provider names.
pub fn provider_registry_entry(name: &str) -> Option<OpenAICompatProfile> {
    registry()
        .iter()
        .find(|e| e.name == name)
        .map(|e| profile_from_registry(&e.profile))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provider_builds_groq_model() {
        let model = match provider("groq", Some("sk-test".into()), "llama-3.3-70b", None) {
            Ok(m) => m,
            Err(e) => panic!("groq should construct: {e}"),
        };
        assert_eq!(model.provider(), "openai"); // LanguageModel::provider() is the protocol impl name (same as before phase 4)
        assert_eq!(model.model_id(), "llama-3.3-70b");
    }

    #[test]
    fn provider_applies_registry_profile() {
        // groq entry: supports_top_k=false, stream_usage_key="x_groq",
        // max_tokens_key="max_completion_tokens" — verify the config carries them.
        let entry = registry().iter().find(|e| e.name == "groq").unwrap();
        let profile = profile_from_registry(&entry.profile);
        assert!(!profile.supports_top_k);
        assert_eq!(profile.stream_usage_key, Some("x_groq"));
        assert_eq!(profile.max_tokens_key, Some("max_completion_tokens"));

        // stepfun entry: max_tokens_key="max_tokens".
        let entry = registry().iter().find(|e| e.name == "stepfun").unwrap();
        let profile = profile_from_registry(&entry.profile);
        assert_eq!(profile.max_tokens_key, Some("max_tokens"));
    }

    #[test]
    fn provider_accepts_typed_and_string_names() {
        // Both spellings work: typed ProviderName (recommended) and string.
        let typed = match provider(
            ProviderName::Groq,
            Some("sk-test".into()),
            "llama-3.3-70b",
            None,
        ) {
            Ok(m) => m,
            Err(e) => panic!("typed name should construct: {e}"),
        };
        assert_eq!(typed.model_id(), "llama-3.3-70b");
        let string = match provider("groq", Some("sk-test".into()), "llama-3.3-70b", None) {
            Ok(m) => m,
            Err(e) => panic!("string name should construct: {e}"),
        };
        assert_eq!(string.model_id(), "llama-3.3-70b");
    }

    #[test]
    fn provider_unknown_name_lists_available() {
        let err = match provider("no-such-provider", Some("k".into()), "m", None) {
            Ok(_) => panic!("unknown name must fail"),
            Err(e) => e,
        };
        match err {
            AiMuxError::UnknownProvider(msg) => {
                assert!(msg.contains("no-such-provider"));
                assert!(
                    msg.contains("groq"),
                    "error should list available providers"
                );
            }
            other => panic!("expected UnknownProvider, got {other:?}"),
        }
    }

    #[test]
    fn provider_missing_env_key_fails() {
        // env var almost certainly unset in CI; the error must be the missing-key
        // error, not a registry problem.
        let err = match provider("abacus", None, "m", None) {
            Ok(_) => panic!("missing env key must fail"),
            Err(e) => e,
        };
        assert!(err.to_string().to_lowercase().contains("api key"));
    }

    #[test]
    fn registry_entries_are_valid() {
        let entries = registry();
        assert_eq!(entries.len(), 251);
        for e in entries {
            assert!(e.name.starts_with(|c: char| c.is_ascii_lowercase()));
            assert!(!e.base_url.is_empty());
            assert!(!e.env_var.is_empty());
        }
    }

    #[test]
    fn registry_no_corrupt_base_urls() {
        // Issue #90 R2: no registry base_url may carry non-ASCII pollution
        // or be a non-URL fragment. Templated placeholders (cloudflare/neon/
        // snowflake/oci) are allowed but rejected at construct time — see
        // provider_handle's base_url_has_placeholder check.
        for e in registry() {
            assert!(
                e.base_url.starts_with("https://") || e.base_url.starts_with("http://"),
                "registry entry '{}' has a non-URL base_url: {:?}",
                e.name,
                e.base_url
            );
            assert!(
                e.base_url.is_ascii(),
                "registry entry '{}' base_url has non-ASCII chars: {:?}",
                e.name,
                e.base_url
            );
        }
    }

    #[test]
    fn registry_fixed_base_urls_are_correct() {
        // Issue #90 R2: pin the corrected base_urls for entries that were
        // broken (regression guard against reverting to the old bad values).
        let by_name: std::collections::HashMap<&str, &str> = registry()
            .iter()
            .map(|e| (e.name.as_str(), e.base_url.as_str()))
            .collect();
        assert_eq!(
            by_name.get("xpersona").copied(),
            Some("https://www.xpersona.co/v1"),
            "xpersona base_url was '/v1' (truncated); must be the full URL"
        );
        assert_eq!(
            by_name.get("moonshotai_cn").copied(),
            Some("https://api.moonshot.cn/anthropic/v1"),
            "moonshotai_cn base_url had a leaked '（Anthropic' annotation suffix"
        );
        assert_eq!(
            by_name.get("zhipuai_coding_plan").copied(),
            Some("https://open.bigmodel.cn/api/coding/paas/v4"),
            "zhipuai_coding_plan base_url was a docs page, not the API endpoint"
        );
        assert_eq!(
            by_name.get("the_grid_ai").copied(),
            Some("https://api.thegrid.ai/v1"),
            "the_grid_ai base_url was a docs page, not the API endpoint"
        );
    }

    #[test]
    fn provider_rejects_templated_base_url_without_override() {
        // Both placeholder forms must be rejected without an override:
        // cloudflare uses `{CLOUDFLARE_ACCOUNT_ID}`, snowflake uses
        // `<account-identifier>` — exercise both so `base_url_has_placeholder`
        // can't silently lose one form.
        for name in ["cloudflare", "snowflake"] {
            let err = match provider(name, Some("dummy".into()), "m", None) {
                Ok(_) => panic!("templated base_url for '{name}' without override must fail"),
                Err(e) => e,
            };
            assert!(
                matches!(err, AiMuxError::InvalidArgument(_)),
                "expected InvalidArgument for '{name}' templated base_url, got {err:?}"
            );
        }
    }

    #[test]
    fn provider_accepts_templated_base_url_with_override() {
        // With a concrete base_url override, the templated entry must construct
        // fine (key is dummy; we only assert it gets past validation).
        let res = provider(
            "cloudflare",
            Some("dummy".into()),
            "m",
            Some(ProviderOptions {
                base_url: Some("https://example.com/v1".into()),
                ..Default::default()
            }),
        );
        assert!(res.is_ok(), "override should bypass placeholder check");
    }

    #[test]
    fn provider_name_roundtrip() {
        assert_eq!(ProviderName::Groq.as_str(), "groq");
        assert_eq!(
            "deepseek".parse::<ProviderName>().ok(),
            Some(ProviderName::Deepseek)
        );
        assert_eq!("nope".parse::<ProviderName>().ok(), None);
        assert!(ProviderName::all_names().contains("groq"));
        assert_eq!(ProviderName::ALL.len(), 251);
    }

    #[test]
    fn provider_name_matches_registry_json() {
        // Anti-drift: every registry name must exist as a ProviderName variant
        // and round-trip; counts must match (guards against editing the JSON
        // without regenerating provider_name.rs).
        let registry: serde_json::Value =
            serde_json::from_str(include_str!("provider_registry.json"))
                .expect("registry JSON is valid");
        let names: Vec<&str> = registry
            .as_array()
            .expect("registry is an array")
            .iter()
            .map(|e| e["name"].as_str().expect("name is a string"))
            .collect();
        assert_eq!(ProviderName::ALL.len(), names.len());
        for name in &names {
            let variant = name
                .parse::<ProviderName>()
                .unwrap_or_else(|_| panic!("registry name {name} missing from ProviderName"));
            assert_eq!(variant.as_str(), *name);
        }
    }
}
