#!/usr/bin/env python3
"""Regenerate ts-rs TypeScript bindings from Rust core types.

The Rust types in aimux-core carry #[derive(TS)] + #[ts(export)]; running the
export tests (cargo test -p aimux-core --lib export) writes the generated .ts
files to TS_RS_EXPORT_DIR. This script always exports into a temporary
directory first — the repo is never written by cargo directly — then either
syncs that output into bindings/node/src/types/ (default) or compares the two
trees and fails on any difference (--check). Comparing full file sets means a
deleted Rust type shows up as a stale .ts, and a forgotten `git add` of a new
type shows up as a missing one; a failed cargo run leaves the repo untouched.

Run this after changing any Rust type, and commit the generated files along
with the change.

Usage:
    python3 scripts/gen_ts_types.py             # regenerate bindings/node/src/types
    python3 scripts/gen_ts_types.py --check     # fail if committed output differs
                                                # (CI; read-only, repo untouched)
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TYPES_DIR = ROOT / "bindings" / "node" / "src" / "types"
TYPES_TS = ROOT / "bindings" / "node" / "src" / "types.ts"
# ProviderName.ts is generated by scripts/gen_provider_names.py and re-exported
# from index.ts directly as a value + type; it is not a ts-rs product, and this
# aggregate is type-only (it would erase the const), so it lives outside the
# generated set: never compared, never deleted, never re-exported here.
EXCLUDED = {"ProviderName.ts"}


def regenerate(export_dir: Path) -> None:
    """Run the ts-rs export tests, writing the .ts files into export_dir.

    The external TS_RS_EXPORT_DIR overrides the repo-relative default in
    .cargo/config.toml ([env] without force = true). Do not add force = true
    there: it would pin the export to the repo and leave export_dir empty,
    which main() below turns into a hard error.
    """
    env = {**os.environ, "TS_RS_EXPORT_DIR": str(export_dir)}
    subprocess.run(
        ["cargo", "test", "-p", "aimux-core", "--lib", "export"],
        cwd=ROOT,
        env=env,
        check=True,
    )


def manifest(root: Path, exclude: set[str] = frozenset()) -> dict[str, str]:
    """Map POSIX-style relative path -> content for every .ts under root."""
    return {
        p.relative_to(root).as_posix(): p.read_text(encoding="utf-8")
        for p in root.rglob("*.ts")
        if p.name not in exclude
    }


def aggregate(files: dict[str, str]) -> str:
    """The types.ts content: one type-only re-export per generated file."""
    lines = [
        "// Re-export all ts-rs generated types from bindings/node/src/types/.",
        "// Generated by scripts/gen_ts_types.py — do not edit manually.",
        "// Run scripts/gen_ts_types.py to regenerate after Rust type changes.",
        "",
    ]
    for f in sorted(files):
        lines.append(f"export type * from './types/{f.removesuffix('.ts')}'")
    return "\n".join(lines) + "\n"


def sync(expected: dict[str, str]) -> None:
    """Make TYPES_DIR match expected exactly (EXCLUDED files untouched)."""
    for rel in manifest(TYPES_DIR, EXCLUDED).keys() - expected.keys():
        (TYPES_DIR / rel).unlink()
    for rel, content in expected.items():
        path = TYPES_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    check = "--check" in sys.argv[1:]

    with tempfile.TemporaryDirectory(prefix="ts-rs-export-") as tmp:
        regenerate(Path(tmp))
        expected = manifest(Path(tmp))
        if not expected:
            print(
                "ERROR: the export tests wrote nothing to the temporary "
                "TS_RS_EXPORT_DIR — is it overridden with force = true in "
                ".cargo/config.toml?",
                file=sys.stderr,
            )
            return 2

    if not check:
        sync(expected)
        TYPES_TS.write_text(aggregate(expected), encoding="utf-8")
        print(f"{len(expected)} files written to {TYPES_DIR.relative_to(ROOT)}")
        return 0

    actual = manifest(TYPES_DIR, EXCLUDED) if TYPES_DIR.is_dir() else {}
    missing = sorted(expected.keys() - actual.keys())
    stale = sorted(actual.keys() - expected.keys())
    changed = sorted(k for k in expected.keys() & actual.keys() if expected[k] != actual[k])
    try:
        aggregate_ok = TYPES_TS.read_text(encoding="utf-8") == aggregate(expected)
    except FileNotFoundError:
        aggregate_ok = False

    if missing or stale or changed or not aggregate_ok:
        rel = TYPES_DIR.relative_to(ROOT)
        for f in missing:
            print(f"MISSING: {rel}/{f} (generated, but not committed)", file=sys.stderr)
        for f in stale:
            print(f"STALE: {rel}/{f} (committed, but no longer generated)", file=sys.stderr)
        for f in changed:
            print(f"CHANGED: {rel}/{f}", file=sys.stderr)
        if not aggregate_ok:
            print(f"CHANGED: {TYPES_TS.relative_to(ROOT)}", file=sys.stderr)
        print(
            "generated ts-rs types are out of sync — "
            "run scripts/gen_ts_types.py and commit the result",
            file=sys.stderr,
        )
        return 1

    print(f"{len(expected)} files up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
