"""Generate ProviderName derived types from provider-registry.json (RFC-0017 phase 4).

Produces (all checked-in, one per language):
- aimux-providers/src/provider_name.rs            (Rust enum)
- bindings/node/src/types/ProviderName.ts          (TS string-literal union)
- bindings/go/provider_name.go                     (Go const group)
- bindings/python/python/aimux/provider_name.py    (Python Literal)
- bindings/java/src/main/java/io/aimux/ProviderName.java (Java String consts)
- bindings/kotlin/src/main/kotlin/aimux/ProviderName.kt  (Kotlin const object)
- bindings/swift/Sources/Aimux/ProviderName.swift  (Swift enum)
- bindings/flutter/lib/provider_name.dart          (Dart const class)

Usage: uv run python scripts/gen_provider_names.py
Idempotent: overwrites outputs.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON = ROOT / "aimux-providers" / "src" / "provider_registry.json"


def to_variant(name: str) -> str:
    """snake_case provider name -> PascalCase (abacus->Abacus, reka_ai->RekaAi)."""
    parts = name.split("_")
    out = []
    for p in parts:
        if not p:
            continue
        if p[0].isdigit():
            out.append(p)
        else:
            out.append(p[0].upper() + p[1:])
    return "".join(out)


def gen_rs(names):
    variants = "\n".join(f"    {to_variant(n)}," for n in names)
    arms_str = "\n".join(f'            Self::{to_variant(n)} => "{n}",' for n in names)
    arms_from = "\n".join(f'            "{n}" => Ok(Self::{to_variant(n)}),' for n in names)
    all_list = "\n".join(f"        Self::{to_variant(n)}," for n in names)
    return f"""//! Provider name enum — GENERATED by `scripts/gen_provider_names.py`.
//! Do not edit manually; single source of truth is `provider_registry.json`.

/// Names of all built-in OpenAI-compatible providers (registry-backed).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ProviderName {{
{variants}
}}

impl ProviderName {{
    /// All provider names, sorted.
    pub const ALL: &'static [ProviderName] = &[
{all_list}
    ];

    /// The registry name (snake_case), e.g. `ProviderName::Groq -> "groq"`.
    pub fn as_str(self) -> &'static str {{
        match self {{
{arms_str}
        }}
    }}

    /// All registry names (for error messages / docs).
    pub const fn all_names() -> &'static str {{
        "{','.join(names)}"
    }}
}}

impl std::str::FromStr for ProviderName {{
    type Err = ();

    fn from_str(name: &str) -> Result<Self, Self::Err> {{
        match name {{
{arms_from}
            _ => Err(()),
        }}
    }}
}}

impl std::fmt::Display for ProviderName {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        f.write_str(self.as_str())
    }}
}}
"""


def gen_ts(names):
    union = " | ".join(f"'{n}'" for n in names)
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.

/** Names of all built-in OpenAI-compatible providers. */
export type ProviderName = {union}
"""


def gen_go(names):
    consts = "\n".join(
        f'\t{to_variant(n)} ProviderName = "{n}"' for n in names
    )
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.
package aimux

// ProviderName is the registry name of a built-in OpenAI-compatible provider.
type ProviderName string

const (
{consts}
)
"""


def gen_py(names):
    lit = ", ".join(f"{n!r}" for n in names)
    return f'''"""ProviderName — GENERATED by `scripts/gen_provider_names.py`.

Do not edit manually; single source of truth is `provider-registry.json`.
"""

from typing import Literal

ProviderName = Literal[{lit}]
'''


def gen_java(names):
    consts = "\n".join(
        f'    public static final String {to_variant(n).upper()} = "{n}";'
        for n in names
    )
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.
package io.aimux;

/** Names of all built-in OpenAI-compatible providers. */
public final class ProviderName {{
    private ProviderName() {{}}

{consts}
}}
"""


def gen_kotlin(names):
    consts = "\n".join(
        f'    const val {to_variant(n).upper()} = "{n}"' for n in names
    )
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.
package aimux

/** Names of all built-in OpenAI-compatible providers. */
object ProviderName {{
{consts}
}}
"""


def gen_swift(names):
    cases = "\n".join(f"    case {to_variant(n)}" for n in names)
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.

/// Names of all built-in OpenAI-compatible providers.
public enum ProviderName: String, CaseIterable, Sendable {{
{cases}
}}
"""


def gen_dart(names):
    consts = "\n".join(f"  static const {to_variant(n)} = '{n}';" for n in names)
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.

/// Names of all built-in OpenAI-compatible providers.
class ProviderName {{
  ProviderName._();
{consts}
}}
"""


OUTPUTS = {
    "aimux-providers/src/provider_name.rs": gen_rs,
    "bindings/node/src/types/ProviderName.ts": gen_ts,
    "bindings/go/provider_name.go": gen_go,
    "bindings/python/python/aimux/provider_name.py": gen_py,
    "bindings/java/src/main/java/io/aimux/ProviderName.java": gen_java,
    "bindings/kotlin/src/main/kotlin/aimux/ProviderName.kt": gen_kotlin,
    "bindings/swift/Sources/Aimux/ProviderName.swift": gen_swift,
    "bindings/flutter/lib/provider_name.dart": gen_dart,
}


def main() -> int:
    entries = json.loads(JSON.read_text(encoding="utf-8"))
    names = sorted(e["name"] for e in entries)
    for rel, gen in OUTPUTS.items():
        out = ROOT / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(gen(names), encoding="utf-8")
        print(f"{len(names)} names -> {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
