#!/usr/bin/env python3
"""Generate aimux-providers/src/presets/*.rs from provider_registry.json.

Every registry row becomes an explicit factory module (RFC-0036 section 5):

    pub mod ollama {
        pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor { .. };
        pub fn create_ollama(settings: PresetSettings) -> Result<PresetProvider, AiMuxError>;
        pub fn ollama() -> &'static PresetProvider;        // OnceLock, reads nothing, cannot fail
    }

Row schema (aimux-providers/src/provider_registry.json):

    name          required, [a-z][a-z0-9_]*
    display       required
    base_url      required; a template ("{param}") when `params` is given
    env_var       required unless auth is "none": the API key variable
    auth          "api_key" (default) | "none" (local server: no key, no Authorization)
    base_url_env  optional: variable holding the base URL
    family        "openai-compatible" (default) | "groq" | "deepseek" (own package dialect)
    params        optional: [{name, env: [..], default}] or
                  {name, derive: {from, map: {value: host}, otherwise: "{from}-..."}}
    profile       {} or {"max_tokens_key": "max_tokens" | "max_completion_tokens"}

Output (committed): presets/mod.rs plus one presets/<first letter>.rs per
initial. The letter files are `#[rustfmt::skip]`: they are generated text, and
`--check` is what keeps them honest.

Usage:
    python3 scripts/gen_presets.py           # write the files
    python3 scripts/gen_presets.py --check   # exit 1 if the committed files differ
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "aimux-providers" / "src" / "provider_registry.json"
OUT_DIR = ROOT / "aimux-providers" / "src" / "presets"

ROW_KEYS = {
    "name", "display", "family", "base_url", "env_var", "auth", "base_url_env", "params", "profile",
}
FAMILIES = {
    "openai-compatible": "OpenAICompatible",
    "groq": "Groq",
    "deepseek": "DeepSeek",
}
AUTHS = {"api_key": "ApiKey", "none": "None"}
MAX_TOKENS_KEYS = {"max_tokens", "max_completion_tokens"}
# Names the generated `presets` module itself defines.
RESERVED = {"entries", "names", "lookup", "groups", "mod", "self", "super", "crate"}
RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
}

HEADER = "// @generated by scripts/gen_presets.py from provider_registry.json - do not edit by hand.\n"


class RegistryError(Exception):
    pass


def lit(value: str) -> str:
    """A Rust string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def doc_text(value: str) -> str:
    """Plain text safe inside a rustdoc line (no links, tags or emphasis)."""
    return re.sub(r"([\[\]<>*_`\\])", r"\\\1", value)


def load_registry() -> list[dict]:
    rows = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise RegistryError("registry must be a JSON array")
    seen: set[str] = set()
    for row in rows:
        validate_row(row)
        if row["name"] in seen:
            raise RegistryError(f"duplicate registry name {row['name']!r}")
        seen.add(row["name"])
    return sorted(rows, key=lambda r: r["name"])


def validate_row(row: dict) -> None:
    name = row.get("name", "<missing>")

    def fail(message: str) -> None:
        raise RegistryError(f"registry row {name!r}: {message}")

    extra = set(row) - ROW_KEYS
    if extra:
        fail(f"unknown keys {sorted(extra)}")
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        fail("name must match [a-z][a-z0-9_]*")
    if name in RESERVED or name in RUST_KEYWORDS:
        fail("name collides with a reserved identifier")
    if not row.get("display"):
        fail("missing display")
    if not row.get("base_url", "").startswith(("http://", "https://")):
        fail("base_url must start with http(s)://")
    if not row["base_url"].isascii():
        fail("base_url must be ASCII")
    family = row.get("family", "openai-compatible")
    if family not in FAMILIES:
        fail(f"unknown family {family!r}")
    auth = row.get("auth", "api_key")
    if auth not in AUTHS:
        fail(f"unknown auth {auth!r}")
    if auth == "api_key" and not row.get("env_var"):
        fail("auth api_key needs env_var")
    if auth == "none" and row.get("env_var"):
        fail("auth none must not have env_var")
    if "base_url_env" in row and not re.fullmatch(r"[A-Z][A-Z0-9_]*", row["base_url_env"]):
        fail("base_url_env must be an environment variable name")
    profile = row.get("profile", {})
    if set(profile) - {"max_tokens_key"}:
        fail(f"unknown profile keys {sorted(set(profile) - {'max_tokens_key'})}")
    if "max_tokens_key" in profile and profile["max_tokens_key"] not in MAX_TOKENS_KEYS:
        fail(f"max_tokens_key must be one of {sorted(MAX_TOKENS_KEYS)}")
    params = row.get("params", [])
    names = []
    for param in params:
        if set(param) - {"name", "env", "default", "derive"}:
            fail(f"unknown param keys in {param}")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", param.get("name", "")):
            fail(f"bad param name in {param}")
        names.append(param["name"])
        if "derive" in param:
            if set(param) - {"name", "derive"}:
                fail(f"derived param {param['name']!r} takes no env or default")
            derive = param["derive"]
            if set(derive) != {"from", "map", "otherwise"}:
                fail(f"derive of {param['name']!r} needs from, map and otherwise")
    for param in params:
        if "derive" in param:
            source = param["derive"]["from"]
            if source not in names or any(
                p["name"] == source and "derive" in p for p in params
            ):
                fail(f"derived param {param['name']!r} must derive from a plain param")
    if len(set(names)) != len(names):
        fail("duplicate param names")
    placeholders = set(re.findall(r"\{([^{}]*)\}", row["base_url"]))
    if placeholders != set(names):
        fail(
            f"base_url placeholders {sorted(placeholders)} must equal params {sorted(names)}"
        )
    if re.search(r"[<>$]", row["base_url"]):
        fail("base_url may only use {param} placeholders")


def render_param(param: dict, indent: str) -> str:
    env = ", ".join(lit(v) for v in param.get("env", []))
    default = f"Some({lit(param['default'])})" if "default" in param else "None"
    if "derive" in param:
        derive = param["derive"]
        pairs = ", ".join(f"({lit(k)}, {lit(v)})" for k, v in derive["map"].items())
        derive_src = (
            f"Some(DeriveSpec {{ from: {lit(derive['from'])}, map: &[{pairs}], "
            f"otherwise: {lit(derive['otherwise'])} }})"
        )
    else:
        derive_src = "None"
    return (
        f"{indent}ParamSpec {{ name: {lit(param['name'])}, env: &[{env}], "
        f"default: {default}, derive: {derive_src} }},"
    )


def render_row(row: dict) -> str:
    name = row["name"]
    family = FAMILIES[row.get("family", "openai-compatible")]
    auth = AUTHS[row.get("auth", "api_key")]
    max_tokens_key = row.get("profile", {}).get("max_tokens_key")
    params = row.get("params", [])
    imports = ["AuthMode", "PresetDescriptor", "PresetFamily", "PresetProvider", "PresetSettings"]
    if any("derive" in p for p in params):
        imports.append("DeriveSpec")
    if params:
        imports.append("ParamSpec")
    imports.sort()
    lines = [
        f"/// The `{name}` preset ({doc_text(row['display'])}).",
        f"pub mod {name} {{",
        f"    use crate::preset::{{{', '.join(imports)}}};",
        "    use aimux_core::AiMuxError;",
        "    use std::sync::OnceLock;",
        "",
        "    /// The registry row.",
        "    pub const DESCRIPTOR: PresetDescriptor = PresetDescriptor {",
        f"        name: {lit(name)},",
        f"        display: {lit(row['display'])},",
        f"        family: PresetFamily::{family},",
        f"        base_url: {lit(row['base_url'])},",
        f"        env_var: {lit(row.get('env_var', ''))},",
        f"        auth: AuthMode::{auth},",
        "        base_url_env: "
        + (f"Some({lit(row['base_url_env'])})" if "base_url_env" in row else "None")
        + ",",
        "        max_tokens_key: "
        + (f"Some({lit(max_tokens_key)})" if max_tokens_key else "None")
        + ",",
    ]
    if params:
        lines.append("        params: &[")
        lines.extend(render_param(p, "            ") for p in params)
        lines.append("        ],")
    else:
        lines.append("        params: &[],")
    lines += [
        "    };",
        "",
        f"    /// Create the `{name}` preset from explicit settings. Reads nothing from the",
        "    /// environment: the key and any environment-sourced URL are evaluated per request.",
        "    ///",
        "    /// # Errors",
        "    ///",
        "    /// `InvalidArgument` for an unusable `base_url`, an undeclared `params` key or a",
        "    /// `params` value that is not a plain segment.",
        f"    pub fn create_{name}(settings: PresetSettings) -> Result<PresetProvider, AiMuxError> {{",
        "        PresetProvider::create(&DESCRIPTOR, settings)",
        "    }",
        "",
        f"    /// The default `{name}` instance, created on first use. Creating it reads nothing",
        "    /// from the environment and cannot fail.",
        "    #[must_use]",
        f"    pub fn {name}() -> &'static PresetProvider {{",
        "        static DEFAULT: OnceLock<PresetProvider> = OnceLock::new();",
        "        DEFAULT.get_or_init(|| {",
        f"            create_{name}(PresetSettings::default())",
        '                .expect("default preset settings are always valid")',
        "        })",
        "    }",
        "}",
        f"pub use {name}::{{create_{name}, {name}}};",
    ]
    return "\n".join(lines) + "\n"


def render_letter(letter: str, rows: list[dict]) -> str:
    out = [HEADER]
    out.append("use crate::preset::PresetEntry;\n")
    out.append(f"pub(super) static ENTRIES_{letter.upper()}: &[PresetEntry] = &[")
    for row in rows:
        n = row["name"]
        out.append(
            f"    PresetEntry {{ descriptor: &{n}::DESCRIPTOR, create: {n}::create_{n} }},"
        )
    out.append("];\n")
    out.extend(render_row(row) for row in rows)
    return "\n".join(out)


def render_groups(letters: list[str]) -> str:
    """The `GROUPS` constant, laid out the way rustfmt lays out a short-element
    array: one line when it fits in 100 columns, otherwise packed lines."""
    items = [f"ENTRIES_{c.upper()}" for c in letters]
    one_line = "const GROUPS: &[&[PresetEntry]] = &[" + ", ".join(items) + "];"
    if len(one_line) <= 100:
        return one_line
    lines, current = [], "   "
    for item in items:
        if len(current) + 1 + len(item) + 1 > 100:
            lines.append(current)
            current = "   "
        current += f" {item},"
    lines.append(current)
    return "const GROUPS: &[&[PresetEntry]] = &[\n" + "\n".join(lines) + "\n];"


def render_mod(letters: list[str], total: int) -> str:
    groups = render_groups(letters)
    mods = "\n".join(f"#[rustfmt::skip]\nmod {c};" for c in letters)
    uses = "\n".join(f"pub use {c}::*;" for c in letters)
    return f"""{HEADER}//! The registry rows as explicit factories ({total} presets).
//!
//! **Generated** by `scripts/gen_presets.py` from `provider_registry.json`; do
//! not edit by hand (CI runs `gen_presets.py --check`).
//!
//! For every row `<name>`:
//!
//! - `presets::<name>::DESCRIPTOR` is its [`PresetDescriptor`](crate::preset::PresetDescriptor);
//! - `presets::create_<name>(PresetSettings)` creates a [`PresetProvider`](crate::preset::PresetProvider);
//! - `presets::<name>()` is the default instance (created on first use, reads
//!   nothing from the environment, cannot fail).
//!
//! [`lookup`] finds a preset by name for the by-name entry points.

use crate::preset::PresetEntry;

{mods}

{uses}

/// The presets of each initial, in name order.
{groups}

/// Every preset, in name order.
pub fn entries() -> impl Iterator<Item = &'static PresetEntry> {{
    GROUPS.iter().flat_map(|group| group.iter())
}}

/// The names of every preset, in order.
pub fn names() -> impl Iterator<Item = &'static str> {{
    entries().map(|entry| entry.descriptor.name)
}}

/// The preset called `name`, or `None`. An unknown name is never mapped to
/// another preset.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static PresetEntry> {{
    entries().find(|entry| entry.descriptor.name == name)
}}
"""


def generate() -> dict[Path, str]:
    rows = load_registry()
    by_letter: dict[str, list[dict]] = {}
    for row in rows:
        by_letter.setdefault(row["name"][0], []).append(row)
    letters = sorted(by_letter)
    files = {OUT_DIR / "mod.rs": render_mod(letters, len(rows))}
    for letter in letters:
        files[OUT_DIR / f"{letter}.rs"] = render_letter(letter, by_letter[letter])
    return files


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        files = generate()
    except RegistryError as error:
        print(f"gen_presets: {error}", file=sys.stderr)
        return 1
    if check:
        stale = []
        for path, text in files.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
        if OUT_DIR.is_dir():
            stale += [p for p in OUT_DIR.glob("*.rs") if p not in files]
        if stale:
            for path in sorted(stale):
                print(f"STALE: {path.relative_to(ROOT)}", file=sys.stderr)
            print(
                "run `python3 scripts/gen_presets.py` and commit the result", file=sys.stderr
            )
            return 1
        print(f"presets up to date ({len(files) - 1} files, {sum(1 for _ in load_registry())} presets)")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.rs"):
        if stale not in files:
            stale.unlink()
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files to {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
