#!/usr/bin/env python3
"""Generate ProviderName derived types from provider-registry.json (RFC-0017 phase 4).

Produces:
- aimux-providers/src/provider_name.rs   (Rust enum + as_str/from_str/Display/ALL)
- bindings/node/src/types/ProviderName.ts (TS string-literal union)

Checked-in generated files: run this script, commit the outputs. No build.rs.

Usage: uv run python scripts/gen_provider_names.py
Idempotent: overwrites outputs.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON = ROOT / "aimux-providers" / "src" / "provider_registry.json"
OUT_RS = ROOT / "aimux-providers" / "src" / "provider_name.rs"
OUT_TS = ROOT / "bindings" / "node" / "src" / "types" / "ProviderName.ts"


def to_variant(name: str) -> str:
    """snake_case provider name -> PascalCase Rust enum variant.

    abacus -> Abacus, abliteration_ai -> AbliterationAi, ai21 -> Ai21,
    reka_ai -> RekaAi. Digit-leading segments are kept as-is (ai21 -> Ai21).
    """
    parts = name.split("_")
    out = []
    for p in parts:
        if not p:
            continue
        if p[0].isdigit():
            out.append(p)
        else:
            out.append(p[0].upper() + p[1:])
    return "".join(out)


def gen_rs(names: list[str]) -> str:
    variants = "\n".join(f"    {to_variant(n)}," for n in names)
    arms_str = "\n".join(
        f'            Self::{to_variant(n)} => "{n}",' for n in names
    )
    arms_from = "\n".join(
        f'            "{n}" => Some(Self::{to_variant(n)}),' for n in names
    )
    all_list = "\n".join(
        f"        Self::{to_variant(n)}," for n in names
    )
    return f"""//! Provider name enum — GENERATED by `scripts/gen_provider_names.py`.
//! Do not edit manually; single source of truth is `provider_registry.json`.

/// Names of all built-in OpenAI-compatible providers (registry-backed).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ProviderName {{
{variants}
}}

impl ProviderName {{
    /// All provider names, sorted.
    pub const ALL: &'static [ProviderName] = &[
{all_list}
    ];

    /// The registry name (snake_case), e.g. `ProviderName::Groq -> "groq"`.
    pub fn as_str(self) -> &'static str {{
        match self {{
{arms_str}
        }}
    }}

    /// Look up a provider by its registry name.
    pub fn from_str(name: &str) -> Option<Self> {{
        match name {{
{arms_from}
            _ => None,
        }}
    }}

    /// All registry names (for error messages / docs).
    pub const fn all_names() -> &'static str {{
        "{','.join(names)}"
    }}
}}

impl std::fmt::Display for ProviderName {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        f.write_str(self.as_str())
    }}
}}
"""


def gen_ts(names: list[str]) -> str:
    union = " | ".join(f"'{n}'" for n in names)
    return f"""// ProviderName — GENERATED by `scripts/gen_provider_names.py`.
// Do not edit manually; single source of truth is `provider-registry.json`.

/** Names of all built-in OpenAI-compatible providers. */
export type ProviderName = {union}
"""


def main() -> int:
    entries = json.loads(JSON.read_text(encoding="utf-8"))
    names = [e["name"] for e in entries]
    names.sort()

    OUT_RS.write_text(gen_rs(names), encoding="utf-8")
    OUT_TS.write_text(gen_ts(names), encoding="utf-8")
    print(f"provider_name.rs: {len(names)} variants -> {OUT_RS.relative_to(ROOT)}")
    print(f"ProviderName.ts: {len(names)} literals -> {OUT_TS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
