// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingResponse } from "./EmbeddingResponse";
import type { EmbeddingUsage } from "./EmbeddingUsage";
import type { Warning } from "./Warning";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The result of [`EmbeddingModel::do_embed`].
 *
 * Aligned with V4 `EmbeddingModelV4Result`.
 */
export type EmbeddingResult = { 
/**
 * Generated embeddings, in the same order as the input `values`.
 */
embeddings: Array<Array<number>>, 
/**
 * Token usage (input tokens only).
 */
usage: EmbeddingUsage | null, 
/**
 * Additional provider-specific metadata.
 */
provider_metadata: { [key in string]: JsonValue } | null, 
/**
 * Optional response information for debugging.
 */
response: EmbeddingResponse | null, 
/**
 * Warnings for the call, e.g. unsupported settings.
 */
warnings: Array<Warning>, };
