// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A content item in the generation result.
 */
export type GenerateContent = { "Text": { text: string, } } | { "ToolCall": { tool_call_id: string, tool_name: string, input: JsonValue, } } | { "Source": { id: string, source_type: string, url: string | null, title: string | null, } } | { "Reasoning": { text: string, provider_metadata: JsonValue | null, } } | { "ToolResult": { tool_call_id: string, tool_name: string, result: JsonValue, } };
