// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning effort level (aligned with V4 `reasoning` option).
 *
 * Controls how much reasoning/thinking the model performs. Maps to
 * OpenAI `reasoning_effort` and Anthropic `thinking` config.
 */
export type ReasoningEffort = "provider-default" | "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
