// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage detail (with cache breakdown).
 */
export type TokenUsage = { 
/**
 * Total tokens.
 */
total: number | null, 
/**
 * Tokens that were not served from cache.
 */
no_cache: number | null, 
/**
 * Tokens served from cache (read).
 */
cache_read: number | null, 
/**
 * Tokens written to cache.
 */
cache_write: number | null, 
/**
 * Text (non-reasoning) tokens (output side).
 */
text: number | null, 
/**
 * Reasoning tokens (output side).
 */
reasoning: number | null, };
