//! `StreamPart` — the individual chunk types emitted by `do_stream`.
//!
//! Aligned with V4 `LanguageModelV4StreamPart`. v0.1 implements the P0/P1 variants;
//! P2 variants (reasoning, file, source) are defined but not yet emitted by providers.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use ts_rs::TS;

use crate::error::AiMuxError;
use crate::shared::FileData;
use crate::tool::{RawToolCall, ToolCall, ToolResult};
use crate::types::{FinishReason, ProviderMetadata, Usage, Warning};

/// A single chunk in the stream returned by `do_stream`.
///
/// Generic over the tool-call payload: providers emit the default
/// [`StreamPart`] (raw argument text); `stream_text` emits [`TextStreamPart`]
/// (parsed and validated [`ToolCall`]).
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, concrete(C = ToolCall))]
pub enum StreamPart<C = RawToolCall> {
    // ── P0: text ──
    /// Start of a text segment.
    TextStart {
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of generated text.
    TextDelta {
        id: String,
        delta: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a text segment.
    TextEnd {
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P0: stream lifecycle ──
    /// First chunk — carries warnings from the provider.
    StreamStart { warnings: Vec<Warning> },
    /// Final chunk — carries usage, finish reason, and metadata.
    Finish {
        finish_reason: FinishReason,
        usage: Usage,
        provider_metadata: Option<ProviderMetadata>,
    },
    /// An error occurred mid-stream.
    Error { error: AiMuxError },

    // ── P1: tool calls ──
    /// Start of a tool call's input streaming.
    ToolInputStart {
        id: String,
        tool_name: String,
        /// Whether the tool call will be executed by the provider.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_executed: Option<bool>,
        /// Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dynamic: Option<bool>,
        /// Optional title for the tool call.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of tool call input (partial JSON).
    ToolInputDelta {
        id: String,
        delta: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a tool call's input streaming.
    ToolInputEnd {
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A complete tool call (alternative to the start/delta/end flow).
    ///
    /// The provider layer emits [`RawToolCall`] (`input` is the raw argument
    /// text); `stream_text` re-emits the parsed [`ToolCall`] ([`TextStreamPart`]).
    ToolCall(C),
    /// A tool result (provider-executed tools).
    ToolResult(ToolResult),

    // ── P2: file ──
    /// A file generated by the model (e.g. an image or document).
    ///
    /// Mirrors the Vercel AI SDK `file` stream part. `data` is a tagged union
    /// covering base64 data, URL, or provider reference.
    File {
        data: FileData,
        media_type: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P2: reasoning ──
    ReasoningStart {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningDelta {
        id: String,
        delta: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningEnd {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
        #[allow(unused)]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P2: metadata ──
    /// Response metadata (id, timestamp, model_id).
    ResponseMetadata {
        id: Option<String>,
        timestamp: Option<String>,
        model_id: Option<String>,
    },

    /// A source / citation (e.g. URL citation from search-preview models).
    Source {
        id: String,
        source_type: String,
        url: Option<String>,
        title: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    /// A raw chunk from the provider (for debugging, when `include_raw_chunks` is set).
    Raw { raw_value: Value },
}

/// The stream `stream_text` and later stages produce: tool calls are parsed.
pub type TextStreamPart = StreamPart<ToolCall>;

impl<C> StreamPart<C> {
    /// Replace the tool-call payload, leaving every other variant untouched.
    pub fn map_tool_call<D>(self, f: impl FnOnce(C) -> D) -> StreamPart<D> {
        // The generic parameter forces every variant to be rebuilt.
        macro_rules! carry {
            ($($variant:ident { $($field:ident),* })*) => {
                match self {
                    StreamPart::ToolCall(call) => StreamPart::ToolCall(f(call)),
                    StreamPart::ToolResult(result) => StreamPart::ToolResult(result),
                    $(StreamPart::$variant { $($field),* } => StreamPart::$variant { $($field),* },)*
                }
            };
        }
        carry! {
            TextStart { id, provider_metadata }
            TextDelta { id, delta, provider_metadata }
            TextEnd { id, provider_metadata }
            StreamStart { warnings }
            Finish { finish_reason, usage, provider_metadata }
            Error { error }
            ToolInputStart { id, tool_name, provider_executed, dynamic, title, provider_metadata }
            ToolInputDelta { id, delta, provider_metadata }
            ToolInputEnd { id, provider_metadata }
            File { data, media_type, provider_metadata }
            ReasoningStart { id, provider_metadata }
            ReasoningDelta { id, delta, provider_metadata }
            ReasoningEnd { id, provider_metadata }
            ResponseMetadata { id, timestamp, model_id }
            Source { id, source_type, url, title, provider_metadata }
            Raw { raw_value }
        }
    }
}
