//! `StreamPart` — the individual chunk types emitted by `do_stream`.
//!
//! Aligned with V4 `LanguageModelV4StreamPart`. v0.1 implements the P0/P1 variants;
//! P2 variants (reasoning, file, source) are defined but not yet emitted by providers.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use ts_rs::TS;

use crate::error::AiMuxError;
use crate::result::{
    GeneratedFile, RawToolApprovalRequest, ReasoningFileOutput, Source, ToolApprovalRequestOutput,
};
use crate::tool::{RawToolCall, ToolCall, ToolResult};
use crate::types::{FinishReason, ProviderMetadata, ResponseMetadata, Usage, Warning};

/// A single chunk in the stream returned by `do_stream`.
///
/// Generic over the tool-call payload: providers emit the default
/// [`StreamPart`] (raw argument text); `stream_text` emits [`TextStreamPart`]
/// (parsed and validated [`ToolCall`]).
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(
    tag = "type",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase"
)]
#[ts(export, concrete(C = RawToolCall, A = RawToolApprovalRequest, R = GeneratedFile))]
pub enum StreamPart<C = RawToolCall, A = RawToolApprovalRequest, R = GeneratedFile> {
    // ── P0: text ──
    /// Start of a text segment.
    TextStart {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of generated text.
    TextDelta {
        id: String,
        delta: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a text segment.
    TextEnd {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P0: stream lifecycle ──
    /// First chunk — carries warnings from the provider.
    StreamStart {
        warnings: Vec<Warning>,
    },
    /// Final chunk — carries usage, finish reason, and metadata.
    Finish {
        finish_reason: FinishReason,
        usage: Usage,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// An error occurred mid-stream.
    Error {
        error: AiMuxError,
    },

    // ── P1: tool calls ──
    /// Start of a tool call's input streaming.
    ToolInputStart {
        id: String,
        tool_name: String,
        /// Whether the tool call will be executed by the provider.
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_executed: Option<bool>,
        /// Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dynamic: Option<bool>,
        /// Optional title for the tool call.
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of tool call input (partial JSON).
    ToolInputDelta {
        id: String,
        delta: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a tool call's input streaming.
    ToolInputEnd {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A complete tool call (alternative to the start/delta/end flow).
    ///
    /// The provider layer emits [`RawToolCall`] (`input` is the raw argument
    /// text); `stream_text` re-emits the parsed [`ToolCall`] ([`TextStreamPart`]).
    ToolCall(C),
    /// A tool result (provider-executed tools).
    ToolResult(ToolResult),

    // ── P2: file ──
    /// A file generated by the model (e.g. an image or document).
    File(GeneratedFile),
    ReasoningFile(R),
    Custom {
        kind: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ToolApprovalRequest(A),

    // ── P2: reasoning ──
    ReasoningStart {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningDelta {
        id: String,
        delta: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningEnd {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P2: metadata ──
    /// Response metadata (id, timestamp, model_id).
    ResponseMetadata(ResponseMetadata),

    /// A source / citation (e.g. URL citation from search-preview models).
    Source(Source),

    /// A raw chunk from the provider (for debugging, when `include_raw_chunks` is set).
    Raw {
        raw_value: Value,
    },
}

/// A public call-layer stream chunk, with parsed tool calls.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(
    tag = "type",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase"
)]
#[ts(export)]
pub enum TextStreamPart {
    // ── P0: text ──
    /// Start of a text segment.
    TextStart {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of generated text.
    TextDelta {
        id: String,
        delta: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a text segment.
    TextEnd {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    // ── P0: stream lifecycle ──
    /// First chunk — carries warnings from the provider.
    StreamStart {
        warnings: Vec<Warning>,
    },
    /// Final chunk — carries usage, finish reason, and metadata.
    Finish {
        finish_reason: FinishReason,
        usage: Usage,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A completed model call, including its response metadata.
    FinishStep {
        finish_reason: FinishReason,
        usage: Usage,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
        response: crate::shared::ResponseInfo,
    },
    /// An error occurred mid-stream.
    Error {
        error: AiMuxError,
    },

    // ── P1: tool calls ──
    /// Start of a tool call's input streaming.
    ToolInputStart {
        id: String,
        tool_name: String,
        /// Whether the tool call will be executed by the provider.
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_executed: Option<bool>,
        /// Whether the tool is dynamic (defined at runtime, e.g. MCP tools).
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dynamic: Option<bool>,
        /// Optional title for the tool call.
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A delta of tool call input (partial JSON).
    ToolInputDelta {
        id: String,
        delta: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// End of a tool call's input streaming.
    ToolInputEnd {
        id: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    /// A complete tool call (alternative to the start/delta/end flow).
    ///
    /// The provider layer emits [`RawToolCall`] (`input` is the raw argument
    /// text); `stream_text` re-emits the parsed [`ToolCall`] ([`TextStreamPart`]).
    ToolCall(ToolCall),
    /// A tool result (provider-executed tools).
    ToolResult(ToolResult),

    // ── P2: file ──
    /// A file generated by the model (e.g. an image or document).
    File(GeneratedFile),
    ReasoningFile(ReasoningFileOutput),
    Custom {
        kind: String,
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ToolApprovalRequest(ToolApprovalRequestOutput),

    // ── P2: reasoning ──
    ReasoningStart {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningDelta {
        id: String,
        delta: String,
        /// Provider-specific metadata (e.g. xAI `itemId`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },
    ReasoningEnd {
        id: String,
        /// Provider-specific metadata (e.g. xAI `itemId`, `reasoningEncryptedContent`).
        #[allow(unused)]
        #[ts(optional)]
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<ProviderMetadata>,
    },

    /// A source / citation (e.g. URL citation from search-preview models).
    Source(Source),

    /// A raw chunk from the provider (for debugging, when `include_raw_chunks` is set).
    Raw {
        raw_value: Value,
    },
}

impl<C, A, R> StreamPart<C, A, R> {
    /// Replace the tool-call payload, leaving every other variant untouched.
    pub fn map_tool_call<D>(self, f: impl FnOnce(C) -> D) -> StreamPart<D, A, R> {
        self.map_payloads(f, |approval| approval)
    }

    /// Replace the approval payload, leaving other variants untouched.
    pub fn map_tool_approval_request<B>(self, f: impl FnOnce(A) -> B) -> StreamPart<C, B, R> {
        self.map_payloads(|call| call, f)
    }

    /// Replace tool call and approval payloads.
    pub fn map_payloads<D, B>(
        self,
        call: impl FnOnce(C) -> D,
        approval: impl FnOnce(A) -> B,
    ) -> StreamPart<D, B, R> {
        self.map_all(call, approval, |file| file)
    }

    /// Replace a reasoning file with its user-facing output wrapper.
    pub fn map_reasoning_file<F>(self, f: impl FnOnce(R) -> F) -> StreamPart<C, A, F> {
        self.map_all(|call| call, |approval| approval, f)
    }

    fn map_all<D, B, F>(
        self,
        call: impl FnOnce(C) -> D,
        approval: impl FnOnce(A) -> B,
        file: impl FnOnce(R) -> F,
    ) -> StreamPart<D, B, F> {
        // The generic parameter forces every variant to be rebuilt.
        macro_rules! carry {
            ($($variant:ident { $($field:ident),* })*) => {
                match self {
                    StreamPart::ToolCall(value) => StreamPart::ToolCall(call(value)),
                    StreamPart::ToolApprovalRequest(value) => StreamPart::ToolApprovalRequest(approval(value)),
                    StreamPart::ToolResult(result) => StreamPart::ToolResult(result),
                    StreamPart::File(file) => StreamPart::File(file),
                    StreamPart::ReasoningFile(value) => StreamPart::ReasoningFile(file(value)),
                    StreamPart::ResponseMetadata(meta) => StreamPart::ResponseMetadata(meta),
                    StreamPart::Source(source) => StreamPart::Source(source),
                    $(StreamPart::$variant { $($field),* } => StreamPart::$variant { $($field),* },)*
                }
            };
        }
        carry! {
            TextStart { id, provider_metadata }
            TextDelta { id, delta, provider_metadata }
            TextEnd { id, provider_metadata }
            StreamStart { warnings }
            Finish { finish_reason, usage, provider_metadata }
            Error { error }
            ToolInputStart { id, tool_name, provider_executed, dynamic, title, provider_metadata }
            ToolInputDelta { id, delta, provider_metadata }
            ToolInputEnd { id, provider_metadata }
            ReasoningStart { id, provider_metadata }
            ReasoningDelta { id, delta, provider_metadata }
            ReasoningEnd { id, provider_metadata }
            Custom { kind, provider_metadata }
            Raw { raw_value }
        }
    }
}

impl StreamPart<ToolCall, ToolApprovalRequestOutput, ReasoningFileOutput> {
    /// Convert content chunks; the call layer absorbs metadata and finish chunks.
    #[must_use]
    pub fn into_text_stream_part(self) -> Option<TextStreamPart> {
        macro_rules! carry {
            ($($variant:ident { $($field:ident),* })*) => {
                match self {
                    Self::ResponseMetadata(_) | Self::Finish { .. } => None,
                    Self::ToolCall(value) => Some(TextStreamPart::ToolCall(value)),
                    Self::ToolApprovalRequest(value) => Some(TextStreamPart::ToolApprovalRequest(value)),
                    Self::ToolResult(value) => Some(TextStreamPart::ToolResult(value)),
                    Self::File(value) => Some(TextStreamPart::File(value)),
                    Self::ReasoningFile(value) => Some(TextStreamPart::ReasoningFile(value)),
                    Self::Source(value) => Some(TextStreamPart::Source(value)),
                    $(Self::$variant { $($field),* } => Some(TextStreamPart::$variant { $($field),* }),)*
                }
            };
        }
        carry! {
            TextStart { id, provider_metadata }
            TextDelta { id, delta, provider_metadata }
            TextEnd { id, provider_metadata }
            StreamStart { warnings }
            Error { error }
            ToolInputStart { id, tool_name, provider_executed, dynamic, title, provider_metadata }
            ToolInputDelta { id, delta, provider_metadata }
            ToolInputEnd { id, provider_metadata }
            ReasoningStart { id, provider_metadata }
            ReasoningDelta { id, delta, provider_metadata }
            ReasoningEnd { id, provider_metadata }
            Custom { kind, provider_metadata }
            Raw { raw_value }
        }
    }
}

impl TextStreamPart {
    pub(crate) fn is_output_chunk(&self) -> bool {
        match self {
            Self::TextDelta { delta, .. }
            | Self::ReasoningDelta { delta, .. }
            | Self::ToolInputDelta { delta, .. } => !delta.is_empty(),
            Self::ToolCall(_) | Self::File(_) | Self::ReasoningFile(_) => true,
            _ => false,
        }
    }
}
